<template><div><h1 id="javascript" tabindex="-1"><a class="header-anchor" href="#javascript" aria-hidden="true">#</a> JavaScript</h1>
<p>Benvido, estás a piques de comezar a aprender JavaScript, e este é só un repaso rápido para ensinarache a leer/escribir código.</p>
<p>Para crear aplicacións web con <strong>HTML, CSS, JavaScript</strong>. JavaScript é a linguaxe de programación que permite crear aplicacións web (páxinas web, sitio web), engadir interactividade e enriquecer a experiencia de usuario xa que permite facer un seguimento das accións dunha persoa no nosos sitio. JS non soe actuar soa. Para empregar JavaScript tamén imos ter que empregar , dun xeito ou outro, HTML e CSS.</p>
<p>Se empregas JavaScript desde o propio documento HTML escribe código JavaScript dentro de <strong><code v-pre>&lt;script&gt;&lt;/script&gt;</code></strong>:</p>
<div class="language-html line-numbers-mode" data-ext="html"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>script</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>text/javascript<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token script"><span class="token language-javascript">
  <span class="token function">alert</span><span class="token punctuation">(</span><span class="token string">"This alert box was called with the onload event"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>script</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Se non, enlaza o teu arquivo <em>*.js</em>, na cabeceira da páxina ou antes do peche de <code v-pre>&lt;/body&gt;</code> e sempre despois das follas de estilos, por se tiveras algunha dependencia alí.</p>
<div class="language-HTML line-numbers-mode" data-ext="HTML"><pre v-pre class="language-HTML"><code>&lt;script type=&quot;text/javascript&quot; src=&quot;path-to-javascript-file.js&quot;&gt;&lt;/script&gt;
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="variables" tabindex="-1"><a class="header-anchor" href="#variables" aria-hidden="true">#</a> Variables</h2>
<p>As variables son o primeiro que necesitamos entender, as variables axúdan a declarar o tipo de información que vas almacenar, podes almacenar: <strong>Números, Texto, Obxectos</strong>,... As variables se declaran usando as palabras clave <strong>var</strong> ou <strong>let</strong>.</p>
<p><strong><em>String</em> (cadea)</strong> :<br>
almacena datos de tipo texto. Coma nos seguintes exemplos:</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> fullName <span class="token operator">=</span> <span class="token string">"Auterpio Lumbreras"</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">let</span> country <span class="token operator">=</span> <span class="token string">"Nova Caledonia"</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><strong><em>Number</em>(número)</strong> :
calquera número, coma nos seguintes exemplos:</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> productQty <span class="token operator">=</span> <span class="token number">10</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> productPrice <span class="token operator">=</span> <span class="token number">2</span><span class="token punctuation">,</span><span class="token number">50</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><strong>Booleano</strong> :
podese usar cando se requira resolver unha decisión, o booleano é unha decisión que se resolve coma <code v-pre>true</code> (verdadeira) ou <code v-pre>false</code> (falsa). Os seguintes son exemplos de tipos de datos <strong>booleanos</strong> .</p>
<p><code v-pre>var isValid = true;</code></p>
<p><code v-pre>var isDone = false;</code></p>
<p><strong><em>Object</em> (obxecto)</strong> : o<br>
un obxecto úsase para almacenar outros contidos de referencia como propiedades de matrices. O seguinte é un exemplo do tipo de datos <strong>Object</strong> .</p>
<div class="language-text line-numbers-mode" data-ext="text"><pre v-pre class="language-text"><code>var Produto = {  
       "Name": "Apple",
    "Price": 1.50,
    "Quantity": 2,
    }
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Neste exemplo de variable obxecto describimos o seguinte:
O produto é unha variable.
Nome, Prezo e Cantidade son propiedades seguidas do seu valor. Propiedade e valor desa propiedade van separados por puntos dobres <code v-pre>:</code>.</p>
<h2 id="comentarios" tabindex="-1"><a class="header-anchor" href="#comentarios" aria-hidden="true">#</a> Comentarios</h2>
<p>Os comentarios son partes de texto que podes incluír en calquera parte do teu código para documentar o que estas a facer, para que serve,... . Podes usar <strong><code v-pre>//  </code></strong> para comentar unha soa liña de texto no teu código ou <strong><code v-pre>/* */</code></strong> para comentar varias liñas. O comentario non se executará aínda que teñas código nel, JavaScript ignora o bloque de comentarios, a sintaxe é a seguinte.</p>
<p><code v-pre>//Este é un comentario nunha soa liña.</code></p>
<div class="language-/* line-numbers-mode" data-ext="/*"><pre v-pre class="language-/*"><code>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="operadores" tabindex="-1"><a class="header-anchor" href="#operadores" aria-hidden="true">#</a> Operadores</h2>
<p>Os operadores poden ser de tipo <strong>Numeric, Boolean, String, Assignment</strong> <strong>(<em>numérico, booleano, cadea e asignación</em>)</strong></p>
<h3 id="operadores-numericos" tabindex="-1"><a class="header-anchor" href="#operadores-numericos" aria-hidden="true">#</a> Operadores numéricos</h3>
<p>Os <strong>operadores numéricos</strong> úsanse no cálculo matemático <strong><code v-pre>+</code>(sumar) <code v-pre>-</code>(restar) <code v-pre>*</code>(multiplicar) <code v-pre>/</code>(dividir)</strong> . 👁️ O signo <strong><code v-pre>+</code></strong> tamén se usa como concatenación de cadeas(<em>string</em>). Os seguintes son exemplos de operadores numéricos:</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>	<span class="token keyword">var</span> addiction <span class="token operator">=</span> <span class="token number">5</span> <span class="token operator">+</span> <span class="token number">2</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> subtraction <span class="token operator">=</span> <span class="token number">6</span> <span class="token operator">-</span> <span class="token number">2</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> multiplication <span class="token operator">=</span> <span class="token number">8</span> <span class="token operator">*</span> <span class="token number">3</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> division <span class="token operator">=</span> <span class="token number">4</span> <span class="token operator">/</span> <span class="token number">2</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> increment <span class="token operator">+=</span><span class="token number">1</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> decrement <span class="token operator">-=</span><span class="token number">1</span><span class="token punctuation">;</span> 
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="concatenacion-de-cadeas-strings" tabindex="-1"><a class="header-anchor" href="#concatenacion-de-cadeas-strings" aria-hidden="true">#</a> Concatenación de cadeas (<em>strings</em>)</h2>
<p>A concatenación de cadeas úsase cando necesitamos converter o valor de texto de diferentes variables nunha soa variable. Para iso se usa o signo  <strong><code v-pre>+</code></strong>, para concatenar o valor dos textos como segue.</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> concatenation <span class="token operator">=</span> <span class="token string">"O ceo é azul "</span> <span class="token operator">+</span> <span class="token string">"con moitas nubes brancas"</span><span class="token punctuation">;</span>
<span class="token keyword">var</span> firstName <span class="token operator">=</span> <span class="token string">"Melvin"</span><span class="token punctuation">;</span>
<span class="token keyword">var</span> lastName <span class="token operator">=</span> <span class="token string">"Hernandez"</span><span class="token punctuation">;</span>
<span class="token keyword">var</span> fullName <span class="token operator">=</span> firstName <span class="token operator">+</span> <span class="token string">" "</span> <span class="token operator">+</span> lastName<span class="token punctuation">;</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span>fullName<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="operadores-relacionais" tabindex="-1"><a class="header-anchor" href="#operadores-relacionais" aria-hidden="true">#</a> Operadores relacionais</h2>
<p>Os operadores relacionais utilízanse cando necesitamos tomar unha decisión entre dous valores a partir de certas variables. Para o que usamos <strong>== <em>(igual)</em></strong> ou <strong>!= <em>(non iguais)</em></strong></p>
<p>O seguinte exemplo devolve <strong><code v-pre>true</code> <em>(verdadeiro)</em></strong> porque o <strong>prezo</strong> e <strong>inputPrice</strong> non son iguais</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> price <span class="token operator">=</span> <span class="token number">20.5</span><span class="token punctuation">;</span>
<span class="token keyword">var</span> inputPrice <span class="token operator">=</span> <span class="token number">10.50</span><span class="token punctuation">;</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span>inputPrice <span class="token operator">=</span> price <span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>O seguinte exemplo devolve <strong><code v-pre>false</code> <em>(falso)</em></strong> porque o <strong>price</strong> e <strong>inputPrice</strong> non son iguais</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> price <span class="token operator">=</span> <span class="token number">20.5</span><span class="token punctuation">;</span>
<span class="token keyword">var</span> inputPrice <span class="token operator">=</span> <span class="token number">10.50</span><span class="token punctuation">;</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span>inputPrice <span class="token operator">==</span> price <span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="operadores-de-comparacion" tabindex="-1"><a class="header-anchor" href="#operadores-de-comparacion" aria-hidden="true">#</a> Operadores de comparación</h2>
<p>Os operadores de comparación úsanse cando necesitamos comparar valores de números ou valores de cadea, usamos<br>
*<strong>&lt;</strong> 	<em>(menor que)</em><br>
<strong>&lt;=</strong>  	<em>(menor que ou igual)</em></p>
<p><strong>&gt;</strong>   	<em>(maior que)</em><br>
<strong>&gt; =</strong> 	<em>(maior que ou igual)</em></p>
<p>O seguinte exemplo compara <strong>num1</strong> con <strong>num2</strong> e <strong>num3</strong> o valor de saída é verdadeiro ou falso dependendo da comparación solicitada.</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> num1 <span class="token operator">=</span> <span class="token number">20</span><span class="token punctuation">;</span>  
<span class="token keyword">var</span> num2 <span class="token operator">=</span> <span class="token number">12</span><span class="token punctuation">;</span>  
<span class="token keyword">var</span> num3 <span class="token operator">=</span> <span class="token number">20</span><span class="token punctuation">;</span>

document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span>num1 <span class="token operator">></span> num2<span class="token punctuation">)</span><span class="token punctuation">;</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span>num1 <span class="token operator">>=</span> num2<span class="token punctuation">)</span><span class="token punctuation">;</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span>num1 <span class="token operator">></span> num3<span class="token punctuation">)</span><span class="token punctuation">;</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span>num1 <span class="token operator">>=</span> num3<span class="token punctuation">)</span><span class="token punctuation">;</span>

document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span>num1 <span class="token operator">&lt;</span> num2<span class="token punctuation">)</span><span class="token punctuation">;</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span>num1 <span class="token operator">&lt;=</span> num2<span class="token punctuation">)</span><span class="token punctuation">;</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span>num1 <span class="token operator">&lt;</span> num3<span class="token punctuation">)</span><span class="token punctuation">;</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span>num1 <span class="token operator">&lt;=</span> num3<span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="operadores-loxicos" tabindex="-1"><a class="header-anchor" href="#operadores-loxicos" aria-hidden="true">#</a> Operadores lóxicos</h2>
<p>Os operadores lóxicos utilízanse cando necesitamos comparar valores entre 2 ou máis valores.<br>
<strong>&amp;&amp; 		   <em>(descrito como &quot;AND&quot;)</em><br>
|| 			<em>(descrito como &quot;OR&quot;)</em><br>
!     			<em>(descrito como &quot;NON&quot;)</em></strong></p>
<p>Exemplo de cando utilizar operadores lóxicos pódese facer como segue: Tes unha lista de produtos cos seus respectivos prezos:<br>
<strong>produto1 = &quot;Mazá&quot;, Prezo = 1,99</strong><br>
<strong>produto2 = &quot;Mango&quot;, Prezo = 1,29</strong><br>
<strong>produto3 = &quot;Uva&quot;, Prezo = 1,99</strong><br>
<strong>produto4 = &quot;Sandía&quot;, Prezo = 1,69</strong><br>
<strong>produto5 = &quot;Limón&quot;, Prezo = 1,39</strong></p>
<p>Queres atopar todos os produtos cun prezo de <strong>1,99</strong> e <strong>1,29</strong>, pero non incluir as mazas  o código pódese escribir como segue.</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> products <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
products<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">"Apple"</span><span class="token punctuation">,</span> <span class="token number">1.99</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
products<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">"Mango"</span><span class="token punctuation">,</span> <span class="token number">1.29</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
products<span class="token punctuation">[</span><span class="token number">2</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">"Grape"</span><span class="token punctuation">,</span> <span class="token number">1.99</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
products<span class="token punctuation">[</span><span class="token number">3</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">"Watermelon"</span><span class="token punctuation">,</span> <span class="token number">1.69</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
products<span class="token punctuation">[</span><span class="token number">4</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">"Lemon"</span><span class="token punctuation">,</span> <span class="token number">1.39</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span><span class="token string">"&lt;h1>Found products&lt;/h1>"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">var</span> prod <span class="token keyword">in</span> products<span class="token punctuation">)</span> <span class="token punctuation">{</span>

<span class="token keyword">var</span> productName <span class="token operator">=</span> products<span class="token punctuation">[</span>prod<span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
<span class="token keyword">var</span> productPrice <span class="token operator">=</span> products<span class="token punctuation">[</span>prod<span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
<span class="token keyword">if</span> <span class="token punctuation">(</span>productName <span class="token operator">!=</span> <span class="token string">"Apple"</span> <span class="token operator">&amp;&amp;</span> productPrice <span class="token operator">==</span> <span class="token number">1.99</span> <span class="token operator">||</span> productPrice <span class="token operator">==</span> <span class="token number">1.29</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span>productName <span class="token operator">+</span> <span class="token string">" $"</span> <span class="token operator">+</span> productPrice <span class="token operator">+</span> <span class="token string">"&lt;br>"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
<span class="token punctuation">}</span> 

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Inda que este era un exemplo para mostrar como usar os <strong>operadores lóxicos</strong>, vemos como se crea un código JavaScript avanzado que inclúe <strong>matriz, bucle, control de fluxo e operadores loxicos</strong>,. Terás que usar <strong>if, else</strong> cando, p.ex., fagas unha comparación.</p>
<h2 id="control-de-fluxo" tabindex="-1"><a class="header-anchor" href="#control-de-fluxo" aria-hidden="true">#</a> Control de fluxo</h2>
<p>As instrucións de control de fluxo baséanse en iteracións condicionais de <em>bucles</em> -<strong>loop</strong>- e saltos para fóra deses bucles. <s>no exemplo utilizamos operadores lóxicos, usamos control de fluxo, condicional e iteración en bucle.</s></p>
<h2 id="declaracions-condicionais" tabindex="-1"><a class="header-anchor" href="#declaracions-condicionais" aria-hidden="true">#</a> Declaracións condicionais</h2>
<p>A declaración condicional baséase en <strong>if, if/else, switch</strong> usamos esta declaración cando necesitamos cumprir unha condición entre os valores dun bloque de código.</p>
<h2 id="a-declaracion-if-if-else" tabindex="-1"><a class="header-anchor" href="#a-declaracion-if-if-else" aria-hidden="true">#</a> A declaración if, if/else</h2>
<p>A declaración <strong>if, if/else</strong> axúdanos a verificar se se cumpren algúns criterios, se os criterios se cumpren podemos realizar outras accións ou saír do código. A sintaxe da instrución <strong>if, if/else</strong> úsase como segue.</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">if</span> <span class="token punctuation">(</span>condition<span class="token punctuation">)</span> <span class="token punctuation">{</span>  
<span class="token comment">// bloque de código a executar se a condición é certa:  </span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">if</span> <span class="token punctuation">(</span>condition<span class="token punctuation">)</span> <span class="token punctuation">{</span>  
<span class="token comment">// bloque de código a executar se a condición é verdadeira:  </span>
<span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>  
<span class="token comment">// bloque de código a executar se a condición é falsa  </span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>O seguinte exemplo executa o bloque de código <strong>if</strong> e devolve a mensaxe <strong>O prezo do produto é alto</strong> .</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> price <span class="token operator">=</span> <span class="token number">99</span><span class="token punctuation">;</span>
<span class="token keyword">if</span> <span class="token punctuation">(</span>price <span class="token operator">></span> <span class="token number">70</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span><span class="token string">"The product price is high"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span><span class="token string">"The product price is lower"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span> 
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>O seguinte exemplo executa o bloque de código <strong>else</strong> e devolve a mensaxe <strong>O prezo do produto é inferior</strong> .</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> price <span class="token operator">=</span> <span class="token number">99</span><span class="token punctuation">;</span>
<span class="token keyword">if</span> <span class="token punctuation">(</span>price <span class="token operator">&lt;</span> <span class="token number">70</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span><span class="token string">"The product price is high."</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span><span class="token string">"The product price is lower."</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="a-declaracion-de-cambio-switch-statement" tabindex="-1"><a class="header-anchor" href="#a-declaracion-de-cambio-switch-statement" aria-hidden="true">#</a> A declaración de cambio - <em>switch statement</em></h2>
<p>A instrución switch permíte seleccionar un valor entre moitos resultados posibles do código que queremos analizar. A sintaxe sería algo así:</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">switch</span> <span class="token punctuation">(</span>expression<span class="token punctuation">)</span> <span class="token punctuation">{</span>

<span class="token keyword">case</span> <span class="token literal-property property">value1</span><span class="token operator">:</span>
value1_Return<span class="token punctuation">;</span>
<span class="token keyword">break</span><span class="token punctuation">;</span>
<span class="token keyword">case</span> <span class="token literal-property property">value2</span><span class="token operator">:</span>
value2_Return<span class="token punctuation">;</span>
<span class="token keyword">break</span><span class="token punctuation">;</span>
<span class="token keyword">case</span> <span class="token literal-property property">value3</span><span class="token operator">:</span>
value3_Return<span class="token punctuation">;</span>
<span class="token keyword">break</span><span class="token punctuation">;</span>
<span class="token keyword">default</span><span class="token operator">:</span>
default_value_Return<span class="token punctuation">;</span>
<span class="token keyword">break</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span> 
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Podes usar a instrución switch como o seguinte exemplo.</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> selection <span class="token operator">=</span> <span class="token number">1</span><span class="token punctuation">;</span>
<span class="token keyword">var</span> answer<span class="token punctuation">;</span>
<span class="token keyword">switch</span> <span class="token punctuation">(</span>selection<span class="token punctuation">)</span> <span class="token punctuation">{</span>

<span class="token keyword">case</span> <span class="token number">0</span><span class="token operator">:</span>
answer <span class="token operator">=</span> <span class="token string">'Red'</span><span class="token punctuation">;</span>
<span class="token keyword">break</span><span class="token punctuation">;</span>
<span class="token keyword">case</span> <span class="token number">1</span><span class="token operator">:</span>
answer <span class="token operator">=</span> <span class="token string">'Blue'</span><span class="token punctuation">;</span>
<span class="token keyword">break</span><span class="token punctuation">;</span>
<span class="token keyword">case</span> <span class="token number">2</span><span class="token operator">:</span>
answer <span class="token operator">=</span> <span class="token string">'Yellow'</span><span class="token punctuation">;</span>
<span class="token keyword">break</span><span class="token punctuation">;</span>
<span class="token keyword">case</span> <span class="token number">3</span><span class="token operator">:</span>
answer <span class="token operator">=</span> <span class="token string">'Green'</span><span class="token punctuation">;</span>
<span class="token keyword">break</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span>answer<span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Pódese cambiar o valor da variable de <strong>selección</strong> para ver un resultado diferente.</p>
<h2 id="loops" tabindex="-1"><a class="header-anchor" href="#loops" aria-hidden="true">#</a> Loops</h2>
<p>Os bucles úsanse para recuperar unha lista de elementos e saír cando se atopa un condicional</p>
<h2 id="a-declaracion-while-mentres" tabindex="-1"><a class="header-anchor" href="#a-declaracion-while-mentres" aria-hidden="true">#</a> A declaración <em>while</em> - mentres</h2>
<p>Se a avaliación cumpre a condición de expresión detense e sae do bucle. a sintaxe <strong>while</strong> é a seguinte</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">while</span> <span class="token punctuation">(</span>expression<span class="token punctuation">)</span> <span class="token punctuation">{</span>
<span class="token comment">//code to execute</span>
<span class="token punctuation">}</span> 
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>O seguinte exemplo mostra como usar a instrución <strong>while</strong> , se a variable <strong>i</strong> é inferior a <strong>10</strong> continúa en bucle, se <strong>i</strong> chega a 10 sairá.</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> text <span class="token operator">=</span> <span class="token string">""</span><span class="token punctuation">;</span>
<span class="token keyword">var</span> i <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span>
<span class="token keyword">while</span> <span class="token punctuation">(</span>i <span class="token operator">&lt;</span> <span class="token number">10</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>

text <span class="token operator">+=</span> <span class="token string">"&lt;br>The number is "</span> <span class="token operator">+</span> i<span class="token punctuation">;</span>
i<span class="token operator">++</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span>text<span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="a-declaracion-do-while" tabindex="-1"><a class="header-anchor" href="#a-declaracion-do-while" aria-hidden="true">#</a> A declaración do/while</h2>
<p>A instrución <strong>do/while</strong> é case a mesma que <strong>mentres</strong> o diferente é que o <strong>while se</strong> executa primeiro e despois realiza a condición, a sintaxe do/while é a seguinte.</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">do</span> <span class="token punctuation">{</span>
<span class="token comment">//code to execute</span>
<span class="token punctuation">}</span>
<span class="token keyword">while</span> <span class="token punctuation">(</span>expression<span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>O seguinte exemplo mostra como usar a instrución <strong>while</strong> , se a variable <strong>i</strong> é inferior a <strong>10</strong> continúa en bucle, se <strong>i</strong> chega a 10 sairá.</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> text <span class="token operator">=</span> <span class="token string">""</span><span class="token punctuation">;</span>
<span class="token keyword">var</span> i <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span>
<span class="token keyword">do</span> <span class="token punctuation">{</span>

text <span class="token operator">+=</span> <span class="token string">"&lt;br>The number is "</span> <span class="token operator">+</span> i<span class="token punctuation">;</span>
i<span class="token operator">++</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
<span class="token keyword">while</span> <span class="token punctuation">(</span>i <span class="token operator">&lt;</span> <span class="token number">10</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span>text<span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="a-declaracion-for-para" tabindex="-1"><a class="header-anchor" href="#a-declaracion-for-para" aria-hidden="true">#</a> A declaración <em>for</em> - para</h2>
<p>A instrución <strong>for</strong> funciona en base a pasos que se recorren nun reconto coñecido de elementos da lista ou desde o número inicial ata o número final, o <strong>for</strong> úsase máis cando precisa obter todos os elementos dunha lista de elementos dunha <strong>matriz</strong> , a sintaxe é a seguinte.</p>
<p><code v-pre>for (int_start; expresión; incremento){   //código a executar   };</code></p>
<p>O seguinte exemplo mostra como usar a declaración <strong>for</strong>.</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> fruits <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'Apple'</span><span class="token punctuation">,</span> <span class="token string">'Melon'</span><span class="token punctuation">,</span> <span class="token string">'Mango'</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
<span class="token keyword">var</span> text <span class="token operator">=</span> <span class="token string">""</span><span class="token punctuation">;</span>
<span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">var</span> i <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> i <span class="token operator">&lt;</span> fruits<span class="token punctuation">.</span>length<span class="token punctuation">;</span> i<span class="token operator">++</span><span class="token punctuation">)</span><span class="token punctuation">{</span>

text <span class="token operator">+=</span> fruits<span class="token punctuation">[</span>i<span class="token punctuation">]</span> <span class="token operator">+</span> <span class="token string">"&lt;br>"</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span>text<span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Normalmente podes escribir moitas liñas que queiras.</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> write1000lines <span class="token operator">=</span> <span class="token string">""</span><span class="token punctuation">;</span>
<span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">var</span> i <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> i <span class="token operator">&lt;=</span> <span class="token number">1000</span><span class="token punctuation">;</span> i<span class="token operator">++</span><span class="token punctuation">)</span><span class="token punctuation">{</span>

write1000lines <span class="token operator">+=</span> <span class="token string">"I don't have to forget my homework &lt;br>"</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span>write1000lines<span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="a-declaracion-for-in" tabindex="-1"><a class="header-anchor" href="#a-declaracion-for-in" aria-hidden="true">#</a> A declaración <code v-pre>for/in</code></h2>
<p>A instrución <strong><code v-pre>for/in</code></strong> é case a mesma que a instrución <strong>for</strong> , pero <strong>for/in</strong> non require un número de inicio, un número final, un incremento, senón que usa o <strong>in</strong> onde vai para contar o número de elementos que están na <strong>matriz,</strong> a sintaxe é como acompañamento.</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">for</span> <span class="token punctuation">(</span>variable <span class="token keyword">in</span> elements_array<span class="token punctuation">)</span> <span class="token punctuation">{</span>
<span class="token comment">//code to execute</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span> 
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>O seguinte exemplo mostra como usar a instrución <strong>for/in</strong></p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> fruits <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'Apple'</span><span class="token punctuation">,</span> <span class="token string">'Melon'</span><span class="token punctuation">,</span> <span class="token string">'Mango'</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
<span class="token keyword">var</span> text <span class="token operator">=</span> <span class="token string">""</span><span class="token punctuation">;</span>
<span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">var</span> i <span class="token keyword">in</span> fruits<span class="token punctuation">)</span> <span class="token punctuation">{</span>

text <span class="token operator">+=</span> fruits<span class="token punctuation">[</span>i<span class="token punctuation">]</span> <span class="token operator">+</span> <span class="token string">"&lt;br>"</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span>text<span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Podes usar o <strong>for/in</strong> para contar letras nunha cadea e obter cada unha á vez.</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> abc <span class="token operator">=</span> <span class="token string">"ABCDEFGHIJKLMNOPQRSTUVWXYZ"</span>
<span class="token keyword">var</span> text <span class="token operator">=</span> <span class="token string">""</span><span class="token punctuation">;</span>
<span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">var</span> i <span class="token keyword">in</span> abc<span class="token punctuation">)</span> <span class="token punctuation">{</span>

text <span class="token operator">+=</span> abc<span class="token punctuation">[</span>i<span class="token punctuation">]</span> <span class="token operator">+</span> <span class="token string">"&lt;br>"</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span>text<span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="obxectos" tabindex="-1"><a class="header-anchor" href="#obxectos" aria-hidden="true">#</a> Obxectos</h2>
<p>Os obxectos son unha colección de nomes coñecidos como <strong>Propiedades.</strong> Calquera propiedade pode ter o seu propio tipo de datos, vostede declara o obxecto do mesmo xeito que se declara variables. Os obxectos adoitan facer referencia a un <strong>espazo de nomes</strong> , accede ás propiedades mediante a súa declaración, poden aniñarse noutros obxectos. a sintaxe é a seguinte.</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> namespace <span class="token operator">=</span> <span class="token punctuation">{</span>
<span class="token string-property property">"oject1"</span><span class="token operator">:</span>value<span class="token punctuation">,</span>
<span class="token string-property property">"oject2"</span><span class="token operator">:</span>value<span class="token punctuation">,</span>
<span class="token string-property property">"oject3"</span><span class="token operator">:</span>value<span class="token punctuation">,</span>
<span class="token punctuation">}</span> 
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>O seguinte exemplo crea un obxecto con propiedades e recuperamos o valor das propiedades.</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token comment">//Object</span>
<span class="token keyword">var</span> Product <span class="token operator">=</span> <span class="token punctuation">{</span>

<span class="token string-property property">"Name"</span><span class="token operator">:</span><span class="token string">"Apple"</span><span class="token punctuation">,</span>
<span class="token string-property property">"Price"</span><span class="token operator">:</span><span class="token number">2.99</span><span class="token punctuation">,</span>
<span class="token punctuation">}</span>
<span class="token comment">//Get product information</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span>Product<span class="token punctuation">.</span>Name <span class="token operator">+</span><span class="token string">" is priced at "</span><span class="token operator">+</span> Product<span class="token punctuation">.</span>Price<span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="obxectos-con-obxectos-aninados" tabindex="-1"><a class="header-anchor" href="#obxectos-con-obxectos-aninados" aria-hidden="true">#</a> Obxectos con obxectos aniñados</h2>
<p>O seguinte exemplo crea un obxecto e ten un <strong>obxecto aniñado</strong> con propiedades, e recuperamos o valor das propiedades.</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token comment">//Object</span>
<span class="token keyword">var</span> Product <span class="token operator">=</span> <span class="token punctuation">{</span>

<span class="token string-property property">"Name"</span><span class="token operator">:</span><span class="token string">"Apple"</span><span class="token punctuation">,</span>
<span class="token string-property property">"Price"</span><span class="token operator">:</span><span class="token number">2.99</span><span class="token punctuation">,</span>
<span class="token comment">//Nested object</span>
<span class="token literal-property property">CannedFruit</span><span class="token operator">:</span><span class="token punctuation">{</span>
<span class="token string-property property">"UPC"</span><span class="token operator">:</span><span class="token number">123456789101</span><span class="token punctuation">,</span>
<span class="token string-property property">"Description"</span><span class="token operator">:</span><span class="token string">"Pineapple"</span><span class="token punctuation">,</span>
<span class="token string-property property">"Price"</span><span class="token operator">:</span><span class="token number">5.99</span>
<span class="token punctuation">}</span>
<span class="token punctuation">}</span>
<span class="token comment">//Get the first product information</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span>Product<span class="token punctuation">.</span>Name <span class="token operator">+</span><span class="token string">" is priced at "</span><span class="token operator">+</span> Product<span class="token punctuation">.</span>Price<span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">//Get the Canned fruit information</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span><span class="token string">"&lt;br>"</span> <span class="token operator">+</span> Product<span class="token punctuation">.</span>CannedFruit<span class="token punctuation">.</span>Description <span class="token operator">+</span> <span class="token string">" with UPC "</span><span class="token operator">+</span> Product<span class="token punctuation">.</span>CannedFruit<span class="token punctuation">.</span><span class="token constant">UPC</span> <span class="token operator">+</span><span class="token string">" is priced at "</span><span class="token operator">+</span> Product<span class="token punctuation">.</span>CannedFruit<span class="token punctuation">.</span>Price<span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="obxectos-con-arrays" tabindex="-1"><a class="header-anchor" href="#obxectos-con-arrays" aria-hidden="true">#</a> Obxectos con <code v-pre>arrays</code></h2>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token comment">//Object</span>
<span class="token keyword">var</span> GroceryStore <span class="token operator">=</span> <span class="token punctuation">{</span>

<span class="token literal-property property">Departments</span> <span class="token operator">:</span> <span class="token punctuation">{</span>
<span class="token literal-property property">Deli</span><span class="token operator">:</span><span class="token punctuation">[</span><span class="token string">"Yougurt"</span><span class="token punctuation">,</span><span class="token string">"Juice"</span><span class="token punctuation">,</span><span class="token string">"Milk"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
<span class="token literal-property property">Produce</span><span class="token operator">:</span><span class="token punctuation">[</span><span class="token string">"Vegetables"</span><span class="token punctuation">,</span><span class="token string">"Fruits"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
<span class="token punctuation">}</span>
<span class="token punctuation">}</span>
<span class="token keyword">for</span><span class="token punctuation">(</span><span class="token keyword">var</span> i <span class="token keyword">in</span> GroceryStore<span class="token punctuation">.</span>Departments<span class="token punctuation">.</span>Deli<span class="token punctuation">)</span><span class="token punctuation">{</span>

document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span>GroceryStore<span class="token punctuation">.</span>Departments<span class="token punctuation">.</span>Deli<span class="token punctuation">[</span>i<span class="token punctuation">]</span> <span class="token operator">+</span><span class="token string">"&lt;br>&lt;br>"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
<span class="token keyword">for</span><span class="token punctuation">(</span><span class="token keyword">var</span> i <span class="token keyword">in</span> GroceryStore<span class="token punctuation">.</span>Departments<span class="token punctuation">.</span>Produce<span class="token punctuation">)</span><span class="token punctuation">{</span>

document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span>GroceryStore<span class="token punctuation">.</span>Departments<span class="token punctuation">.</span>Produce<span class="token punctuation">[</span>i<span class="token punctuation">]</span> <span class="token operator">+</span> <span class="token string">"&lt;br>&lt;br>"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span> 
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="obxectos-con-metodos" tabindex="-1"><a class="header-anchor" href="#obxectos-con-metodos" aria-hidden="true">#</a> Obxectos con métodos</h2>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token comment">//Object</span>
<span class="token keyword">var</span> Customer <span class="token operator">=</span> <span class="token punctuation">{</span>

<span class="token literal-property property">Name</span><span class="token operator">:</span><span class="token string">"Melvin"</span><span class="token punctuation">,</span>
<span class="token literal-property property">LastName</span><span class="token operator">:</span><span class="token string">"Hernandez"</span><span class="token punctuation">,</span>
<span class="token function-variable function">GetFullName</span><span class="token operator">:</span><span class="token keyword">function</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
<span class="token keyword">return</span> <span class="token keyword">this</span><span class="token punctuation">.</span>Name <span class="token operator">+</span> <span class="token string">" "</span> <span class="token operator">+</span> <span class="token keyword">this</span><span class="token punctuation">.</span>LastName<span class="token punctuation">;</span>
<span class="token punctuation">}</span>
<span class="token punctuation">}</span>
<span class="token comment">//Get full name</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span>Customer<span class="token punctuation">.</span><span class="token function">GetFullName</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="propiedades-dos-obxectos-dinamicos" tabindex="-1"><a class="header-anchor" href="#propiedades-dos-obxectos-dinamicos" aria-hidden="true">#</a> Propiedades dos obxectos dinámicos</h2>
<p>Podes engadir propiedades ao obxecto despois de que o obxecto fose declarado, o seguinte exemplo crea un obxecto chamado <strong>Dispositivo</strong> e engadimos 3 propiedades <strong>Nome, Descrición, Tipo</strong></p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token comment">//Object</span>
<span class="token keyword">var</span> Device <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token punctuation">}</span>

<span class="token comment">//Add properties with values</span>
Device<span class="token punctuation">.</span>Name <span class="token operator">=</span><span class="token string">"Surface Book 3"</span><span class="token punctuation">;</span>
Device<span class="token punctuation">.</span>Description <span class="token operator">=</span> <span class="token string">"Silver with 500GB Hard drive"</span><span class="token punctuation">;</span>
Device<span class="token punctuation">.</span>Type <span class="token operator">=</span> <span class="token string">"Laptop"</span><span class="token punctuation">;</span>

<span class="token comment">//Get property value</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span><span class="token string">"Name: "</span> <span class="token operator">+</span> Device<span class="token punctuation">.</span>Name<span class="token punctuation">)</span><span class="token punctuation">;</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span><span class="token string">"&lt;br>&lt;br>"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span><span class="token string">"Description: "</span> <span class="token operator">+</span> Device<span class="token punctuation">.</span>Description<span class="token punctuation">)</span><span class="token punctuation">;</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span><span class="token string">"&lt;br>&lt;br>"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span><span class="token string">"Type: "</span> <span class="token operator">+</span> Device<span class="token punctuation">.</span>Type<span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="construtor-de-obxectos" tabindex="-1"><a class="header-anchor" href="#construtor-de-obxectos" aria-hidden="true">#</a> Construtor de obxectos</h2>
<p>O construtor de obxectos créase coa palabra clave <strong>new</strong> , o seguinte exemplo crea un <strong>obxecto Coche</strong> e engadimos propiedades <strong>Marca, Cor, Portas</strong> e un método <strong>GetDescription()</strong> .</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token comment">//Object</span>
<span class="token keyword">var</span> Car <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Object</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">//Add properties</span>
Car<span class="token punctuation">.</span>Brand <span class="token operator">=</span> <span class="token string">"Tesla"</span><span class="token punctuation">;</span>
Car<span class="token punctuation">.</span>Color <span class="token operator">=</span> <span class="token string">"Black"</span><span class="token punctuation">;</span>
Car<span class="token punctuation">.</span>Doors <span class="token operator">=</span> <span class="token number">4</span><span class="token punctuation">;</span>
<span class="token comment">//Add property as method</span>
Car<span class="token punctuation">.</span><span class="token function-variable function">GetDescription</span> <span class="token operator">=</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>

<span class="token keyword">return</span> <span class="token string">"The "</span> <span class="token operator">+</span> Car<span class="token punctuation">.</span>Brand <span class="token operator">+</span> <span class="token string">" car is color "</span> <span class="token operator">+</span> Car<span class="token punctuation">.</span>Color <span class="token operator">+</span> <span class="token string">" and has "</span><span class="token operator">+</span> Car<span class="token punctuation">.</span>Doors <span class="token operator">+</span> <span class="token string">" doors."</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
<span class="token comment">//Get the car description by calling the "GetDescription()" method.</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span>Car<span class="token punctuation">.</span><span class="token function">GetDescription</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token comment">//Object</span>
<span class="token keyword">var</span> <span class="token function-variable function">Car</span> <span class="token operator">=</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter">brand<span class="token punctuation">,</span> color<span class="token punctuation">,</span> doors</span><span class="token punctuation">)</span><span class="token punctuation">{</span>

<span class="token keyword">this</span><span class="token punctuation">.</span>Brand <span class="token operator">=</span> brand<span class="token punctuation">;</span>
<span class="token keyword">this</span><span class="token punctuation">.</span>Color <span class="token operator">=</span> color<span class="token punctuation">;</span>
<span class="token keyword">this</span><span class="token punctuation">.</span>Doors <span class="token operator">=</span> doors<span class="token punctuation">;</span>
<span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function-variable function">GetDescription</span> <span class="token operator">=</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
<span class="token keyword">return</span> <span class="token string">"The "</span> <span class="token operator">+</span> <span class="token keyword">this</span><span class="token punctuation">.</span>Brand <span class="token operator">+</span> <span class="token string">" car is color "</span> <span class="token operator">+</span> <span class="token keyword">this</span><span class="token punctuation">.</span>Color <span class="token operator">+</span> <span class="token string">" and has "</span><span class="token operator">+</span> <span class="token keyword">this</span><span class="token punctuation">.</span>Doors <span class="token operator">+</span> <span class="token string">" doors."</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>

<span class="token keyword">var</span> teslaCar <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Car</span><span class="token punctuation">(</span><span class="token string">"Tesla"</span><span class="token punctuation">,</span><span class="token string">"Red"</span><span class="token punctuation">,</span><span class="token string">"2"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">var</span> bmwCar <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Car</span><span class="token punctuation">(</span><span class="token string">"BMW"</span><span class="token punctuation">,</span><span class="token string">"Blue"</span><span class="token punctuation">,</span><span class="token string">"4"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span>teslaCar<span class="token punctuation">.</span><span class="token function">GetDescription</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span><span class="token string">"&lt;br>&lt;br>"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span>bmwCar<span class="token punctuation">.</span><span class="token function">GetDescription</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="arrays" tabindex="-1"><a class="header-anchor" href="#arrays" aria-hidden="true">#</a> Arrays</h2>
<p>As matrices son listas de elementos indexados por posición numérica. As matrices pódense declarar como segue.</p>
<p><code v-pre>var froitas = [&quot;Mazá&quot;, &quot;melón&quot;, &quot;mango&quot;];</code></p>
<p><code v-pre>var froitas = new Array (&quot;Mazá&quot;, &quot;Melon&quot;, &quot;Mango&quot;);</code></p>
<p>Podes engadir máis elementos a un <strong>Array</strong> usando o método <strong>push()</strong> como segue</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> fruits <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">"Apple"</span><span class="token punctuation">,</span> <span class="token string">"Melon"</span><span class="token punctuation">,</span> <span class="token string">"Mango"</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
<span class="token comment">//Adds new item to Array</span>
fruits<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span><span class="token string">"Grape"</span><span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Podes eliminar elementos de <strong>Array</strong> usando o método <strong>splice() do</strong> seguinte xeito</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> fruits <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">"Apple"</span><span class="token punctuation">,</span> <span class="token string">"Melon"</span><span class="token punctuation">,</span> <span class="token string">"Mango"</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
<span class="token comment">// splice syntax splice(remove_item_position, item_count_to_remove)</span>
<span class="token comment">//Removes "Apple" item from Array</span>
fruits<span class="token punctuation">.</span><span class="token function">splice</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span><span class="token number">1</span><span class="token punctuation">)</span> 
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Podes obter máis información sobre Arrays e os seus membros completos en <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array" target="_blank" rel="noopener noreferrer">MDN web docs<ExternalLinkIcon/></a></p>
<h2 id="metodos-funcions" tabindex="-1"><a class="header-anchor" href="#metodos-funcions" aria-hidden="true">#</a> Métodos/funcións</h2>
<p>As funcións ás veces chámanse métodos, as funcións son útiles e calquera linguaxe de programación a inclúe. As funcións son bloques de código que se executan cando se chama. podes chamar á función que crees desde calquera parte do teu código. A sintaxe é a seguinte.</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>función <span class="token function">functionName</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>  
<span class="token comment">//Bloque de código  </span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>función <span class="token function">functionName</span><span class="token punctuation">(</span><span class="token parameter">parametro1<span class="token punctuation">,</span> parametro2<span class="token punctuation">,</span><span class="token punctuation">.</span><span class="token punctuation">.</span></span><span class="token punctuation">)</span><span class="token punctuation">{</span>  
<span class="token comment">//Bloque de código  </span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Os seguintes exemplos mostran como usar as funcións</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">function</span> <span class="token function">programmingLanguages</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>

document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span><span class="token string">"JavaScript, C#, VB.NET"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
<span class="token comment">//Call the function</span>
<span class="token function">programmingLanguages</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> <span class="token function-variable function">prog</span> <span class="token operator">=</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter">languages</span><span class="token punctuation">)</span><span class="token punctuation">{</span>

<span class="token keyword">return</span> languages<span class="token punctuation">;</span>
<span class="token punctuation">}</span>
<span class="token comment">//Call the function;</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span><span class="token function">prog</span> <span class="token punctuation">(</span><span class="token string">"JavaScript, C#, VB.NET"</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>as funcións tamén devolven valor</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">function</span> <span class="token function">programmingLanguages</span><span class="token punctuation">(</span><span class="token parameter">languages</span><span class="token punctuation">)</span><span class="token punctuation">{</span>

<span class="token keyword">return</span> languages<span class="token punctuation">;</span>
<span class="token punctuation">}</span>
<span class="token comment">//Call the function</span>
document<span class="token punctuation">.</span><span class="token function">write</span><span class="token punctuation">(</span><span class="token function">programmingLanguages</span><span class="token punctuation">(</span><span class="token string">"JavaScript, C#, VB.NET"</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span> 
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="cont" tabindex="-1"><a class="header-anchor" href="#cont" aria-hidden="true">#</a> cont. (?)</h2>
<p></p>
<h3 id="javascript-frameworks" tabindex="-1"><a class="header-anchor" href="#javascript-frameworks" aria-hidden="true">#</a> JavaScript Frameworks</h3>
<p>Un <em><strong>framework</strong></em> ou marco de traballo é basicamente unha biblioteca de código destinada a unha determinada linguaxe. Xeralmente, o marco de traballo abstrae tarefas comúns e fai que os deseñadores e desenvolvedores escriban o seu código específico de xeito máis sinxelo e rápido. Os frameworks non fan nada por si sós, só proporcionan unha plataforma máis sinxela para que as persoas poidan construír.</p>
<p>Marcos JavaScript comúns:</p>
<ul>
<li><a href="http://jquery.com/" target="_blank" rel="noopener noreferrer">JQuery<ExternalLinkIcon/></a></li>
<li><a href="http://www.prototypejs.org/" target="_blank" rel="noopener noreferrer">Prototype<ExternalLinkIcon/></a></li>
<li><a href="http://mootools.net/" target="_blank" rel="noopener noreferrer">MooTools<ExternalLinkIcon/></a></li>
<li><a href="http://script.aculo.us/" target="_blank" rel="noopener noreferrer">script.aculo.us<ExternalLinkIcon/></a></li>
</ul>
<p>Destes frameworks, jQuery é actualmente o máis popular.</p>
<p>NOV 2021</p>
</div></template>


