export const data = JSON.parse("{\"key\":\"v-d5d86098\",\"path\":\"/uf1842/02-Arquitectura%20dos%20navegadores%20web.html\",\"title\":\"Arquitectura dos navegadores web\",\"lang\":\"en-US\",\"frontmatter\":{\"marp\":true,\"description\":\"Arquitectura dos navegadores web bg image-20230122020030065 Como funcionan os navegadores web? img Interface de usuario É a interface de usuario do navegador. Inclúe a barra de enderezos, o botón Atrás, as opcións de marcadores, o botón Actualizar, etc.\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://ambosass.com/megaboot/uf1842/02-Arquitectura%20dos%20navegadores%20web.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"DAW\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Arquitectura dos navegadores web\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Arquitectura dos navegadores web bg image-20230122020030065 Como funcionan os navegadores web? img Interface de usuario É a interface de usuario do navegador. Inclúe a barra de enderezos, o botón Atrás, as opcións de marcadores, o botón Actualizar, etc.\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://ambosass.com/megaboot/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Arquitectura dos navegadores web\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Arquitectura dos navegadores web\\\",\\\"image\\\":[\\\"https://ambosass.com/megaboot/\\\"],\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":3,\"title\":\"Como funcionan os navegadores web?\",\"slug\":\"como-funcionan-os-navegadores-web\",\"link\":\"#como-funcionan-os-navegadores-web\",\"children\":[]}],\"readingTime\":{\"minutes\":2.43,\"words\":730},\"filePathRelative\":\"uf1842/02-Arquitectura dos navegadores web.md\",\"excerpt\":\"<h1> Arquitectura dos navegadores web</h1>\\n<figure><figcaption>bg image-20230122020030065</figcaption></figure>\\n<hr>\\n<h3> Como funcionan os navegadores web?</h3>\\n<hr>\\n<figure><figcaption>img</figcaption></figure>\\n<hr>\\n<h4> Interface de usuario</h4>\\n<p>É a interface de usuario do navegador. Inclúe a barra de enderezos, o botón Atrás, as opcións de marcadores, o botón Actualizar, etc.</p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
