<template><div><h3 id="que-e-un-sitio-web-dinamico" tabindex="-1"><a class="header-anchor" href="#que-e-un-sitio-web-dinamico" aria-hidden="true">#</a> Que é un sitio web dinámico?</h3>
<p>A diferenza dun sitio web estático onde o contido está predefinido mediante ficheiros html, nun sitio web dinámico o contido está construído a partir de diferentes fontes.</p>
<figure><img src="https://aprendelibvrefiles.blob.core.windows.net/aprendelibvre-container/course/creacion_de_sitios_web/image/webb2_xl.png" alt="sitios web dinámicos" tabindex="0" loading="lazy"><figcaption>sitios web dinámicos</figcaption></figure>
<p>Nos seus inicios, a web orientouse para compartir artigos académicos, pero cando se puxo a disposición do público en xeral xurdiron outros usos. Por exemplo, se un portal de noticias fose un sitio web estático, alguén tería que estar actualizando o ficheiro html da portada cada vez que se publicase unha noticia; engadindo etiquetas, escribindo os textos e actualizando imaxes ou ligazóns e subindo o novo ficheiro ao servidor web.</p>
<p>O anterior non soa moi eficiente, poderíamos melloralo? Claro! Se nos fixamos ben, hai certas cousas que se repiten, estruturas comúns como títulos, descricións ou encabezados, estas estruturas mantense mentres cambian os seus contidos. E se puideses manter dalgunha maneira as estruturas e só actualizar os contidos?</p>
<p>Isto é precisamente o que fai un sitio web dinámico: enriba dunha estrutura de etiquetas html, engade ou modifica contido e entrega un novo documento ao navegador, que non necesariamente representa un ficheiro nun directorio do servidor web.</p>
<p>Como podes ver, un sitio web dinámico non significa que teña animacións bonitas, significa que os seus contidos foron xerados de forma dinámica e non a partir dun ficheiro html. Seguindo o exemplo dunha web de noticias, aínda que a url da portada sexa a mesma, os contidos de cada día serán diferentes.</p>
<p>O desenvolvemento de sitios web dinámicos responde a varias necesidades: podemos presentar un sitio web en diferentes idiomas, cambiar as opcións en función do usuario que acceda a el e responder aos cambios de información con rapidez. Tamén permite que diferentes usuarios creen contido web simultaneamente usando só o navegador.</p>
<p>A ampla dispoñibilidade de navegadores e Internet tamén fixo posible o desenvolvemento de aplicacións web. Estes non son tecnicamente moi diferentes do que presentamos como un sitio web dinámico, só que se centran en ofrecer solucións a necesidades máis empresariais onde se deben proporcionar controis de usuarios, permisos, actualizacións constantes, rexistro de usos, xeración de informes e gráficos. certificados... en definitiva, moitas funcionalidades que serían máis difíciles de acadar nunha aplicación de escritorio tradicional.</p>
<p><em><strong>E como é un sitio web dinámico?</strong></em> Son exemplos todos os portais de noticias, sitios de contido como nós, redes sociais, blogs, revistas en liña, a maioría dos sitios web hoxe en día son dinámicos, se non, non sería factible mantelos.</p>
<p>Constrúese un sitio web dinámico a partir das tecnoloxías básicas da web: html, css e JavaScript engadindo outras tecnoloxías adicionais que se denominan <em>tecnoloxías de fondo.</em></p>
<h4 id="paxina-17-tecnoloxias-e-conceptos-no-backend-web" tabindex="-1"><a class="header-anchor" href="#paxina-17-tecnoloxias-e-conceptos-no-backend-web" aria-hidden="true">#</a> Páxina 17: Tecnoloxías e conceptos no backend web</h4>
<h3 id="tecnoloxias-e-conceptos-no-backend-web" tabindex="-1"><a class="header-anchor" href="#tecnoloxias-e-conceptos-no-backend-web" aria-hidden="true">#</a> Tecnoloxías e conceptos no backend web</h3>
<p>O backend abrangue todo o que se executa no servidor, onde se xestionan as tecnoloxías e os conceptos que permiten a creación de sitios web dinámicos.</p>
<figure><img src="https://aprendelibvrefiles.blob.core.windows.net/aprendelibvre-container/course/creacion_de_sitios_web/image/webb1_xl.png" alt="backend web" tabindex="0" loading="lazy"><figcaption>backend web</figcaption></figure>
<p>A principios dos 90 creouse o primeiro mecanismo para que un servidor web puidese responder con contido dinámico: CGI. A especificación de <em>Common Gateway Interface</em> permite que un servidor web estático delegue noutro programa a xeración do contido dinámico e, a continuación, reciba a resposta e redirixaa ao navegador. Nos anos seguintes empregáronse outros enfoques, algúns servidores web engadiron módulos para poder executar código sen o uso de CGI, outras tecnoloxías permitían mesturar instrucións de programación con etiquetas html e creáronse servidores especificamente deseñados para xerar contido dinámico.</p>
<p>Sen entrar nos detalles de cada idioma ou plataforma, podemos falar en termos xerais de como funciona un sitio web dinámico, lembra que para cada solicitude do navegador hai unha resposta do servidor. Un servidor web dinámico *<strong>expón*</strong> a solicitude http e a resposta http o que significa, en palabras máis sinxelas, que temos acceso desde o noso código a esas dúas estruturas en forma de estrutura de datos ou como obxecto.</p>
<h3 id="solicitude-http" tabindex="-1"><a class="header-anchor" href="#solicitude-http" aria-hidden="true">#</a> Solicitude HTTP</h3>
<p>A solicitude http contén varios valores que son útiles para saber que contido debemos xerar ou que acción debemos executar, un dos máis útiles son os <em><strong>parámetros</strong></em> , estes son unha serie de nomes e valores en forma de texto. Dependendo do método de solicitude, estes valores poden ser visibles ao final do URL ou non visibles no corpo da solicitude. En calquera caso podemos acceder a eses nomes e valores desde o noso código.</p>
<h3 id="resposta-http" tabindex="-1"><a class="header-anchor" href="#resposta-http" aria-hidden="true">#</a> Resposta HTTP</h3>
<p>O corpo da resposta http varía dependendo do contido, pode ser texto simple que representa follas de estilo, etiquetas html ou código javascript, pero tamén pode ser contido binario como imaxes ou documentos. O navegador poderá indicar o tipo de contido lendo o valor da cabeceira *<strong>Content-Type*</strong> , polo que necesitamos establecer o valor correcto do noso código no backend.</p>
<h3 id="sesion-http" tabindex="-1"><a class="header-anchor" href="#sesion-http" aria-hidden="true">#</a> Sesión HTTP</h3>
<p>A comunicación nun entorno web é unha comunicación <em>sen estado</em> , isto quere dicir que o servidor web non sabe se houbo ou haberá comunicación co mesmo cliente, simplemente responde a cada solicitude coma se dunha solicitude nova e illada se tratase. No contexto dunha web dinámica, é necesario manter un estado, é dicir, poder saber quen fai a solicitude e que solicitudes se fixeron con anterioridade.</p>
<p>Para conseguilo utilízase o concepto de <em><strong>sesión</strong></em> . En termos informáticos, unha sesión é un período de tempo no que se producen unha serie de mensaxes entre dúas máquinas; nun sitio web dinámico, unha sesión corresponde a un grupo de solicitudes e respostas HTTP dun usuario. O concepto de sesión é importante porque permite ao servidor distinguir ao usuario que realiza as solicitudes para xerar o contido axeitado, por exemplo, por motivos de seguridade non podemos mostrar opcións administrativas a todos os usuarios, só a aqueles que proporcionaron un nome de usuario e un contrasinal válidos.</p>
<p>A sesión http adoita implementarse xerando un código identificador único por usuario que se almacena no navegador a través dunha *<strong>cookie*</strong> , o navegador sempre envía ese identificador en todas as solicitudes ao mesmo sitio mentres que o servidor web almacena o identificador e asocia algúns datos importantes a recoñecer ao usuario.</p>
<h3 id="codigo-modelos-e-datos-no-backend-web" tabindex="-1"><a class="header-anchor" href="#codigo-modelos-e-datos-no-backend-web" aria-hidden="true">#</a> Código, modelos e datos no backend web</h3>
<p>No frontend non temos moitas opcións en canto a linguaxes de programación, a día de hoxe só temos JavaScript (aínda que indirectamente podemos utilizar outras linguaxes que sexan capaces de producir código js). Pola contra, no backend temos múltiples opcións, podemos escribir a lóxica da nosa web dinámica nunha variedade de idiomas e plataformas que veremos máis adiante. Desde o código backend temos acceso a dúas cousas importantes no desenvolvemento de sitios web dinámicos: os modelos e os datos.</p>
<p>O <em><strong>sistema de modelos</strong></em> de backend é a tecnoloxía que nos permite substituír só os datos dinámicos nun documento html. Depende un pouco do idioma ou plataforma que utilicemos, pero en xeral consiste nun ficheiro de texto con determinadas especificacións ao que se aplican algúns datos, xerando así un novo documento. Estes datos que mencionamos proceden xeralmente dunha ou varias *<strong>bases*</strong> de datos . As bases de datos, que veremos máis adiante, xogan un papel moi importante no desenvolvemento de sitios web dinámicos, xa que conteñen a información que necesitamos para xestionar e xerar o noso contido dinámico.</p>
<h4 id="paxina-18-linguaxes-de-programacion-web" tabindex="-1"><a class="header-anchor" href="#paxina-18-linguaxes-de-programacion-web" aria-hidden="true">#</a> Páxina 18: Linguaxes de programación web</h4>
<h3 id="linguaxes-de-programacion-web" tabindex="-1"><a class="header-anchor" href="#linguaxes-de-programacion-web" aria-hidden="true">#</a> linguaxes de programación web</h3>
<p>Para o desenvolvemento no <em>backend</em> web podemos escoller entre moitas linguaxes de programación, vexamos algunhas delas.</p>
<p>Presentámosvos unha visión xeral das posibilidades de desenvolvemento en diferentes idiomas, desde aquí podedes afondar visitando os manuais técnicos e titoriais recompilados ao final desta lección. Todos estes idiomas/plataformas permítennos acceder a parámetros de solicitude, podemos escribir ficheiros binarios ou texto html na resposta, podemos xestionar sesións e conectarnos a varias bases de datos. Por outra banda, cada plataforma ten diferentes frameworks que ofrecen formas de modelar o noso desenvolvemento, utilidades comúns e sistemas de modelos.</p>
<h3 id="php" tabindex="-1"><a class="header-anchor" href="#php" aria-hidden="true">#</a> PHP</h3>
<p>PHP é unha das linguaxes máis recoñecidas no desenvolvemento web, foi creada en 1994 por Rasmus Lerdorf para a súa páxina persoal, máis tarde foi lanzado como código aberto en 1995 e a partir de aí tivo unha longa evolución ata o que é hoxe en día. . PHP está orientado principalmente ao desenvolvemento web.</p>
<figure><img src="https://aprendelibvrefiles.blob.core.windows.net/aprendelibvre-container/course/creacion_de_sitios_web/image/php-logo_xl.png" alt="Logotipo PHP" tabindex="0" loading="lazy"><figcaption>Logotipo PHP</figcaption></figure>
<p>PHP é unha linguaxe multiparadigma, é dicir, pode programar de xeito procedemental (funcións e variables) ou orientada a obxectos (obxectos, atributos e métodos). PHP debe estar integrado cun servidor web como Apache ou NginX, entre outros. Entre algúns dos seus frameworks temos: Laravel, Symfony, Zend 2 e CakePHP.</p>
<p><a href="https://edu.gcfglobal.org/es/creacion-de-sitios-web/paginas-para-aprender-a-programar/1/#" target="_blank" rel="noopener noreferrer">Explora<ExternalLinkIcon/></a></p>
<h3 id="xava" tabindex="-1"><a class="header-anchor" href="#xava" aria-hidden="true">#</a> Xava</h3>
<p>Java comezou a ser concibido en 1991 por James Gosling e finalmente foi lanzado ao público en 1995. É unha linguaxe orientada a obxectos, portátil a diferentes arquitecturas, que lle permite funcionar en teléfonos móbiles e ordenadores persoais ata servidores e superordenadores. Para o desenvolvemento web Java ofrece dúas tecnoloxías: Servlets e páxinas JSP (Páxinas do servidor Java). Os servlets son obxectos que teñen métodos que responden ás solicitudes web, o desenvolvedor crea subclases destes obxectos para implementar alí a lóxica do seu sitio web dinámico. Pola súa banda, JSP permite mesturar código Java con etiquetas html.</p>
<figure><img src="https://aprendelibvrefiles.blob.core.windows.net/aprendelibvre-container/course/creacion_de_sitios_web/image/java-logo_xl.png" alt="logotipo de java" tabindex="0" loading="lazy"><figcaption>logotipo de java</figcaption></figure>
<p>Para executar páxinas Servlets ou JSP, necesitas un servidor web especializado en tecnoloxía Java como WildFly, Tomcat ou Glassfish. Entre os seus frameworks máis coñecidos están: Spring, Wicket, Struts, Play! e JSF.</p>
<p><a href="https://edu.gcfglobal.org/es/creacion-de-sitios-web/paginas-para-aprender-a-programar/1/#" target="_blank" rel="noopener noreferrer">Explora<ExternalLinkIcon/></a></p>
<h3 id="asp-net" tabindex="-1"><a class="header-anchor" href="#asp-net" aria-hidden="true">#</a> <a href="http://ASP.NET" target="_blank" rel="noopener noreferrer">ASP.NET<ExternalLinkIcon/></a></h3>
<p>ASP é a tecnoloxía de Microsoft para desenvolver sitios web dinámicos, a súa versión máis recente, <a href="http://ASP.NET" target="_blank" rel="noopener noreferrer">ASP.NET<ExternalLinkIcon/></a>, foi lanzada ao público en 2002. Utiliza o entorno de execución .NET polo que é posible programar en linguaxes soportadas por el como C# ou Visual Basic. É posible mesturar código de programación con etiquetas html ou separar código e etiquetas en diferentes ficheiros.</p>
<figure><img src="https://aprendelibvrefiles.blob.core.windows.net/aprendelibvre-container/course/creacion_de_sitios_web/image/asp-logo_xl.png" alt="Logotipo ASP" tabindex="0" loading="lazy"><figcaption>Logotipo ASP</figcaption></figure>
<p>Requírese un servidor Microsoft IIS para executar páxinas <a href="http://ASP.NET" target="_blank" rel="noopener noreferrer">ASP.NET<ExternalLinkIcon/></a>. Entre os seus frameworks atopamos: <a href="http://ASP.NET" target="_blank" rel="noopener noreferrer">ASP.NET<ExternalLinkIcon/></a> MVC, <a href="http://ASP.NET" target="_blank" rel="noopener noreferrer">ASP.NET<ExternalLinkIcon/></a> WebAPI e NancyFX.</p>
<p><a href="https://edu.gcfglobal.org/es/creacion-de-sitios-web/paginas-para-aprender-a-programar/1/#" target="_blank" rel="noopener noreferrer">Explora<ExternalLinkIcon/></a></p>
<p><em>O uso de frameworks e sistemas de modelos evita mesturar o código de programación con etiquetas html, o que mellora o mantemento dos grandes proxectos.</em></p>
<h3 id="alternativas" tabindex="-1"><a class="header-anchor" href="#alternativas" aria-hidden="true">#</a> Alternativas</h3>
<p>É posible facer desenvolvemento web en case calquera idioma, podes atopar opcións en Ruby, Perl, Python, C++, JavaScript, Haxe... en definitiva, seguro que atoparás como facer o desenvolvemento web no idioma que desexes.</p>
<p>Podemos destacar <a href="https://nodejs.org/es/" target="_blank" rel="noopener noreferrer">Node.js<ExternalLinkIcon/></a> para o desenvolvemento de backend de JavaScript, <a href="http://cppcms.com/" target="_blank" rel="noopener noreferrer">cppCMS<ExternalLinkIcon/></a> para o desenvolvemento de C++, <a href="http://rubyonrails.org/" target="_blank" rel="noopener noreferrer">Ruby On Rails<ExternalLinkIcon/></a> para o desenvolvemento de Ruby e <a href="https://www.djangoproject.com/" target="_blank" rel="noopener noreferrer">Django<ExternalLinkIcon/></a> para o desenvolvemento de Python.</p>
<p>Para escoller entre unha ou outra tecnoloxía debes ter en conta varios factores: o tamaño do proxecto, os idiomas nos que tes experiencia, o rendemento, os frameworks dispoñibles, a calidade da documentación e a estabilidade, entre outros.</p>
<h4 id="paxina-19-sistemas-de-bases-de-datos" tabindex="-1"><a class="header-anchor" href="#paxina-19-sistemas-de-bases-de-datos" aria-hidden="true">#</a> Páxina 19: Sistemas de bases de datos</h4>
<h3 id="sistemas-de-bases-de-datos" tabindex="-1"><a class="header-anchor" href="#sistemas-de-bases-de-datos" aria-hidden="true">#</a> Sistemas de bases de datos</h3>
<p>As bases de datos son esenciais para sitios web dinámicos, conteñen toda a información administrativa e o contido do sitio.</p>
<p>A base de datos é un compoñente fundamental dun sitio web dinámico, contén toda a información necesaria para que o sitio funcione. Neste contexto, a base de datos debe conter información administrativa como usuarios, permisos e contrasinais, información textual, que é o contido como tal do sitio e outra información que forma parte do núcleo do negocio.</p>
<h3 id="base-de-datos-relacional" tabindex="-1"><a class="header-anchor" href="#base-de-datos-relacional" aria-hidden="true">#</a> Base de datos relacional</h3>
<p>Existen varios modelos de bases de datos, mencionaremos un deles que se utiliza maioritariamente no desenvolvemento de sitios web, o modelo *<strong>relacional*</strong> . Isto ten fundamentos teóricos na álxebra relacional que foi proposto por Edgar &quot;Ted&quot; Codd na década de 1970, como unha especie de teoría de conxuntos aplicada aos datos.</p>
<figure><img src="https://aprendelibvrefiles.blob.core.windows.net/aprendelibvre-container/course/creacion_de_sitios_web/image/diagrama_er_xl.png" alt="Diagrama de relacións entidades" tabindex="0" loading="lazy"><figcaption>Diagrama de relacións entidades</figcaption></figure>
<p><em>Diagrama de relacións entidades</em></p>
<h3 id="entidades" tabindex="-1"><a class="header-anchor" href="#entidades" aria-hidden="true">#</a> entidades</h3>
<p>Un dos conceptos importantes no modelo relacional é o concepto de *<strong>entidade*</strong> . Unha entidade representa algo que é significativo e contén *<strong>atributos*</strong> relevantes para o sistema. Por exemplo, se o noso sitio web é un blog, unha posible entidade sería &quot;artigo&quot; e algúns posibles atributos serían a súa &quot;data de publicación&quot; e o seu &quot;título&quot;. Se a nosa web é unha tenda en liña, unha posible entidade sería &quot;produto&quot; con posibles atributos &quot;nome&quot; e &quot;prezo&quot;.</p>
<h3 id="chaves" tabindex="-1"><a class="header-anchor" href="#chaves" aria-hidden="true">#</a> Chaves</h3>
<p>É importante que cada entidade teña un identificador único coñecido como a súa *<strong>clave primaria*</strong> , esta pode ser artificial, é dicir, xerada polo sistema, ou natural, é dicir, que normalmente forma parte da entidade. As claves facilitan as buscas na base de datos e permiten establecer relacións entre entidades.</p>
<h3 id="relacions" tabindex="-1"><a class="header-anchor" href="#relacions" aria-hidden="true">#</a> Relacións</h3>
<p>Unha *<strong>relación*</strong> é unha asociación entre dúas entidades, podemos identificar estas relacións cando usamos verbos como ten, contén, forma parte, está inscrito, etc. Establecemos relacións ao deseñar a base de datos e baseámonos na experiencia no noso negocio. Por exemplo, se o noso sitio é un blog, sabemos que un autor escribe varios artigos, polo que atopamos unha relación entre a entidade &quot;artigo&quot; e a entidade &quot;autor&quot;. Se o noso sitio é unha tenda en liña, sabemos que unha compra ten un ou varios produtos, polo que atopamos unha relación entre a entidade &quot;compra&quot; e a entidade &quot;produto&quot;.</p>
<p>Para implementar as relacións, utilízase o concepto de *<strong>chave estranxeira*</strong> . A clave externa é unha clave que é primaria para unha entidade e cópiase como un atributo doutra entidade, establecendo así a relación. Seguindo o exemplo do blog, para relacionar un autor cos seus artigos engadiremos a &quot;artigo&quot; un novo atributo &quot;escrito por&quot;, que conterá o valor da clave primaria da entidade &quot;autor&quot;.</p>
<h3 id="procuras" tabindex="-1"><a class="header-anchor" href="#procuras" aria-hidden="true">#</a> procuras</h3>
<p>Unha das vantaxes de ter un modelo matemático para bases de datos relacionais é que facilitou a creación dunha linguaxe de consulta estruturada coñecida como *<strong>SQL*</strong> ( <em>Structured Query Language)</em> . A través deste podemos executar actualizacións e consultas sobre os datos. Por exemplo, actualizar atributos dalgunha entidade, buscar entidades que cumpran determinadas condicións ou atopar grupos de entidades asociadas, entre outras moitas opcións.</p>
<h3 id="implementacion-informatica" tabindex="-1"><a class="header-anchor" href="#implementacion-informatica" aria-hidden="true">#</a> implementación informática</h3>
<p>Os sistemas de xestión de bases de datos relacionais, <em>RDBMS</em> polas súas siglas en inglés, implementan o modelo relacional a través do concepto de *<strong>táboa*</strong> . Unha táboa contén *<strong>filas*</strong> e *<strong>columnas*</strong> . Cada entidade rexístrase nunha fila da táboa e cada un dos seus atributos rexístrase en cada columna da fila. Finalmente, as táboas materialízanse como ficheiros en disco, para que a súa información quede gravada de forma permanente e duradeira.</p>
<figure><img src="https://aprendelibvrefiles.blob.core.windows.net/aprendelibvre-container/course/creacion_de_sitios_web/image/tabla-autor_xl.png" alt="táboa de autores" tabindex="0" loading="lazy"><figcaption>táboa de autores</figcaption></figure>
<p><em>Exemplo de táboa &quot;AUTHOR&quot;.</em></p>
<p>Ademais, estes sistemas ofrecen funcionalidades como xestión de usuarios e permisos, acceso simultáneo a través da rede, creación de copias de seguridade e análise de rendemento, entre outras. No mercado atopamos moitos destes sistemas, podemos citar a <a href="http://www.mysql.com/" target="_blank" rel="noopener noreferrer">MySQL<ExternalLinkIcon/></a> , <a href="https://www.oracle.com/database/index.html" target="_blank" rel="noopener noreferrer">Oracle<ExternalLinkIcon/></a> e <a href="https://www.postgresql.org/" target="_blank" rel="noopener noreferrer">PostgreSQL<ExternalLinkIcon/></a> entre os máis coñecidos.</p>
<figure><img src="https://aprendelibvrefiles.blob.core.windows.net/aprendelibvre-container/course/creacion_de_sitios_web/image/tabla-articulo_xl.png" alt="táboa de artigos" tabindex="0" loading="lazy"><figcaption>táboa de artigos</figcaption></figure>
<p><em>Exemplo de táboa &quot;ARTIGO&quot;</em></p>
<h3 id="alternativas-1" tabindex="-1"><a class="header-anchor" href="#alternativas-1" aria-hidden="true">#</a> Alternativas</h3>
<p>O campo das bases de datos é amplo tanto a nivel académico como empresarial. Existen diferentes criterios para clasificalos, multitude de implementacións e un número infinito de controladores para conectar con eles desde múltiples linguaxes de programación. Segundo a complexidade do sitio, podemos ter unha ou varias bases de datos, incluso é posible mesturar diferentes tipos de bases de datos nun mesmo proxecto segundo as necesidades.</p>
<p>Entre as alternativas ao modelo relacional, podemos atopar outras formas de almacenamento como repositorios de clave-valor, bases de datos orientadas a obxectos, táboas distribuídas, bases de datos orientadas a documentos ou almacenamento baseado en rexistros. Cada un deles ten semellanzas e diferenzas co modelo relacional. Podemos mencionar <a href="https://www.mongodb.com/" target="_blank" rel="noopener noreferrer">MongoDB<ExternalLinkIcon/></a> , <a href="http://www.ozone-db.org/" target="_blank" rel="noopener noreferrer">Ozone DB<ExternalLinkIcon/></a> , <a href="http://www.oracle.com/technetwork/database/database-technologies/berkeleydb/overview/index.html" target="_blank" rel="noopener noreferrer">Oracle Berkeley Database<ExternalLinkIcon/></a> , <a href="https://cassandra.apache.org/" target="_blank" rel="noopener noreferrer">Apache Cassandra<ExternalLinkIcon/></a> e <a href="http://www.hypertable.org/" target="_blank" rel="noopener noreferrer">Hypertable<ExternalLinkIcon/></a> entre outros.</p>
<h4 id="paxina-20-consellos-para-o-desenvolvemento-web" tabindex="-1"><a class="header-anchor" href="#paxina-20-consellos-para-o-desenvolvemento-web" aria-hidden="true">#</a> Páxina 20: Consellos para o desenvolvemento web</h4>
<h3 id="consellos-para-o-desenvolvemento-web" tabindex="-1"><a class="header-anchor" href="#consellos-para-o-desenvolvemento-web" aria-hidden="true">#</a> Consellos para o desenvolvemento web</h3>
<p>Como mostramos en páxinas anteriores, o desenvolvemento dun sitio web dinámico implica moitas tecnoloxías que podemos clasificar como tecnoloxías de <em>frontend</em> (ou do lado do cliente) e tecnoloxías de <em>backend</em> (ou do lado do servidor). Aquí tes algúns consellos que debes ter en conta ao facer o desenvolvemento web.</p>
<figure><img src="https://aprendelibvrefiles.blob.core.windows.net/aprendelibvre-container/course/creacion_de_sitios_web/image/webb3_xl.png" alt="Equipo de traballo" tabindex="0" loading="lazy"><figcaption>Equipo de traballo</figcaption></figure>
<h4 id="fai-un-bo-equipo" tabindex="-1"><a class="header-anchor" href="#fai-un-bo-equipo" aria-hidden="true">#</a> Fai un bo equipo.</h4>
<p>O desenvolvemento de sitios web implica diversas tecnoloxías, polo que necesitamos un equipo de traballo con coñecementos e habilidades diversas.</p>
<p>Algúns membros do equipo centraranse no <em>frontend</em> : facer que o sitio sexa visualmente agradable, que teña un bo aspecto en diferentes dispositivos e que a experiencia do usuario sexa a mellor posible. Outros centraranse no <em>backend</em> : que o sitio sexa rápido, que sexa escalable, seguro e ofreza a funcionalidade esperada.</p>
<h4 id="use-un-sistema-de-control-de-versions" tabindex="-1"><a class="header-anchor" href="#use-un-sistema-de-control-de-versions" aria-hidden="true">#</a> Use un sistema de control de versións.</h4>
<p>Un sitio web consiste nunha colección de ficheiros, algúns serán código fonte, outros texto HTML, outros ficheiros de estilo, algún código JavaScript, etc. Para xestionar o proxecto é necesario un sistema de control de versións como <a href="https://git-scm.com/" target="_blank" rel="noopener noreferrer">Git<ExternalLinkIcon/></a> ou <a href="https://subversion.apache.org/" target="_blank" rel="noopener noreferrer">Subversion<ExternalLinkIcon/></a> , sistemas que permiten o acceso e control de versións do grupo de ficheiros que forman parte do proxecto.</p>
<h4 id="configura-o-teu-ambiente-de-desenvolvemento" tabindex="-1"><a class="header-anchor" href="#configura-o-teu-ambiente-de-desenvolvemento" aria-hidden="true">#</a> Configura o teu ambiente de desenvolvemento.</h4>
<p>Segundo a tecnoloxía escollida, o desenvolvemento implica a instalación e configuración de software: un servidor web, servidores de bases de datos, algún entorno de <em>execución</em> ou de execución, ferramentas de compilación e un entorno de desenvolvemento integrado ou IDE.</p>
<p>Un IDE é unha aplicación que nos permite xestionar e editar ficheiros de proxecto, previsualizar o contido, iniciar e deter servidores, acceder a bases de datos, ver ficheiros de rexistro e outras utilidades necesarias para o desenvolvemento de software.</p>
<h4 id="alternativas-2" tabindex="-1"><a class="header-anchor" href="#alternativas-2" aria-hidden="true">#</a> Alternativas</h4>
<p>Non sempre é necesario que abordes o desenvolvemento web desde cero, tes alternativas como instalar e configurar un sistema de xestión de contidos ou CMS. Estes sistemas poden ser xestionados por usuarios con coñecementos básicos de informática.</p>
<p>Con eles podes construír un sitio web rapidamente, grazas a que estes sistemas incorporan interfaces visuais para editar e configurar o sitio, paquetes temáticos personalizables e <em>complementos</em> ou extensións que se adaptan ás túas necesidades, por exemplo, galerías de imaxes ou formularios de enquisas. Tamén contan con funcionalidades de xestión de usuarios e unha base de datos preconfigurada.</p>
<p>Exemplos destes sistemas son <a href="https://es.wordpress.org/" target="_blank" rel="noopener noreferrer">WordPress <ExternalLinkIcon/></a>, <a href="https://www.joomla.org/" target="_blank" rel="noopener noreferrer">Joomla <ExternalLinkIcon/></a>, <a href="https://www.drupal.org/" target="_blank" rel="noopener noreferrer">Drupal <ExternalLinkIcon/></a>ou <a href="https://moodle.org/?lang=es" target="_blank" rel="noopener noreferrer">Moodle <ExternalLinkIcon/></a>, este último orientado a cursos en liña.</p>
<p>Este é só o comezo. Podes afondar en cada tecnoloxía pola túa conta, por exemplo, <a href="https://edu.gcfglobal.org/es/recomendaciones-tecnologicas/sitios-web-para-aprender-a-programar/print/" target="_blank" rel="noopener noreferrer">aprender a codificar sitios web<ExternalLinkIcon/></a> ou consultando referencias técnicas como <a href="http://www.w3schools.com/" target="_blank" rel="noopener noreferrer">w3schools<ExternalLinkIcon/></a> e <a href="https://developer.mozilla.org/es/" target="_blank" rel="noopener noreferrer">Mozilla Developer Network<ExternalLinkIcon/></a> . Se che interesa a tecnoloxía podes dirixir os teus <a href="https://edu.gcfglobal.org/es/vida_diaria/curso/acceso_a_la_educacion_superior/perfil_del_estudiante/1.do" target="_blank" rel="noopener noreferrer">estudos superiores<ExternalLinkIcon/></a> á área de informática. Ou se o teu é o <a href="https://edu.gcfglobal.org/es/vida_diaria/curso/emprendimiento/inicio_de_un_negocio/1.do" target="_blank" rel="noopener noreferrer">emprendemento<ExternalLinkIcon/></a> , podes pensar en crear o teu propio negocio en liña, para o que será útil unha estratexia web.</p>
<p>Agora que sabes máis sobre o desenvolvemento web, os pasos a seguir son escoller as tecnoloxías coas que vas traballar, instalar o software necesario, revisar a documentación técnica e construír o teu proxecto web. Adiante!</p>
<h4 id="paxina-21-paxinas-para-aprender-a-programar" tabindex="-1"><a class="header-anchor" href="#paxina-21-paxinas-para-aprender-a-programar" aria-hidden="true">#</a> Páxina 21: Páxinas para aprender a programar</h4>
<h3 id="paxinas-para-aprender-a-programar" tabindex="-1"><a class="header-anchor" href="#paxinas-para-aprender-a-programar" aria-hidden="true">#</a> Páxinas para aprender a programar</h3>
<p>Programar é escribir instrucións definidas nunha linguaxe de programación determinada para facer que un ordenador faga algo que se necesita ou quere. Esas instrucións chámanse <em>código</em> e están escritas en moitos ficheiros de texto. Cando o ordenador executa esas instrucións é cando podemos <em>ver</em> o que fan.</p>
<p>Se vas á universidade e estás a explorar opcións de carreira, se xa tes experiencia e queres aprender unha nova linguaxe de programación ou só tes curiosidade sobre a programación, estes sitios poden axudar.</p>
<h4 id="mooc-s" tabindex="-1"><a class="header-anchor" href="#mooc-s" aria-hidden="true">#</a> MOOC'S</h4>
<p>Os MOOC son portais web para cursos gratuítos, normalmente apoiados por organizacións internacionais e institucións universitarias. Podes atopar cursos en moitas áreas, pero neste caso interésanos a área de tecnoloxía.</p>
<h4 id="coursera" tabindex="-1"><a class="header-anchor" href="#coursera" aria-hidden="true">#</a> Coursera</h4>
<p>Podes atopar cursos na categoría <a href="https://www.coursera.org/courses?orderby=upcoming&amp;cats=cs-programming" target="_blank" rel="noopener noreferrer">Informática: Enxeñaría do Software<ExternalLinkIcon/></a> .</p>
<h4 id="academia-khan" tabindex="-1"><a class="header-anchor" href="#academia-khan" aria-hidden="true">#</a> Academia Khan</h4>
<p>Podes atopar cursos na categoría <a href="https://www.khanacademy.org/computing/cs" target="_blank" rel="noopener noreferrer">Programación informática<ExternalLinkIcon/></a> .</p>
<h4 id="miriade-x" tabindex="-1"><a class="header-anchor" href="#miriade-x" aria-hidden="true">#</a> Miríade X</h4>
<p>Podes atopar cursos na categoría de <a href="https://www.miriadax.net/cursos?p_p_id=122_INSTANCE_Qo8k&amp;p_p_lifecycle=0&amp;p_p_state=normal&amp;p_p_mode=view&amp;p_p_col_id=column-1&amp;p_p_col_pos=1&amp;p_p_col_count=2&amp;p_r_p_564233524_categoryId=11154" target="_blank" rel="noopener noreferrer">Ciencias Tecnolóxicas<ExternalLinkIcon/></a> .</p>
<h4 id="udemy" tabindex="-1"><a class="header-anchor" href="#udemy" aria-hidden="true">#</a> udemy</h4>
<p>Podes atopar cursos na categoría de <a href="https://www.udemy.com/courses/Development/?view=grid" target="_blank" rel="noopener noreferrer">desenvolvemento<ExternalLinkIcon/></a> .</p>
<p>A maioría dos cursos de programación en liña están en inglés, polo que é importante que coñezas este idioma.</p>
<h4 id="outros-sitios-de-programacion" tabindex="-1"><a class="header-anchor" href="#outros-sitios-de-programacion" aria-hidden="true">#</a> Outros sitios de programación</h4>
<p>Trátase de portais web que contan con cursos específicos da área de programación, teñen unha forma de practicar o que estás aprendendo dunha vez no ordenador.</p>
<h4 id="codecademy" tabindex="-1"><a class="header-anchor" href="#codecademy" aria-hidden="true">#</a> codecademy</h4>
<p>Podes atopar <a href="http://www.codecademy.com/learn" target="_blank" rel="noopener noreferrer">cursos<ExternalLinkIcon/></a> en varias linguaxes de programación segundo os teus intereses.</p>
<h4 id="programador" tabindex="-1"><a class="header-anchor" href="#programador" aria-hidden="true">#</a> programador</h4>
<p>Podes atopar cursos na sección <a href="http://www.programmr.com/practice/" target="_blank" rel="noopener noreferrer">Cursos gratuítos<ExternalLinkIcon/></a> .</p>
<h4 id="codigo" tabindex="-1"><a class="header-anchor" href="#codigo" aria-hidden="true">#</a> código</h4>
<p>Podes atopar cursos na sección <a href="http://code.org/learn" target="_blank" rel="noopener noreferrer">Aprender<ExternalLinkIcon/></a></p>
<h4 id="w3escolas" tabindex="-1"><a class="header-anchor" href="#w3escolas" aria-hidden="true">#</a> W3Escolas</h4>
<p>Podes atopar <a href="http://www.w3schools.com/" target="_blank" rel="noopener noreferrer">titoriais<ExternalLinkIcon/></a> sobre as linguaxes máis utilizadas para o desenvolvemento web.</p>
<p>Algúns dos cursos son gratuítos, outros teñen un custo. Algúns dan certificación, outros non. Revisa as condicións de cada sitio en detalle.</p>
<p>Dentro da programación son moitos os ámbitos nos que se pode traballar: aplicacións móbiles, aplicacións de escritorio, aplicacións web e videoxogos, entre outras.</p>
<p>Explora os cursos que ofrecen estes sitios, revisa o seu contido, estuda os exemplos, experimenta e elixe. Se queres dedicarte á programación, unha vez que atopes a zona na que te sintas máis cómodo, poderás desenvolverte profesionalmente gozando co que fas.</p>
<h4 id="paxina-22-proba-de-creacion-de-sitios-web" tabindex="-1"><a class="header-anchor" href="#paxina-22-proba-de-creacion-de-sitios-web" aria-hidden="true">#</a> Páxina 22: Proba de creación de sitios web</h4>
</div></template>


