<template><div><h6 id="obxectivos" tabindex="-1"><a class="header-anchor" href="#obxectivos" aria-hidden="true">#</a> Obxectivos</h6>
<ul>
<li><em>Visión xeral das ferramentas web modernas</em></li>
<li><em>Tipos de ferramentas dispoñibles e onde atopalas</em></li>
<li><em>Ciclo de vida do desenvolvemento de aplicacións web</em></li>
<li><em>Como atopar axuda coas ferramentas individuais.</em></li>
</ul>
<h1 id="ferramentas-do-lado-do-cliente" tabindex="-1"><a class="header-anchor" href="#ferramentas-do-lado-do-cliente" aria-hidden="true">#</a> Ferramentas do lado do cliente</h1>
<p>O software de escritura para a web fíxose cada vez máis sofisticado. Pero aínda é totalmente razoable escribir HTML, CSS e JavaScript &quot;a man&quot;,  hoxe en día existen unha gran cantidade de ferramentas que os desenvolvedores poden usar para acelerar o proceso de creación dun sitio web ou aplicación.</p>
<p>Hai algunhas ferramentas ben asentadas que co tempo se converteron en &quot;denominadores&quot; comúns entre os desenvolvedores. Ao tempo, cada día se están escribindo e lanzando novas ferramentas para resolver vellos e novos problemas específicos.</p>
<p>É doado sentirse abraiado pola gran cantidade de ferramentas que se poden incluír nun único proxecto.</p>
<p>De cando en vez, incluso os desenvolvedores web máis experimentados quedan atrapados nun problema coas ferramentas de desenvolvemento; é posible perder horas intentando que unha estrutura de ferramentas funcione antes de tocar unha soa liña de código de aplicación.</p>
<p>Aquí non atoparas respostas a todas as preguntas sobre ferramentas web, pero intentaremos proporcionarche un punto de partida útil para comprender os fundamentos, a partir dos cales poder <strong>construír o teu proceso de aprendizaxe</strong>. Como ocorre con calquera tema complexo, é bo comezar pouco a pouco e ir avanzando gradualmente cara a usos máis avanzados.</p>
<h2 id="o-ecosistema-moderno-de-ferramentas" tabindex="-1"><a class="header-anchor" href="#o-ecosistema-moderno-de-ferramentas" aria-hidden="true">#</a> O ecosistema moderno de ferramentas</h2>
<p>O ecosistema moderno de ferramentas para desenvolvedores actual é enorme, polo que é útil ter unha idea ampla dos principais problemas que están a resolver as ferramentas. Se vas ao teu motor de busca favorito e buscas &quot;ferramentas para desenvolvedores front-end&quot; atoparás un gran espectro de resultados que van desde editores de texto, navegadores, ata o tipo de bolígrafos que podes usar para tomar notas.</p>
<p>A elección final dun ou outro editor de código é algo persoal, pero máis alo do editor imos ver unha cantas ferramentas para desenvolvedores que nos axuden a producir código web de forma máis eficiente.</p>
<p>Desde unha visión aberta, podemos agrupar as ferramentas do lado do cliente en tres grandes categorías segundo o problema que tratan de resolver:</p>
<ul>
<li><strong>Rede de seguridade</strong> (<strong><em>Safety net</em></strong>) — Ferramentas útiles durante o desenvolvemento do teu código.</li>
<li><strong>Transformación</strong> (<strong><em>Transformation</em></strong>) — Ferramentas que transforman o código dalgún xeito, por exemplo, convertendo unha linguaxe intermedia en JavaScript que un navegador poida entender.</li>
<li><strong>Post-desenvolvemento</strong> (<strong><em>Post-development</em></strong>) — Ferramentas que son útiles despois de escribir o código, como ferramentas de proba e implementación.</li>
</ul>
<p>Vexamos cada grupo con máis detalle.</p>
<h3 id="rede-de-seguridade" tabindex="-1"><a class="header-anchor" href="#rede-de-seguridade" aria-hidden="true">#</a> Rede de seguridade</h3>
<p>Estas son ferramentas que melloran un pouco o código que escribes.</p>
<p>Inclúen calquera cousa que facilite o proceso de desenvolvemento con respecto á xeración de código estable e fiable. As ferramentas de rede de seguridade tamén deberían axudarche a previr erros ou a corrixilos automaticamente sen ter que construír o teu código desde cero cada vez.</p>
<p>Algúns tipos de ferramentas de rede de seguridade máis comúns que son utilizados polos desenvolvedores son:</p>
<h4 id="linters" tabindex="-1"><a class="header-anchor" href="#linters" aria-hidden="true">#</a> <em>Linters</em></h4>
<p><strong>Os linters</strong> son ferramentas que verifican o teu código e infórmanche sobre os erros presentes, que tipos de erro son e en que liñas de código están presentes. Moitas veces, os linters pódense configurar non só para informar dos erros, senón tamén para detectar calquera infracción nunha guía de estilo especifica - <em>corporativa</em>-.</p>
<p><a href="https://eslint.org/" target="_blank" rel="noopener noreferrer">eslint<ExternalLinkIcon/></a> é o linter JavaScript estándar do sector: unha ferramenta altamente configurable para detectar posibles erros de sintaxe e fomentar as &quot;mellores prácticas&quot; na edición de código. Algunhas empresas e proxectos o empregan e asemade <a href="https://www.npmjs.com/search?q=keywords:eslintconfig" target="_blank" rel="noopener noreferrer">comparten as súas configuracións<ExternalLinkIcon/></a>.</p>
<p>Tamén podes atopar ferramentas de linting para outros idiomas, como <a href="http://csslint.net/" target="_blank" rel="noopener noreferrer">csslint<ExternalLinkIcon/></a>.</p>
<p>Outra ferramenta deste tipo que tamén vale a pena ollear é <a href="https://webhint.io/" target="_blank" rel="noopener noreferrer">webhint<ExternalLinkIcon/></a>, un linter configurable e de código aberto para a web que recolle as mellores prácticas, incluíndo enfoques de accesibilidade, rendemento e compatibilidade entre navegadores mediante <a href="https://github.com/mdn/browser-compat-data" target="_blank" rel="noopener noreferrer">datos de compatibilidade do navegador de MDN<ExternalLinkIcon/></a>, seguridade, probas de PWA e moito máis. Está dispoñible como unha <a href="https://webhint.io/docs/user-guide/" target="_blank" rel="noopener noreferrer">ferramenta de liña de comandos Node.js<ExternalLinkIcon/></a> e tamén coma <a href="https://marketplace.visualstudio.com/items?itemName=webhint.vscode-webhint" target="_blank" rel="noopener noreferrer">extensión de VSCode<ExternalLinkIcon/></a>.</p>
<h4 id="control-do-codigo-source-code-control" tabindex="-1"><a class="header-anchor" href="#control-do-codigo-source-code-control" aria-hidden="true">#</a> Control do código - <em>Source code control</em></h4>
<p>Tamén coñecido como <strong>sistema de control de versións</strong> (<em>VCS</em>/SCV), o <strong>control de código</strong> é esencial para facer copias de seguridade do traballo e traballar en equipo. Un VCS típico implica ter unha versión local do código na que se fan os cambios. Unha vez rematadas as tarefas se &quot;empuxan&quot; - <strong><em>push</em></strong>- os cambios a unha versión &quot;mestra&quot; - <strong><em>master</em></strong> ou <strong><em>main</em></strong> - do noso código nun repositorio remoto almacenado nun servidor. Normalmente hai unha forma de controlar e coordinar que cambios se fan na copia &quot;mestra&quot; do código, e cando.  Así un equipo de desenvolvedores pode colaborar e compartir un repositorio sen acabar sobreescribindo o traballo duns e doutros.</p>
<p><a href="https://git-scm.com/" target="_blank" rel="noopener noreferrer">Git<ExternalLinkIcon/></a> é o sistema de control de código fonte que usa agora moita xente. Accédese principalmente a través da liña de comandos, pero tamén se pode acceder a través de <a href="https://desktop.github.com/" target="_blank" rel="noopener noreferrer">interfaces de usuario amigables<ExternalLinkIcon/></a>.</p>
<p>Se tes o teu código nun <strong>repositorio git</strong>, podes envialo á túa propia instancia de servidor ou usar un sitio web de control de fontes aloxado como <a href="https://github.com/" target="_blank" rel="noopener noreferrer">GitHub<ExternalLinkIcon/></a>, <a href="https://about.gitlab.com/" target="_blank" rel="noopener noreferrer">GitLab<ExternalLinkIcon/></a>, ou <a href="https://bitbucket.org/product/features" target="_blank" rel="noopener noreferrer">BitBucket<ExternalLinkIcon/></a>.</p>
<p>Como supós, usaremos GitHub neste curso. E podes atopar máis información sobre este coñecido SCV en <a href="https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/GitHub" target="_blank" rel="noopener noreferrer">Git e GitHub<ExternalLinkIcon/></a> .</p>
<h4 id="formatadores-de-codigo-code-formatters" tabindex="-1"><a class="header-anchor" href="#formatadores-de-codigo-code-formatters" aria-hidden="true">#</a> Formatadores de código - <em>Code formatters</em></h4>
<p>Os formatadores de código, as veces tamén coñecidos como <em>embelecedores</em> de código, están dalgún xeito relacionados cos linters, a non ser porque, en lugar de sinalar erros no código, simplemente adoitan asegurarse de que o código estea formateado correctamente, segundo as túas regras de estilo. Se poden tamén configurar para que corrixen automaticamente os erros que atopan.</p>
<p><a href="https://prettier.io/" target="_blank" rel="noopener noreferrer">Prettier<ExternalLinkIcon/></a> é un exemplo de formateador de código moi recoñecido polos desenvolvedores web.</p>
<p>Se buscas formatadores de código para outras linguaxes podes <a href="https://github.com/rishirdua/awesome-code-formatters" target="_blank" rel="noopener noreferrer">ver aquí<ExternalLinkIcon/></a></p>
<h4 id="xestores-de-paquetes-e-empaquetadores-bundlers-packagers" tabindex="-1"><a class="header-anchor" href="#xestores-de-paquetes-e-empaquetadores-bundlers-packagers" aria-hidden="true">#</a> Xestores de paquetes e empaquetadores - <em>Bundlers/packagers</em></h4>
<p>Estas son ferramentas que preparan o teu código para a produción, por exemplo, &quot;sacudindo as árbores&quot; para asegurarte de que só as partes que realmente estás a usar das túas bibliotecas de códigos se trasladan ao teu código de produción final; ou &quot;minimificando&quot; o teu código para eliminar todos os espazos en branco no código de produción; un xeito de facelo o máis pequeno posible antes de cargalo nun servidor.</p>
<p><a href="https://parceljs.org/" target="_blank" rel="noopener noreferrer">Parcel<ExternalLinkIcon/></a> é unha ferramenta especialmente intelixente que encaixa nesta categoría: pode facer as tarefas anteriores, e tamén axuda a empaquetar recursos HTML, CSS e arquivos de imaxe en paquetes axeitados para a publicación, asemade de poder engadir automaticamente as dependencias do proxecto.</p>
<p><a href="https://webpack.js.org/" target="_blank" rel="noopener noreferrer">Webpack<ExternalLinkIcon/></a> é outra ferrameta de enpaquetado moi popular con capacidades similares.</p>
<h3 id="transformacion-transformation" tabindex="-1"><a class="header-anchor" href="#transformacion-transformation" aria-hidden="true">#</a> Transformación - <em>Transformation</em></h3>
<p>Estes procedementos permiten codificar en &quot;código futuro&quot; (como as funcións CSS ou JavaScript máis recentes ou outras tecnoloxías que poden non ser aínda compatibles de forma nativa con algúns navegadores); ou que escribas o teu código utilizando algunha outra linguaxe coma <a href="https://www.typescriptlang.org/" target="_blank" rel="noopener noreferrer">TypeScript<ExternalLinkIcon/></a>. As ferramentas de transformación se ocuparan de xerar o código compatible co navegador e para poidas empregalas para produción.</p>
<p>En xeral, o desenvolvemento web considérase dominio de tres linguaxes: <a href="https://developer.mozilla.org/en-US/docs/Learn/HTML" target="_blank" rel="noopener noreferrer">HTML<ExternalLinkIcon/></a> , <a href="https://developer.mozilla.org/en-US/docs/Learn/CSS" target="_blank" rel="noopener noreferrer">CSS<ExternalLinkIcon/></a> e <a href="https://developer.mozilla.org/en-US/docs/Learn/JavaScript" target="_blank" rel="noopener noreferrer">JavaScript<ExternalLinkIcon/></a> , e hai ferramentas de transformación para todas elas.</p>
<p>A transformación ofrece dous <strong>beneficios principais</strong> (entre outros):</p>
<ol>
<li>A capacidade de <strong>escribir código usando as funcións máis recentes da linguaxe</strong> e transformalo en código que funciona nos dispositivos cotiáns. Por exemplo, pode querer escribir JavaScript utilizando novas funcións de linguaxe de vangarda, pero aínda así o seu código de produción final funciona en navegadores máis antigos que non admiten esas funcións. Bos exemplos destas ferramentas son:
<ul>
<li><a href="https://babeljs.io/" target="_blank" rel="noopener noreferrer">Babel<ExternalLinkIcon/></a>: un compilador de JavaScript que permite aos desenvolvedores escribir o seu código usando JavaScript de vangarda, que Babel toma e converte en JavaScript antigo para que o poidan entender máis navegadores.</li>
<li><a href="https://postcss.org/" target="_blank" rel="noopener noreferrer">PostCSS<ExternalLinkIcon/></a>: Fai o mesmo tipo de cousas que Babel, pero para funcións CSS de vangarda. Se non hai unha forma equivalente de facer algo usando funcións CSS máis antigas, PostCSS instalará un polyfill de JavaScript para emular o efecto CSS que desexa.</li>
</ul>
</li>
<li>A opción de <strong>escribir o teu código nun idioma completamente diferente</strong> e transformalo nun idioma compatible coa web. Por exemplo:
<ul>
<li><a href="https://sass-lang.com/" target="_blank" rel="noopener noreferrer">Sass/SCSS<ExternalLinkIcon/></a>: Esta extensión CSS permítelle usar variables, regras aniñadas, mixins, funcións e moitas outras funcións, algunhas das cales están dispoñibles en CSS nativo (como as variables) e outras non.</li>
<li><a href="https://www.typescriptlang.org/" target="_blank" rel="noopener noreferrer">TypeScript<ExternalLinkIcon/></a>: TypeScript é un superconxunto de JavaScript que ofrece unha morea de funcións adicionais. O compilador TypeScript converte o código TypeScript en JavaScript cando se compila o código para a produción.</li>
<li><a href="https://reactjs.org/" target="_blank" rel="noopener noreferrer">React<ExternalLinkIcon/></a>, <a href="https://emberjs.com/" target="_blank" rel="noopener noreferrer">Emberjs<ExternalLinkIcon/></a>, ou <a href="https://vuejs.org/" target="_blank" rel="noopener noreferrer">Vue<ExternalLinkIcon/></a>: E outros frameworks que ofrecen moitas funcionalidades que se poden  empregar mediante unha sintaxe personalizada construída sobre <em>vanila</em> JavaScript. O código destes frameworks traballa en segundo plano para interpretar a sintaxe personalizada e representala como unha aplicación web final.</li>
</ul>
</li>
</ol>
<h3 id="post-desenvolvemento-post-development" tabindex="-1"><a class="header-anchor" href="#post-desenvolvemento-post-development" aria-hidden="true">#</a> Post desenvolvemento - <em>Post development</em></h3>
<p>Tamén existen ferramentas para ser usadas polos programadores despois do desenvolvemento. Estas ferramentas garanten que o teu código chegue á web e continúe funcionando. Isto inclúe os procesos de implantación, os marcos de proba, as ferramentas de auditoría e unhas cantas cousas máis.</p>
<p>Esta etapa do proceso de desenvolvemento é aquela coa que queres a menor interacción activa posible. Así que preferirás que, unha vez configurada, se execute na súa maior parte de forma automatica.</p>
<h4 id="ferramentas-de-proba-testing-tools" tabindex="-1"><a class="header-anchor" href="#ferramentas-de-proba-testing-tools" aria-hidden="true">#</a> Ferramentas de proba - <em>Testing tools</em></h4>
<p>Xeralmente adoptan a forma dunha ferramenta que executa probas automatizadas contra o teu código para que poidas asegurarte de que é correcto antes de proceder, por exemplo, no intento de facer cambios nun repositorio de GitHub. Isto pode incluír <em>linting</em>, pero tamén procedementos máis sofisticados como probas unitarias, onde executas partes do teu código, asegurándote de que se comportan como deberían.</p>
<ul>
<li>Os marcos para probas de redacción inclúen <a href="https://jestjs.io/" target="_blank" rel="noopener noreferrer">Jest<ExternalLinkIcon/></a>, <a href="https://mochajs.org/" target="_blank" rel="noopener noreferrer">Mocha<ExternalLinkIcon/></a>, e <a href="https://jasmine.github.io/" target="_blank" rel="noopener noreferrer">Jasmine<ExternalLinkIcon/></a>.</li>
<li>Os sistemas de notificación e execución de probas automatizadas inclúen <a href="https://travis-ci.org/" target="_blank" rel="noopener noreferrer">Travis CI<ExternalLinkIcon/></a>, <a href="https://jenkins.io/" target="_blank" rel="noopener noreferrer">Jenkins<ExternalLinkIcon/></a>, <a href="https://circleci.com/" target="_blank" rel="noopener noreferrer">Circle CI<ExternalLinkIcon/></a>, e <a href="https://en.m.wikipedia.org/wiki/List_of_build_automation_software#Continuous_integration" target="_blank" rel="noopener noreferrer">outros<ExternalLinkIcon/></a>.</li>
</ul>
<h4 id="ferramentas-de-implantacion-deployment-tools" tabindex="-1"><a class="header-anchor" href="#ferramentas-de-implantacion-deployment-tools" aria-hidden="true">#</a> Ferramentas de implantación - <em>Deployment tools</em></h4>
<p>Os sistemas de implantación permítenche publicar o teu sitio web, están dispoñibles tanto para sitios estáticos como dinámicos e adoitan funcionar xunto con sistemas de proba. Por exemplo, unha cadea de ferramentas típica esperará a que introduzas os cambios nun repositorio remoto, realizará algunhas probas para ver se os cambios están ben e, se as probas pasan, implementará automaticamente a túa aplicación nun sitio de produción.</p>
<p><a href="https://netlify.com/" target="_blank" rel="noopener noreferrer">Netlify<ExternalLinkIcon/></a> é unha das ferramentas de implementación máis populares neste momento, pero tamén hai outras como <a href="https://vercel.com/" target="_blank" rel="noopener noreferrer">Vercel<ExternalLinkIcon/></a> ou <a href="https://pages.github.com/" target="_blank" rel="noopener noreferrer">Github Pages<ExternalLinkIcon/></a>.</p>
<h4 id="outras-ferramentas" tabindex="-1"><a class="header-anchor" href="#outras-ferramentas" aria-hidden="true">#</a> Outras ferramentas</h4>
<p>Hai outros tipos de ferramentas dispoñibles para usar na fase posterior ao desenvolvemento, incluíndo <a href="https://codeclimate.com/" target="_blank" rel="noopener noreferrer">Code Climate<ExternalLinkIcon/></a> para recoller métricas de calidade do código, ou a <a href="https://webhint.io/docs/user-guide/extensions/extension-browser/" target="_blank" rel="noopener noreferrer">extensión do navegador webhint<ExternalLinkIcon/></a> para realizar análises de tempo de execución e da compatibilidade entre navegadores e outras comprobacións, <a href="https://probot.github.io/" target="_blank" rel="noopener noreferrer">Github Bots<ExternalLinkIcon/></a> para proporcionar unha funcionalidade GitHub máis potente, <a href="https://updown.io/" target="_blank" rel="noopener noreferrer">Updown<ExternalLinkIcon/></a> para obter un seguimento do tempo de actividade da aplicación e moitos máis!</p>
<h3 id="algunhas-consideracions-sobre-os-tipos-de-ferramentas" tabindex="-1"><a class="header-anchor" href="#algunhas-consideracions-sobre-os-tipos-de-ferramentas" aria-hidden="true">#</a> Algunhas consideracións sobre os tipos de ferramentas</h3>
<p>Sen dúbida, hai unha orde na que se poden aplicar cada un dos tipos de ferramentas durante o ciclo de vida do desenvolvemento, pero <em>ten</em> a certeza de que <strong>non <em>tes</em> que ter todas estas ferramentas para poder lanzar un sitio web</strong>. De feito, <strong>non necesitas ningunha delas</strong>. Iso si, se es quen de incluír algunhas destas ferramentas no teu proceso de desenvolvemento, mellorará a túa propia experiencia coma desenvolvedor e probablemente mellorará a calidade xeral do teu código.</p>
<p>Moitas veces, as novas ferramentas para desenvolvedores tardan algún tempo en axustar a súa complexidade. Unha das ferramentas máis coñecidas, Webpack, ten fama de ser demasiado complicada para traballar, inda que na última versión houbo un importante impulso co fin de simplificar o seu uso e reducir a configuración necesaria absolutamente ao mínimo.</p>
<p>Definitivamente non hai ningunha solución que garanta o éxito coas ferramentas, pero a medida que aumente a túa experiencia atoparás fluxos de traballo que funcionen <em>para ti</em> ou para o teu equipo. So a experimentación practica pode ofrecerche unha visión de cada unha destas, e outras, ferramentas; e se che solucionan algún proceso de desenvolvemento, poderás adoptalas para a tua entorna de desenvolvemento.</p>
<h2 id="como-elixir-e-obter-axuda-cunha-ferramenta-concreta" tabindex="-1"><a class="header-anchor" href="#como-elixir-e-obter-axuda-cunha-ferramenta-concreta" aria-hidden="true">#</a> Como elixir e obter axuda cunha ferramenta concreta</h2>
<p>A maioría das ferramentas adoitan escribirse e publicarse de forma illada, polo que, aínda que case seguramente hai axuda dispoñible, nunca está no mesmo lugar nin no mesmo formato. Pode ser difícil atopar axuda relevante de como usar unha ferramenta ou mesmo escoller a ferramenta que queres utilizar. O coñecemento sobre cales son as mellores ferramentas para usar é un pouco tribal, o que significa que, se aínda non estás na comunidade web, é difícil descubrir exactamente cales buscar.</p>
<p>Probablemente necesites unha combinación das seguintes cousas:</p>
<ul>
<li>Profesores, mentores, compañeiros ou compañeiros que teñan algunha experiencia e que resolveron estes problemas antes.</li>
<li>As buscas xerais na web de ferramentas para desenvolvedores front-end son xeralmente inútiles a non ser que xa coñezas o nome da ferramenta que estás a buscar.
<ul>
<li>Se estás a usar o xestor de paquetes npm para xestionar as túas dependencias, por exemplo, é unha boa idea ir á <a href="https://www.npmjs.com/" target="_blank" rel="noopener noreferrer">páxina de inicio npm<ExternalLinkIcon/></a> e buscar o tipo de ferramenta que está a localizar, por exemplo, intenta buscar &quot;data&quot; se queres unha utilidade de formato de data, ou &quot;formateador&quot; se está a buscar un formateador de código xeral. Presta atención á popularidade, calidade e puntuacións de mantemento e á última actualización do paquete. Tamén fai clic nas páxinas das ferramentas para saber cantas descargas mensuais ten un paquete e se ten boa documentación que poidas usar para saber se fai o que precisas.</li>
<li>Se está a buscar un complemento para integrar a funcionalidade da ferramenta no seu editor de código, consulte a páxina de complementos/extensións do editor de código; consulte <a href="https://atom.io/packages" target="_blank" rel="noopener noreferrer">Paquetes Atom<ExternalLinkIcon/></a> e <a href="https://marketplace.visualstudio.com/VSCode" target="_blank" rel="noopener noreferrer">Extensións de VSCode<ExternalLinkIcon/></a>, por exemplo. Bótalle un ollo ás extensións destacadas na páxina principal e, de novo, tenta buscar o tipo de extensión que quere (ou o nome da ferramenta, por exemplo, busque &quot;eslint&quot; na páxina de extensións de VSCode). Cando obteñas resultados, bótalle unha ollada a información como cantas estrelas ou descargas ten a extensión, como indicador da súa calidade.</li>
</ul>
</li>
<li>Foros relacionados co desenvolvemento para facer preguntas sobre que ferramentas utilizar, por exemplo <a href="https://discourse.mozilla.org/c/mdn/learn" target="_blank" rel="noopener noreferrer">MDN Learn Discourse<ExternalLinkIcon/></a>, ou <a href="https://stackoverflow.com/" target="_blank" rel="noopener noreferrer">Stackoverflow<ExternalLinkIcon/></a>.</li>
</ul>
<p>Cando escolles unha ferramenta para usar, o primeiro punto a visitar debería ser a páxina de inicio do proxecto da ferramenta.</p>
<p>Tamén podes querer atopar algúns titoriais dedicados a comezar con determinados tipos de ferramentas. Algún bos sitios para encetar<a href="https://css-tricks.com/" target="_blank" rel="noopener noreferrer">CSS Tricks<ExternalLinkIcon/></a>, <a href="https://dev.to/" target="_blank" rel="noopener noreferrer">Dev.to<ExternalLinkIcon/></a>, <a href="https://www.freecodecamp.org/" target="_blank" rel="noopener noreferrer">freeCodeCamp<ExternalLinkIcon/></a>, e <a href="https://www.smashingmagazine.com/" target="_blank" rel="noopener noreferrer">Revista Smashing<ExternalLinkIcon/></a>, xa que están adaptados á industria do desenvolvemento web.</p>
<p>Seguramente probarás diferentes ferramentas mentres buscas as máis axeitadas para ti. Só probándoas saberás se teñen sentido, se están ben documentadas e teñen un soporte preocupado por mellorar a ferramenta; e ante todo  se fan o que queres que fagan.</p>
<p>Isto só acaba de encetar. E está é só unha visión ampla e a ollo de paxaro sobre as <strong>ferramentas web do lado cliente</strong>.</p>
<p>OUT 2021</p>
<p><em><strong>ref:</strong></em>  <a href="https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Overview" target="_blank" rel="noopener noreferrer">https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Overview<ExternalLinkIcon/></a></p>
</div></template>


