<template><div><h6 id="obxectivos" tabindex="-1"><a class="header-anchor" href="#obxectivos" aria-hidden="true">#</a> Obxectivos</h6>
<ul>
<li><em>Dereito a accesibilidade</em></li>
<li><em>Importancia da accesibilidade</em></li>
<li><em>Ferramentas que poden axudarche a garantir que os teus recursos web sexan accesibles</em></li>
<li><em>Como desenvolver código tendo en conta a accesibilidade.</em></li>
<li>Tools that users use to browse through webpages.</li>
<li>Tools that developers use to ensure accessibility.</li>
<li>Skills for ensuring that your pages are accessible.</li>
</ul>
<h1 id="creacion-de-paxinas-web-accesibles" tabindex="-1"><a class="header-anchor" href="#creacion-de-paxinas-web-accesibles" aria-hidden="true">#</a> Creación de páxinas web accesibles</h1>
<figure><a href="https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/sketchnotes/webdev101-a11y.png" target="_blank" rel="noopener noreferrer"><img src="https://github.com/microsoft/Web-Dev-For-Beginners/raw/main/sketchnotes/webdev101-a11y.png" alt="Todo sobre a accesibilidade" tabindex="0" loading="lazy"><ExternalLinkIcon/></a><figcaption>Todo sobre a accesibilidade</figcaption></figure>
<blockquote>
<p>Sketchnote de <a href="https://twitter.com/girlie_mac" target="_blank" rel="noopener noreferrer">Tomomi Imura<ExternalLinkIcon/></a></p>
</blockquote>
<h2 id="o-papel-do-desenvolvedor" tabindex="-1"><a class="header-anchor" href="#o-papel-do-desenvolvedor" aria-hidden="true">#</a> O papel do desenvolvedor</h2>
<p>Os desenvolvedores xogan un papel fundamental para facer accesible un sitio web.</p>
<p>Desde a perspectiva dun desenvolvedor, o obxectivo é codificar un sitio web ou unha aplicación web que, como mínimo, cumpra os estándares AA 2.0 das directrices de accesibilidade ao contido web (WCAG). Para o que o teu sitio ou aplicación web debe seguir os principios reitores de POUR da tecnoloxía accesible:</p>
<ul>
<li><strong>Perceptible</strong>: os usuarios deben poder atopar cada elemento usando un dos seus sentidos.</li>
<li><strong>Operable</strong>: os usuarios deben poder interactuar co sitio e todas as súas funcións.</li>
<li><strong>Comprensible</strong>: o contido e a funcionalidade deben ser fáciles de seguir.</li>
<li><strong>Robusto</strong>: os sitios deben funcionar con varias tecnoloxías e considerar tecnoloxías futuras.</li>
</ul>
<p>Obtén máis información sobre os <a href="http://webaim.org/articles/pour/" target="_blank" rel="noopener noreferrer">principios reitores de POUR (WebAIM)<ExternalLinkIcon/></a> .</p>
<blockquote>
<p>O poder da Rede está na súa universalidade.
O acceso de todos independentemente da discapacidade é un aspecto esencial.</p>
<p>Tim Berners-Lee, director do W3C e inventor da World Wide Web</p>
</blockquote>
<p>Esta cita destaca perfectamente a importancia de crear sitios web accesibles. Unha aplicación á que non todos poden acceder é por definición excluínte. <strong>Como desenvolvedores web, debemos ter sempre presente a accesibilidade</strong>. Ao ter este interese desde o principio, estarás ben encamiñado para asegurarte de que todos poidan acceder ás páxinas que crees.</p>
<h2 id="ferramentas-a-utilizar" tabindex="-1"><a class="header-anchor" href="#ferramentas-a-utilizar" aria-hidden="true">#</a> Ferramentas a utilizar</h2>
<h3 id="lectores-de-pantalla" tabindex="-1"><a class="header-anchor" href="#lectores-de-pantalla" aria-hidden="true">#</a> Lectores de pantalla</h3>
<p>Unha das ferramentas de accesibilidade máis coñecidas son os lectores de pantalla.</p>
<p>Os <a href="https://en.wikipedia.org/wiki/Screen_reader" target="_blank" rel="noopener noreferrer">lectores de pantalla<ExternalLinkIcon/></a> son clientes de uso habitual para persoas con discapacidade visual. Como dedicamos tempo a garantir que un navegador transmite correctamente a información que desexamos compartir, tamén debemos asegurarnos de que un lector de pantalla faga o mesmo.</p>
<p>Na forma máis básica, un lector de pantalla lerá unha páxina de arriba abaixo de forma audible. Se a túa páxina é todo texto, o lector transmitirá a información dun xeito similar a un navegador. Por suposto, as páxinas web raramente son puramente texto; conterán ligazóns, gráficos, cor e outros compoñentes visuais. Hai que ter coidado para asegurarse de que esta información sexa lida correctamente por un lector de pantalla.</p>
<p>Todo desenvolvedor web debería familiarizarse cun lector de pantalla. Como se dixo anteriormente, é o cliente que potencialmente utilizarán moitos dos teus usuarios. Do mesmo xeito que deberás familiarizarte co funcionamento dun navegador, deberías aprender como funciona un lector de pantalla. Afortunadamente, os lectores de pantalla están integrados na maioría dos sistemas operativos.</p>
<p>Algúns navegadores tamén teñen ferramentas e extensións integradas que poden ler o texto en voz alta ou incluso proporcionar algunhas funcións básicas de navegación, como <a href="https://support.microsoft.com/help/4000734/microsoft-edge-accessibility-features" target="_blank" rel="noopener noreferrer">as ferramentas do navegador Edge centradas na accesibilidade<ExternalLinkIcon/></a> . Estas tamén son ferramentas de accesibilidade importantes, pero funcionan de forma moi diferente aos lectores de pantalla e non se deben confundir coas ferramentas de proba de lectores de pantalla.</p>
<p>✅Proba un lector de pantalla e un lector de texto do navegador. En Windows Inclúese <a href="https://support.microsoft.com/windows/complete-guide-to-narrator-e4397a0d-ef4f-b386-d8ae-c172f109bdb1" target="_blank" rel="noopener noreferrer">Narrator<ExternalLinkIcon/></a> por defecto e tamén se poden instalar <a href="https://webaim.org/articles/jaws/" target="_blank" rel="noopener noreferrer">JAWS<ExternalLinkIcon/></a> e <a href="https://www.nvaccess.org/about-nvda/" target="_blank" rel="noopener noreferrer">NVDA<ExternalLinkIcon/></a> . En macOS e iOS, <a href="https://support.apple.com/guide/voiceover/welcome/10" target="_blank" rel="noopener noreferrer">VoiceOver<ExternalLinkIcon/></a> está instalado de forma predeterminada.</p>
<h3 id="zoom" tabindex="-1"><a class="header-anchor" href="#zoom" aria-hidden="true">#</a> Zoom</h3>
<p>Outra ferramenta que usan habitualmente as persoas con discapacidade visual é o zoom. O tipo máis básico de zoom é o zoom estático, controlado mediante <code v-pre>Control + signo máis (+)</code>ou diminuíndo a resolución da pantalla. Este tipo de zoom fai que toda a páxina cambie o tamaño, polo que é importante utilizar <a href="https://developer.mozilla.org/docs/Learn/CSS/CSS_layout/Responsive_Design" target="_blank" rel="noopener noreferrer">un deseño responsivo<ExternalLinkIcon/></a> para ofrecer unha boa experiencia de usuario incluso en niveis de zoom elevados.</p>
<p>Outros tipo de zoom dependen dalgún software especializado para ampliar unha área da pantalla e facer unha panorámica, como se  se empregara unha lupa real. En Windows, <a href="https://support.microsoft.com/windows/use-magnifier-to-make-things-on-the-screen-easier-to-see-414948ba-8b1c-d3bd-8615-0e5e32204198" target="_blank" rel="noopener noreferrer">Magnifier<ExternalLinkIcon/></a> está integrado e <a href="https://www.freedomscientific.com/training/zoomtext/getting-started/" target="_blank" rel="noopener noreferrer">ZoomText<ExternalLinkIcon/></a> é un software de ampliación de terceiros con máis funcións e unha base de usuarios máis grande. Tanto macOS como iOS teñen un software de ampliación integrado chamado <a href="https://www.apple.com/accessibility/mac/vision/" target="_blank" rel="noopener noreferrer">Zoom<ExternalLinkIcon/></a> .</p>
<h3 id="validadores-de-contraste" tabindex="-1"><a class="header-anchor" href="#validadores-de-contraste" aria-hidden="true">#</a> Validadores de contraste</h3>
<p>As cores dos sitios web deben elixirse con coidado para responder ás necesidades dos usuarios daltónicos ou das persoas que teñen dificultades para ver cores de baixo contraste.</p>
<p>✅Proba un sitio web que che gusta usar para o uso da cor cunha extensión do navegador como <a href="https://microsoftedge.microsoft.com/addons/detail/wcag-color-contrast-check/idahaggnlnekelhgplklhfpchbfdmkjp?hl=en-US" target="_blank" rel="noopener noreferrer">o corrector de cores de WCAG<ExternalLinkIcon/></a> . Que aprendeches?</p>
<h3 id="lighthouse" tabindex="-1"><a class="header-anchor" href="#lighthouse" aria-hidden="true">#</a> Lighthouse</h3>
<p>Na área de ferramentas para desenvolvedores do teu navegador, atoparás a ferramenta Lighthouse. Esta ferramenta é importante para ter unha primeira visión da accesibilidade (así como doutras análises) dun sitio web. Aínda que é importante non confiar exclusivamente en Lighthouse, unha puntuación do 100 % é moi útil como referencia.</p>
<p>✅Busca Lighthouse no panel de ferramentas para desenvolvedores do teu navegador e realiza unha análise en calquera sitio. Que descobres?</p>
<h4 id="xeracion-de-puntuacion-de-accesibilidade-dunha-paxina-con-lighthouse" tabindex="-1"><a class="header-anchor" href="#xeracion-de-puntuacion-de-accesibilidade-dunha-paxina-con-lighthouse" aria-hidden="true">#</a> Xeración de puntuación de accesibilidade dunha páxina con Lighthouse</h4>
<p>Proba Lighthouse no explorador. Nas capturas de pantalla seguintes úsase Edge, pero podes seguir os mesmos pasos en Chrome e outros navegadores.</p>
<ol>
<li>
<p>Abre o explorador e vai até á páxina web principal de Microsoft.</p>
</li>
<li>
<p>Presiona a tecla F12 para abrir as ferramentas de desenvolvemento.</p>
</li>
<li>
<p>Na parte superior, selecciona o botón de contido adicional (&gt;&gt;) para abrir a lista de pestanas ocultas.</p>
</li>
</ol>
<figure><img src="@source/uf1841/assets/choose-tab.png" alt="Captura de pantalla das ferramentas de desenvolvemento có botón de contido adicional resaltado." tabindex="0" loading="lazy"><figcaption>Captura de pantalla das ferramentas de desenvolvemento có botón de contido adicional resaltado.</figcaption></figure>
<ol start="4">
<li>
<p>Selecciona Lighthouse na lista.</p>
</li>
<li>
<p>En Categories (Categorías), desactiva tódolos elementos, excepto Accessibility (Accesibilidade).</p>
</li>
<li>
<p>En Device (Dispositivo), selecciona Desktop (Escritorio).</p>
</li>
</ol>
<figure><img src="@source/uf1841/assets/lighthouse-option-selection.png" alt="Captura de pantalla de Lighthouse con Accessibility (Accesibilidad) seleccionado en Categories (Categorías), e Desktop (Escritorio) seleccionado en Device (Dispositivo)." tabindex="0" loading="lazy"><figcaption>Captura de pantalla de Lighthouse con Accessibility (Accesibilidad) seleccionado en Categories (Categorías), e Desktop (Escritorio) seleccionado en Device (Dispositivo).</figcaption></figure>
<ol start="7">
<li>
<p>Selecciona 'Generate report' (Xerar informe).</p>
</li>
<li>
<p>Observa a puntuación e a información asociada sobre a páxina.</p>
</li>
<li>
<p>Para probar outras páxinas, selecciona Clear all (Borrar todo) en Lighthouse, vai a outra páxina e, a continuación, selecciona Generate report (Xerar informe).</p>
</li>
</ol>
<figure><img src="@source/uf1841/assets/lighthouse-clear.png" alt="Captura de pantalla da sección de URL de Lighthouse, có botón para borrar todos os elementos resaltado." tabindex="0" loading="lazy"><figcaption>Captura de pantalla da sección de URL de Lighthouse, có botón para borrar todos os elementos resaltado.</figcaption></figure>
<p>Xa coñeces Lighthouse, e a información sobre accesibilidade que pode proporcionar. Emprega agora a ferramenta nos teus proxectos para mellorar a accesibilidade dos mesmos.</p>
<h2 id="deseno-para-a-accesibilidade" tabindex="-1"><a class="header-anchor" href="#deseno-para-a-accesibilidade" aria-hidden="true">#</a> Deseño para a accesibilidade</h2>
<p>A accesibilidade é un tema ben extenso. Para axudarche a entedela hai moitos recursos dispoñibles.</p>
<ul>
<li><a href="https://accessibility.umn.edu/your-role/web-developers" target="_blank" rel="noopener noreferrer">U accesible - Universidade de Minnesota<ExternalLinkIcon/></a> (é un sitio para encetar)</li>
</ul>
<p>Aínda que non poderemos cubrir todos os aspectos da creación de sitios accesibles, alo menos vexamos algúns dos principios fundamentais que é importante coñecer e implementar.</p>
<p><strong>Deseñar unha páxina accesible desde o principio sempre é máis fácil que volver a unha páxina existente para facela accesible.</strong></p>
<h2 id="bos-principios-de-visualizacion" tabindex="-1"><a class="header-anchor" href="#bos-principios-de-visualizacion" aria-hidden="true">#</a> Bos principios de visualización</h2>
<h3 id="paletas-de-cores-seguras" tabindex="-1"><a class="header-anchor" href="#paletas-de-cores-seguras" aria-hidden="true">#</a> Paletas de cores seguras</h3>
<p>A xente ve o mundo de diferentes xeitos, e isto inclúe as cores. Cando selecciones un esquema de cores para o teu sitio, debes asegurarte de que estea accesible para todos. Unha excelente <a href="http://colorsafe.co/" target="_blank" rel="noopener noreferrer">ferramenta para xerar paletas de cores é Color Safe<ExternalLinkIcon/></a> .</p>
<p>✅Identifica algúns sitios web que resulten problemático debido ao seu uso da cor. Que atopas?</p>
<h3 id="usa-o-html-correcto" tabindex="-1"><a class="header-anchor" href="#usa-o-html-correcto" aria-hidden="true">#</a> Usa o HTML correcto</h3>
<p>Con CSS e JavaScript é posible facer que calquera elemento pareza calquera tipo de control. <code v-pre>&lt;span&gt;</code> podería usarse para crear un <code v-pre>&lt;button&gt;</code>, e <code v-pre>&lt;b&gt;</code> podería converterse nun hiperligazón. Pero isto sería unha sofisticación nada útil xa que non lle transmite nada, por exemplo, a un lector de pantalla. O que sería aínda máis evidente nos elementos de control -botóns, formularios, enlaces,...-.</p>
<p>Cada elemento html ten un uso. Emprega o HTML axeitado ao crear unha páxina. Se queres unha hiperligazón, usa <code v-pre>&lt;a&gt;</code>. Usar o HTML correcto para o elemento ou control correcto chámase uso de HTML semántico.</p>
<p>✅Vaia a calquera sitio web e vexa se os deseñadores e desenvolvedores están a usar HTML correctamente. Podes atopar un botón que debería ser unha ligazón? Consello: fai clic co botón dereito e escolle &quot;Ver a fonte da páxina&quot; no teu navegador para ver o código subxacente.</p>
<h3 id="crea-unha-xerarquia-de-titulos-descritivos" tabindex="-1"><a class="header-anchor" href="#crea-unha-xerarquia-de-titulos-descritivos" aria-hidden="true">#</a> Crea unha xerarquía de títulos descritivos</h3>
<p>Os usuarios de lectores de pantalla <a href="https://webaim.org/projects/screenreadersurvey8/#finding" target="_blank" rel="noopener noreferrer">dependen moito dos títulos<ExternalLinkIcon/></a> para atopar información e navegar por unha páxina. Escribir contido descritivo de títulos e usar etiquetas de títulos semánticos son importantes para crear un sitio facilmente navegable para os usuarios de lectores de pantalla.</p>
<h3 id="use-boas-pistas-visuais" tabindex="-1"><a class="header-anchor" href="#use-boas-pistas-visuais" aria-hidden="true">#</a> Use boas pistas visuais</h3>
<p>CSS ofrece un control total sobre o aspecto de calquera elemento dunha páxina. Podes crear caixas de texto sen xustificado ou hipervínculos sen subliñado. Desafortunadamente, eliminar esas pistas pode facer máis difícil que alguén que dependa deles poida recoñecer o tipo de control.</p>
<h2 id="a-importancia-do-texto-da-ligazon" tabindex="-1"><a class="header-anchor" href="#a-importancia-do-texto-da-ligazon" aria-hidden="true">#</a> A importancia do texto da ligazón</h2>
<p>Os hipervínculos son fundamentais para navegar pola web. Como resultado, garantir que un lector de pantalla poida ler correctamente as ligazóns permite que todos os usuarios naveguen polo seu sitio.</p>
<h3 id="lectores-de-pantalla-e-ligazons" tabindex="-1"><a class="header-anchor" href="#lectores-de-pantalla-e-ligazons" aria-hidden="true">#</a> Lectores de pantalla e ligazóns</h3>
<p>Os lectores de pantalla len o texto das ligazóns do mesmo xeito que lerían calquera outro texto da páxina. Tendo isto en conta, o texto que se mostra a continuación pode parecer perfectamente aceptable.</p>
<blockquote>
<p>O pingüín pequeno, ás veces coñecido como o pingüín das fadas, é o pingüín máis pequeno do mundo. <a href="https://en.wikipedia.org/wiki/Little_penguin" target="_blank" rel="noopener noreferrer">Fai clic aquí<ExternalLinkIcon/></a> para obter máis información.</p>
</blockquote>
<blockquote>
<p>O pingüín pequeno, ás veces coñecido como o pingüín das fadas, é o pingüín máis pequeno do mundo. Visita <a href="https://en.wikipedia.org/wiki/Little_penguin" target="_blank" rel="noopener noreferrer">en.wikipedia.org/wiki/Little_penguin<ExternalLinkIcon/></a> para obter máis información.</p>
</blockquote>
<blockquote>
<p><strong>NOTA</strong> Como estás a piques de ler, <strong>nunca</strong> debes crear ligazóns que se parezan ás anteriores.</p>
</blockquote>
<p><strong>Lembra que os lectores de pantalla son unha interface diferente dos navegadores cun conxunto de funcións diferente.</strong></p>
<h3 id="o-problema-co-uso-do-url" tabindex="-1"><a class="header-anchor" href="#o-problema-co-uso-do-url" aria-hidden="true">#</a> O problema co uso do URL</h3>
<p>Os lectores de pantalla len o texto. Se aparece unha URL no texto, o lector de pantalla lerá a URL. En xeral, unha URL non transmite información significativa e pode parecer pouco clara e ate molesta lida na súa integridade. <em>hachetetepedouspuntosbarrabarradobreuvedobreuvedobreuveoquesexapuntocom</em> 🙄</p>
<h3 id="o-problema-con-fai-clic-aqui" tabindex="-1"><a class="header-anchor" href="#o-problema-con-fai-clic-aqui" aria-hidden="true">#</a> O problema con &quot;fai clic aquí&quot;</h3>
<p>Os lectores de pantalla tamén teñen a capacidade de ler só os hipervínculos dunha páxina, do mesmo xeito que unha persoa vidente ollearía unha páxina en busca de ligazóns. Se o texto da ligazón é sempre &quot;clic aquí&quot;, o único que o usuario escoitará é &quot;clic aquí, fai clic aquí, fai clic aquí, fai clic aquí, fai clic aquí, ...&quot; E semella que iso non facilita que as ligazóns se poidan distinguir entre si.</p>
<h3 id="bo-texto-da-ligazon" tabindex="-1"><a class="header-anchor" href="#bo-texto-da-ligazon" aria-hidden="true">#</a> Bo texto da ligazón</h3>
<p>Un bo texto da ligazón describe brevemente o que hai no outro lado da ligazón. No exemplo anterior falando de pingüíns pequenos, a ligazón é á páxina da Wikipedia sobre a especie. A frase <em>pingüíns</em> faría un texto de ligazón perfecto, xa que deixa claro o que alguén aprenderá se fai clic na ligazón: pingüíns.</p>
<blockquote>
<p>O <a href="https://en.wikipedia.org/wiki/Little_penguin" target="_blank" rel="noopener noreferrer">pingüín pequeno<ExternalLinkIcon/></a> , ás veces coñecido como o pingüín das fadas, é o pingüín máis pequeno do mundo.</p>
</blockquote>
<p>✅Navega pola web durante uns minutos para atopar páxinas que usan estratexias de ligazón pouco claras. Compáraos con outros sitios mellor vinculados. Que atopaches?</p>
<h4 id="unha-mellora-dobre" tabindex="-1"><a class="header-anchor" href="#unha-mellora-dobre" aria-hidden="true">#</a> Unha mellora dobre</h4>
<p>Garantir que o teu sitio sexa accesible para todos, axudará aos motores de busca a navegar polo teu sitio tamén. Os motores de busca usan o texto das ligazóns para coñecer os temas das páxinas. Entón, usar un bo texto nos enlaces resulta asemade unha moi boa estratexía de SEO orgánico.</p>
<h3 id="aria" tabindex="-1"><a class="header-anchor" href="#aria" aria-hidden="true">#</a> ARIA</h3>
<p>Imaxina a seguinte páxina:</p>
<table>
<thead>
<tr>
<th>Produto</th>
<th>Descrición</th>
<th>Orde</th>
</tr>
</thead>
<tbody>
<tr>
<td>Widget</td>
<td><a href="https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/1-getting-started-lessons/3-accessibility/'#'" target="_blank" rel="noopener noreferrer">Descrición<ExternalLinkIcon/></a></td>
<td><a href="https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/1-getting-started-lessons/3-accessibility/'#'" target="_blank" rel="noopener noreferrer">Orde<ExternalLinkIcon/></a></td>
</tr>
<tr>
<td>Super widget</td>
<td><a href="https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/1-getting-started-lessons/3-accessibility/'#'" target="_blank" rel="noopener noreferrer">Descrición<ExternalLinkIcon/></a></td>
<td><a href="https://github.com/microsoft/Web-Dev-For-Beginners/blob/main/1-getting-started-lessons/3-accessibility/'#'" target="_blank" rel="noopener noreferrer">Orde<ExternalLinkIcon/></a></td>
</tr>
</tbody>
</table>
<p>Neste exemplo, duplicar os textos 'Descrición' e 'Orde' ten sentido para alguén que use un navegador. Pero alguén que utilice un lector de pantalla só escoitaría as palabras <em>descrición</em> e <em>orde</em> repetidas sen contexto.</p>
<p>Neste tipo de escenarios, HTML admite un conxunto de atributos coñecidos como <a href="https://developer.mozilla.org/docs/Web/Accessibility/ARIA" target="_blank" rel="noopener noreferrer">ARIA (Accesible Rich Internet Applications)<ExternalLinkIcon/></a> . Estes atributos permítenche proporcionar información adicional aos lectores de pantalla.</p>
<blockquote>
<p><strong>NOTA</strong> : Como moitos aspectos do HTML, a compatibilidade con navegador e lector de pantalla pode variar. Non obstante, a maioría dos clientes principais admiten atributos ARIA.</p>
</blockquote>
<p>Podes usar <code v-pre>aria-label</code> para describir unha ligazón cando o formato da páxina non o permita. A descrición do widget podería establecerse como</p>
<div class="language-text line-numbers-mode" data-ext="text"><pre v-pre class="language-text"><code>&lt; a href =" # " aria-label =" Descrición do widget " > descrición &lt;/ a >   
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>✅En xeral, o uso dun marcado semántico axustado substitúe o uso de ARIA, pero ás veces non hai un equivalente semántico para os varios usos dos elementos HTML. Un bo exemplo é un esquema ou diagrama en árbore. Non hai un equivalente HTML para definir dita árbore, polo que so se identificaran os xenéricos <code v-pre>&lt;div&gt;</code> que comporían ese elemento. A menos que conten con roles e valores de aria adaptados. Consulta a <a href="https://developer.mozilla.org/docs/Web/Accessibility/ARIA" target="_blank" rel="noopener noreferrer">documentación de MDN sobre ARIA<ExternalLinkIcon/></a>.</p>
<div class="language-html line-numbers-mode" data-ext="html"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>h2</span> <span class="token attr-name">id</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>tree-label<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>Visor de arquivos<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>h2</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">role</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>tree<span class="token punctuation">"</span></span> <span class="token attr-name">aria-labelledby</span> <span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>tag for tree<span class="token punctuation">"</span></span> <span class="token punctuation">></span></span> &lt; div role =" treeitem " aria-expanded =" false " tabindex =" 0 " > Cargas &lt;/ div > &lt;/ div >  
  
     
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="imaxes" tabindex="-1"><a class="header-anchor" href="#imaxes" aria-hidden="true">#</a> Imaxes</h2>
<p>Os lectores de pantalla non poden ler automaticamente o que hai nunha imaxe. Asegurar que as imaxes sexan accesibles non leva moito traballo; é para o que serve o atributo  <code v-pre>alt</code>. <strong>Todas as imaxes significativas deben ter un <code v-pre>alt</code> para describir o que son</strong>.</p>
<p>As imaxes que sexan puramente decorativas deberían ter o seu atributo <code v-pre>alt</code> definido cunha cadea baleira: <code v-pre>alt=&quot;&quot;</code>. Isto evita que os lectores de pantalla anuncien innecesariamente a imaxe decorativa.</p>
<p>✅Como se podería esperar, os motores de busca tampouco son capaces de entender o que hai nunha imaxe. Tamén precisan <code v-pre>alt</code> , o texto alternativo. E lembra, asegurarte de que a túa páxina é accesible aporta beneficios adicionais de posicio.</p>
<h2 id="o-teclado" tabindex="-1"><a class="header-anchor" href="#o-teclado" aria-hidden="true">#</a> O teclado</h2>
<p>Algúns usuarios non poden usar un rato ou un panel táctil, e confían no teclado para saltar -de <em>tabulador en tabulador</em>- dun elemento a outro. É importante que o teu sitio web presente o contido nunha orde lóxica para que un usuario que empregue o teclado poida acceder a cada elemento interactivo mentres avanza polo documento. Se creas as túas páxinas web con marcas semánticas e usas CSS para diseñar o seu deseño visual, o teu sitio deberíase poder navegar co teclado, pero é importante probar este aspecto manualmente. Obtén máis información sobre <a href="https://webaim.org/techniques/keyboard/" target="_blank" rel="noopener noreferrer">as estratexias de navegación do teclado<ExternalLinkIcon/></a> .</p>
<p>✅Vai a calquera sitio web e tenta navegar por el usando só o teclado. Que funciona, que non funciona? Por que?</p>
<h2 id="lembra" tabindex="-1"><a class="header-anchor" href="#lembra" aria-hidden="true">#</a> Lembra</h2>
<p>Unha web accesible só para un poucos non é unha &quot;web mundial&quot;.</p>
<p>A mellor forma de garantir que os sitios que creas sexan accesibles é incorporar as mellores prácticas de accesibilidade desde o principio. Aínda que teñas que escribir algo máis de código, e aprender a incorporar estas habilidades ao teu fluxo de traballo, facer as túas páxinas accesibles significará moito para moita xente.</p>
<p>E demostrará que sabes resolver dous problemas dunha vez. 🍾</p>
<h2 id="🚀-desafio" tabindex="-1"><a class="header-anchor" href="#🚀-desafio" aria-hidden="true">#</a> 🚀 Desafío</h2>
<p>Toma este HTML e reescribío para que sexa o máis accesible posible, dadas as estratexias que aprendeches.</p>
<div class="language-html line-numbers-mode" data-ext="html"><pre v-pre class="language-html"><code><span class="token doctype"><span class="token punctuation">&lt;!</span><span class="token doctype-tag">DOCTYPE</span> <span class="token name">html</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>html</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>head</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>title</span><span class="token punctuation">></span></span>
      Example
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>title</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>link</span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">'</span>../assets/style.css<span class="token punctuation">'</span></span> <span class="token attr-name">rel</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">'</span>stylesheet<span class="token punctuation">'</span></span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">'</span>text/css<span class="token punctuation">'</span></span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>head</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>body</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>site-header<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>p</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>site-title<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>Turtle Ipsum<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>p</span><span class="token punctuation">></span></span>
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>p</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>site-subtitle<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>The World's Premier Turtle Fan Club<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>p</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>main-nav<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>p</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>nav-header<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>Resources<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>p</span><span class="token punctuation">></span></span>
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>nav-list<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>p</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>nav-item nav-item-bull<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>a</span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>https://www.youtube.com/watch?v=CMNry4PE93Y<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>"I like turtles"<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>a</span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>p</span><span class="token punctuation">></span></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>p</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>nav-item nav-item-bull<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>a</span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>https://en.wikipedia.org/wiki/Turtle<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>Basic Turtle Info<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>a</span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>p</span><span class="token punctuation">></span></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>p</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>nav-item nav-item-bull<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>a</span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>https://en.wikipedia.org/wiki/Turtles_(chocolate)<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>Chocolate Turtles<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>a</span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>p</span><span class="token punctuation">></span></span>
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>main-content<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span><span class="token punctuation">></span></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>p</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>page-title<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>Welcome to Turtle Ipsum. 
            <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>a</span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span><span class="token punctuation">"</span></span><span class="token punctuation">></span></span>Click here<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>a</span><span class="token punctuation">></span></span> to learn more.
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>p</span><span class="token punctuation">></span></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>p</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>article-text<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
          Turtle ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>p</span><span class="token punctuation">></span></span>
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>footer<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>footer-section<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>span</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>button<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>Sign up for turtle news<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>span</span><span class="token punctuation">></span></span>
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>footer-section<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>p</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>nav-header footer-title<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
          Internal Pages
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>p</span><span class="token punctuation">></span></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>nav-list<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
          <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>p</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>nav-item nav-item-bull<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>a</span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>../<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>Index<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>a</span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>p</span><span class="token punctuation">></span></span>
          <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>p</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>nav-item nav-item-bull<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>a</span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>../semantic<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>Semantic Example<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>a</span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>p</span><span class="token punctuation">></span></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span>
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span>
      <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>p</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>footer-copyright<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token entity named-entity" title="&copy;">&amp;copy;</span> 2016 Instrument<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>span</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>body</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>html</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="revision-e-autoestudo" tabindex="-1"><a class="header-anchor" href="#revision-e-autoestudo" aria-hidden="true">#</a> 📖 Revisión e autoestudo</h2>
<p>Moitos gobernos teñen leis sobre requisitos de accesibilidade. Consulta as leis de accesibilidade do teu país de orixe. Que está cuberto e que non? Un exemplo é <a href="https://www.boe.es/diario_boe/txt.php?id=BOE-A-2018-12699" target="_blank" rel="noopener noreferrer">este sitio web do goberno<ExternalLinkIcon/></a> .</p>
<p><strong>.ref</strong>: <a href="https://accessibility.umn.edu/your-role/web-developers" target="_blank" rel="noopener noreferrer">https://accessibility.umn.edu/your-role/web-developers<ExternalLinkIcon/></a></p>
<h2 id="desenvolver-un-sitio-accesible-plan-de-accion" tabindex="-1"><a class="header-anchor" href="#desenvolver-un-sitio-accesible-plan-de-accion" aria-hidden="true">#</a> Desenvolver un sitio accesible. Plan de Acción</h2>
<h3 id="comeza-cun-modelo-accesible" tabindex="-1"><a class="header-anchor" href="#comeza-cun-modelo-accesible" aria-hidden="true">#</a> - Comeza cun modelo accesible</h3>
<p>Para comezar o teu proxecto, podes empregar un modelo ou framework que inclua solucións de accesibilidade entre a súas caracteristicas. Asegúrate de que os elementos cos que construes o sitio sexan accesibles desde o principio. Afortunadamente, marcos como Bootstrap comezan a incorporar accesibilidade ao seu código e, o máis importante, aos seus exemplos.</p>
<p>Moitos exemplos na web afirman ser accesibles pero poden non selo, ou poden seguir un estándar diferente e menos rigoroso. Comproba sempre a accesibilidade de fragmentos de código, modelos e marcos antes de incorporalos ao teu proxecto.</p>
<h3 id="use-o-tema-web-folwell" tabindex="-1"><a class="header-anchor" href="#use-o-tema-web-folwell" aria-hidden="true">#</a> - Use o tema web Folwell</h3>
<p>O <a href="https://folwell.umn.edu/" target="_blank" rel="noopener noreferrer">tema web Folwell<ExternalLinkIcon/></a> da Universidade foi construído para ser accesible desde o comezo. Os compoñentes accesibles están incluídos nas versións empresariais de Drupal 8 e Drupal 8 Lite. <strong>O sitio da <a href="http://pattern-library.umn.edu/" target="_blank" rel="noopener noreferrer">biblioteca de patróns<ExternalLinkIcon/></a> alberga código Folwell para desenvolvedores que traballan fóra de Drupal</strong>.</p>
<p>Todos os <a href="https://folwell.umn.edu/folwell-components" target="_blank" rel="noopener noreferrer">compoñentes de Folwell<ExternalLinkIcon/></a> teñen en conta as medidas de accesibilidade que se incorporaron a cada compoñente. Consulte a pestana &quot;Accesibilidade&quot; na parte inferior de cada páxina de compoñente individual para obter máis información.</p>
<p>Pode ser un bo sitio onde probar, coñecer e entender as implicacións a nivel de redacción do código que escribes normalmente para facer un sitio accesible.</p>
<h3 id="escribir-codigo-accesible-desde-o-principio" tabindex="-1"><a class="header-anchor" href="#escribir-codigo-accesible-desde-o-principio" aria-hidden="true">#</a> - Escribir código accesible desde o principio</h3>
<p><strong>A accesibilidade debería incorporarse tan pronto como comeces a escribir código</strong>. A primeira vista, os estándares WCAG poden parecer confusos e complicados. Ademais, pode ser desalentador ter que aprender a usar diferentes tecnoloxías adaptadoras como lectores de pantalla. Aínda que debas superar esa curva de aprendizaxe inicial, cando remates levarache aproximadamente o mesmo tempo escribir código accesible que escribir código non accesible.</p>
<h3 id="proba-a-miudo" tabindex="-1"><a class="header-anchor" href="#proba-a-miudo" aria-hidden="true">#</a> Proba a miúdo</h3>
<p>Deberías <a href="https://accessibility.umn.edu/node/296" target="_blank" rel="noopener noreferrer">auditar e probar a accesibilidade web con<ExternalLinkIcon/></a> frecuencia <em>durante o desenvolvemento</em> .</p>
<p>Consulta os teus sitios web e aplicacións web nun navegador para asegurarte de que se mostran e funcionan correctamente. Os complementos e ferramentas do navegador poden axudarche a auditalos mentres codificas. Recoméndase probar o sitio web ou aplicación web mediante un lector de pantalla, inada que non sempre sexa estritamente necesario.</p>
<h3 id="codigo-para-todas-as-tecnoloxias-adaptadoras" tabindex="-1"><a class="header-anchor" href="#codigo-para-todas-as-tecnoloxias-adaptadoras" aria-hidden="true">#</a> Código para todas as tecnoloxías adaptadoras</h3>
<p>Estamos codificando para que a información sexa accesible ás persoas que usan calquera tipo de tecnoloxías adaptadoras. Os lectores de pantalla son só un exemplo.</p>
<h3 id="agora-lembra" tabindex="-1"><a class="header-anchor" href="#agora-lembra" aria-hidden="true">#</a> Agora lembra</h3>
<p><strong>No proceso desordenado para conseguir codificar un sitio web</strong> ou unha aplicación web, é fácil esquecer ou renunciar á accesibilidade. Recomendamos estas estratexias:</p>
<ul>
<li>Crea e utiliza unha lista de verificación para programadores mentres traballas.
<ul>
<li><a href="http://webaim.org/standards/wcag/checklist" target="_blank" rel="noopener noreferrer">Listas de verificación de exemplo<ExternalLinkIcon/></a>: lista de verificación <a href="http://webaim.org/standards/wcag/checklist" target="_blank" rel="noopener noreferrer">WebAIM<ExternalLinkIcon/></a> e <a href="http://a11yproject.com/checklist.html" target="_blank" rel="noopener noreferrer">lista de verificación do proxecto A11y<ExternalLinkIcon/></a></li>
</ul>
</li>
<li>Fai unha <a href="https://robots.thoughtbot.com/better-commit-messages-with-a-gitmessage-template" target="_blank" rel="noopener noreferrer">declaración de accesibilidade como parte do teu modelo de confirmación de código<ExternalLinkIcon/></a>.</li>
<li>Fai que as <a href="https://accessibility.umn.edu/node/296" target="_blank" rel="noopener noreferrer">probas<ExternalLinkIcon/></a> básicas de <a href="https://accessibility.umn.edu/node/296" target="_blank" rel="noopener noreferrer">accesibilidade<ExternalLinkIcon/></a> formen parte do proceso de garantía de calidade ou de aceptación do usuario.</li>
<li>Fai da accesibilidade un requisito creando unha <a href="http://www.interactiveaccessibility.com/blog/how-write-user-stories-accessibility-requirements" target="_blank" rel="noopener noreferrer">historia de usuario<ExternalLinkIcon/></a> para cada proxecto.xº</li>
</ul>
<h2 id="proba" tabindex="-1"><a class="header-anchor" href="#proba" aria-hidden="true">#</a> Proba</h2>
<p>A mellor maneira de entender como facer que as páxinas sexan accesibles e o impacto das decisións que se toman ao crear HTML é empregar algunhas das ferramientas que emplean os usuarios para navegar pola Web.</p>
<p>Desprázate por un par de páxinas mediante un lector de pantalla. Abre un sitio web que teña un formulario e use só o teclado para completalo. Esta actividade daráche unha idea do que algunos usuarios experimentan a diario al usar la Web y la importancia de garantizar que las páginas sean accesibles.</p>
<figure><img src="@source/uf1841/assets/make-compliant-website.png" alt="Fai a túa web accesible" tabindex="0" loading="lazy"><figcaption>Fai a túa web accesible</figcaption></figure>
<p>Máis información: <a href="https://interactiveaccessibility.com/blog/how-write-user-stories-accessibility-requirements" target="_blank" rel="noopener noreferrer">interactiveaccessibility<ExternalLinkIcon/></a></p>
<p><a href="https://www.webfx.com/blog/marketing/do-websites-have-to-be-ada-compliant/" target="_blank" rel="noopener noreferrer">Fai a túa web accesible<ExternalLinkIcon/></a></p>
<p><a href="http://accesibilidadweb.dlsi.ua.es/?menu=pautas-accesibilidad-contenido-web" target="_blank" rel="noopener noreferrer">Accesibilidad Web - Universitat d'Alacant<ExternalLinkIcon/></a></p>
<p><a href="https://developers.google.com/web/fundamentals/accessibility" target="_blank" rel="noopener noreferrer">Accesibilidade segundo Google<ExternalLinkIcon/></a></p>
<p>Podes tomar esta lección en <a href="https://docs.microsoft.com/learn/modules/web-development-101/accessibility?WT.mc_id=academic-13441-cxa" target="_blank" rel="noopener noreferrer">Microsoft Learn<ExternalLinkIcon/></a></p>
<p>OUT 2021
Revisión Nov 2021</p>
</div></template>


