<template><div><p><strong>HTML5 engadiu novos recursos á túa caixa de ferramentas, é probable que queiras crear un modelo HTML para comezar todos os proxectos futuros. Definitivamente paga a pena facelo, e hai moitos puntos de partida en liña para axudarche a crear o teu propio modelo HTML5.</strong></p>
<p><s>Neste artigo, veremos como comezar a construír o teu propio modelo HTML5. Percorreremos os elementos esenciais dun modelo HTML, rematando cun modelo básico que podes levar contigo e construír.</s></p>
<p><s>Se prefires coller o código agora e ler este artigo máis tarde, <a href="https://www.sitepoint.com/a-basic-html5-template/#thecompletehtml5boilerplate" target="_blank" rel="noopener noreferrer"><strong>aquí tes o noso modelo HTML5 rematado</strong><ExternalLinkIcon/></a> .</s></p>
<h2 id="anatomia-dun-documento-html5" tabindex="-1"><a class="header-anchor" href="#anatomia-dun-documento-html5" aria-hidden="true">#</a> Anatomía dun documento HTML5</h2>
<p>Un modelo HTML normalmente componse das seguintes partes:</p>
<ol>
<li><a href="#thehtml5doctype">A declaración do tipo de documento</a> (ou doctype)</li>
<li><a href="#thehtmlelement">O elemento <code v-pre>html</code></a></li>
<li><a href="#htmldocumentcharacterencoding">A codificación de caracteres</a></li>
<li><a href="#theviewportmetaelement">O metaelemento da vista</a></li>
<li><a href="https://www.sitepoint.com/a-basic-html5-template/#thetitledescriptionandauthor" target="_blank" rel="noopener noreferrer"><code v-pre>title</code>, <code v-pre>description</code>e<code v-pre>author</code><ExternalLinkIcon/></a></li>
<li><a href="https://www.sitepoint.com/a-basic-html5-template/#opengraphmetaelementsforsocialcards" target="_blank" rel="noopener noreferrer">Metaelementos Open Graph para tarxetas sociais<ExternalLinkIcon/></a></li>
<li><a href="https://www.sitepoint.com/a-basic-html5-template/#faviconsandtouchicons" target="_blank" rel="noopener noreferrer">Favicons e iconas táctiles<ExternalLinkIcon/></a></li>
<li><a href="https://www.sitepoint.com/a-basic-html5-template/#includingastylesheetandscripts" target="_blank" rel="noopener noreferrer">Ligazóns a follas de estilo e guións<ExternalLinkIcon/></a></li>
</ol>
<p>Ademais da declaración do tipo de documento e do elemento <code v-pre>&lt;html&gt;</code> os elementos enumerados anteriormente atoparanse principalmente dentro da sección <code v-pre>&lt;head&gt;</code> do modelo HTML.</p>
<h2 id="o-tipo-de-documento-html5" tabindex="-1"><a class="header-anchor" href="#o-tipo-de-documento-html5" aria-hidden="true">#</a> O tipo de documento HTML5</h2>
<p>O teu modelo HTML5 debe comezar cunha declaración de tipo de documento ou <em>doctype</em> . Un doctype é simplemente un xeito de indicarlle ao navegador, ou a calquera outro analizador, que tipo de documento está mirando.</p>
<p>No caso dos arquivos HTML, está etiqueta indica a versión específica e o <em>sabor</em> HTML. Está declaración do tipo de documento debe ser sempre o primeiro elemento na parte superior de calquera arquivo HTML. Fai uns anos, a declaración doctype era bastante engedellada e dificil de completar.</p>
<p>Declaración para os documentos XHTML:</p>
<div class="language-html line-numbers-mode" data-ext="html"><pre v-pre class="language-html"><code><span class="token doctype"><span class="token punctuation">&lt;!</span><span class="token doctype-tag">DOCTYPE</span> <span class="token name">html</span> <span class="token name">PUBLIC</span> <span class="token string">"-//W3C//DTD XHTML 1.0 Strict//EN"</span>
   <span class="token string">"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>Declaración para os documentos HTML 4:</p>
<div class="language-html line-numbers-mode" data-ext="html"><pre v-pre class="language-html"><code><span class="token doctype"><span class="token punctuation">&lt;!</span><span class="token doctype-tag">DOCTYPE</span> <span class="token name">HTML</span> <span class="token name">PUBLIC</span> <span class="token string">"-//W3C//DTD HTML 4.01 Transitional//EN"</span>
            <span class="token string">"http://www.w3.org/TR/html4/loose.dtd"</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>Coa chegada de HTML5, eses fantasmas indescifrables desapareceron e agora todo o que necesitas é isto:</p>
<div class="language-html line-numbers-mode" data-ext="html"><pre v-pre class="language-html"><code><span class="token doctype"><span class="token punctuation">&lt;!</span><span class="token doctype-tag">doctype</span> <span class="token name">html</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Sinxelo, e ao gran. O doctype pódese escribir en maiúsculas, minúsculas ou en mestura. Notarás que falta  o &quot;5&quot; na declaración. Aínda que a versión actual do marcado web coñécese como &quot;HTML5&quot;, realmente é só unha evolución dos estándares HTML anteriores, e as futuras especificacións serán simplemente un desenvolvemento do que temos hoxe. Nunca haberá un &quot;HTML6&quot;, polo que tamén resulta común e admitido referirse ao estado actual do marcado web simplemente como &quot;HTML&quot;.</p>
<p>Dado que os navegadores están obrigados a admitir contidos máis antigos que inda viven na web, non se depende do doctype para indicarlles aos navegadores qué características se deben admitir dun determinado documento. Así, o doctype por si só non vai facer que as túas páxinas sean compatibles coas características modernas de HTML. En realidade é o navegador o encargado de determinar a compatibilidade das funcións caso por caso, independentemente do tipo de documento utilizado. De feito, podes usar un dos doctypes máis antigos cos novos elementos HTML5 nunha páxina e a páxina mostrarase igual que se usase doctype máis novo</p>
<p>En realidad, es el navegador el que debe determinar la compatibilidad de las características caso por caso, independientemente del doctype utilizado. De hecho, puedes utilizar uno de los doctypes más antiguos con los nuevos elementos de HTML5 en una página y la página se renderizará igual que si utilizaras el nuevo doctype.</p>
<h2 id="o-html-elemento" tabindex="-1"><a class="header-anchor" href="#o-html-elemento" aria-hidden="true">#</a> O <code v-pre>&lt;html&gt;</code>Elemento</h2>
<p>Despois do doctype en calquera documento HTML está o elemento <code v-pre>&lt;html&gt;</code>:</p>
<div class="language-markup line-numbers-mode" data-ext="markup"><pre v-pre class="language-markup"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>html</span> <span class="token attr-name">lang</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>en<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Isto non sufriu ningún cambio significativo desde a aparición de HTML5. No fragmento de código anterior, incluímos o atributo <code v-pre>lang</code> cun valor de <code v-pre>en</code>, que especifica que o documento está en inglés. Isto non é necesario para que unha páxina se valide, pero recibirás unha advertencia da maioría dos validadores de código se non o inclúes.</p>
<p>O <code v-pre>&lt;html&gt;</code>elemento divídese en dúas partes, o <code v-pre>&lt;head&gt;</code>e <code v-pre>&lt;body&gt;</code>seccións. A <code v-pre>&lt;head&gt;</code>sección contén información importante sobre o documento que non se mostra ao usuario final, como a <a href="https://www.sitepoint.com/a-basic-html5-template/#htmldocumentcharacterencoding" target="_blank" rel="noopener noreferrer">codificación de caracteres<ExternalLinkIcon/></a> e <a href="https://www.sitepoint.com/a-basic-html5-template/#includingastylesheetandscripts" target="_blank" rel="noopener noreferrer">ligazóns a arquivos CSS e posiblemente JavaScript<ExternalLinkIcon/></a> . A <code v-pre>&lt;body&gt;</code>sección contén todo o que se mostra no navegador: texto, imaxes, etc.</p>
<h2 id="codificacion-de-caracteres-de-documentos-html" tabindex="-1"><a class="header-anchor" href="#codificacion-de-caracteres-de-documentos-html" aria-hidden="true">#</a> Codificación de caracteres de documentos HTML</h2>
<p>A primeira liña dentro da sección <code v-pre>&lt;head&gt;</code> dun documento HTML é a que define a codificación de caracteres para o documento. Esta é unha función opcional e non causará avisos nos validadores, pero recoméndase para a maioría das páxinas HTML:</p>
<div class="language-markup line-numbers-mode" data-ext="markup"><pre v-pre class="language-markup"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>meta</span> <span class="token attr-name">charset</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>utf-8<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>En case todos os casos, se emprega o valor  <code v-pre>utf-8</code>. Unha explicación completa da codificación de caracteres está fóra do alcance deste artigo, e probablemente tampouco che resulte tan interesante. Non obstante, se queres profundizar un pouco máis, podes <a href="https://html.spec.whatwg.org/multipage/infrastructure.html#encoding-terminology" target="_blank" rel="noopener noreferrer">ler sobre a codificación de caracteres na especificación HTML<ExternalLinkIcon/></a> .</p>
<iframe frameborder="0" src="https://8a3a1affd7b9f05dbfd70710ff677661.safeframe.googlesyndication.com/safeframe/1-0-38/html/container.html" id="google_ads_iframe_/5376056,7448792/sitepoint_dynamic/dynamic_1_0" title="3rd party ad content" name="" scrolling="no" marginwidth="0" marginheight="0" width="728" height="90" data-is-safeframe="true" sandbox="allow-forms allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts allow-top-navigation-by-user-activation" data-google-container-id="d" data-load-complete="true" style="box-sizing: border-box !important; border: 0px; vertical-align: bottom;"></iframe>
<p><em>Nota: para garantir que certos navegadores máis antigos lean correctamente a codificación de caracteres, a declaración de codificación de caracteres completa debe incluírse nalgún lugar dentro dos primeiros 512 caracteres do documento. Tamén debería aparecer antes de calquera elemento baseado no contido (como o <code v-pre>&lt;title&gt;</code>elemento que aparece máis adiante no noso exemplo)</em> .</p>
<p>Poderiamos escribir moito máis sobre este tema, pero de momento, conformámonos con aceptar esta declaración simplificada e pasar á seguinte parte do noso documento.</p>
<h2 id="o-meta-elemento-viewport" tabindex="-1"><a class="header-anchor" href="#o-meta-elemento-viewport" aria-hidden="true">#</a> O Meta Elemento Viewport</h2>
<p>O metaelemento viewport é unha característica que verás en case todos os modelos HTML5. É importante para o deseño web responsive e o deseño para móbiles:</p>
<div class="language-markup line-numbers-mode" data-ext="markup"><pre v-pre class="language-markup"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>meta</span> <span class="token attr-name">name</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>viewport<span class="token punctuation">"</span></span> <span class="token attr-name">content</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>width=device-width, initial-scale=1<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Este <code v-pre>&lt;meta&gt;</code>elemento inclúe dous atributos que funcionan xuntos como un conxunto de nome/valor. Neste caso, o <code v-pre>name</code>está establecido en <code v-pre>viwport</code>e o valor é <code v-pre>width=device-width, initial-scale=1</code>. Isto só o utilizan os dispositivos móbiles. Notarás que o valor ten dúas partes, descritas aquí:</p>
<ul>
<li><code v-pre>width=device-width</code>: o ancho de píxeles da ventana gráfica na que quere que se represente o sitio web.</li>
<li><code v-pre>initial-scale</code>: debería ser un número positivo entre 0,0 e 10,0. Un valor de &quot;1&quot; indica que hai unha relación de 1:1 entre o ancho do dispositivo e o tamaño da ventana gráfica.</li>
</ul>
<p>Podes ler un pouco máis sobre estas funcións <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name#standard_metadata_names_defined_in_other_specifications" target="_blank" rel="noopener noreferrer">do metaelemento en MDN<ExternalLinkIcon/></a> , pero polo momento só sabes que, na maioría dos casos, este metaelemento con esta configuración é o mellor para sitios web adaptados a dispositivos móbiles.</p>
<h2 id="os-title-description-eauthor" tabindex="-1"><a class="header-anchor" href="#os-title-description-eauthor" aria-hidden="true">#</a> Os <code v-pre>&lt;title&gt;</code>, <code v-pre>description</code>, e<code v-pre>author</code></h2>
<p>A seguinte sección do modelo HTML contén as seguintes tres liñas:</p>
<div class="language-markup line-numbers-mode" data-ext="markup"><pre v-pre class="language-markup"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>title</span><span class="token punctuation">></span></span>A Basic HTML5 Template<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>title</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>meta</span> <span class="token attr-name">name</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>description<span class="token punctuation">"</span></span> <span class="token attr-name">content</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>A simple HTML5 Template for new projects.<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>meta</span> <span class="token attr-name">name</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>author<span class="token punctuation">"</span></span> <span class="token attr-name">content</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>SitePoint<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Estes elementos forman parte do HTML durante moito tempo, polo que non hai nada novo aquí. O <code v-pre>&lt;title&gt;</code>é o que aparece na barra de título do navegador (como cando pasa o rato sobre a pestana do navegador). Este elemento é o único elemento obrigatorio dentro do <code v-pre>&lt;head&gt;</code>.</p>
<p>Os outros dous son <code v-pre>&lt;meta&gt;</code>elementos opcionais que definen unha descrición para fins de SEO xunto cun autor. Todos os elementos no interior <code v-pre>&lt;head&gt;</code>son opcionais, excepto <code v-pre>&lt;title&gt;</code>. En realidade, pode pór <a href="https://html.spec.whatwg.org/multipage/semantics.html#the-meta-element" target="_blank" rel="noopener noreferrer">como moitos válidos ``elementos<ExternalLinkIcon/></a> no <code v-pre>&lt;head&gt;</code>momento.</p>
<h2 id="open-graph-meta-elements-para-tarxetas-sociais" tabindex="-1"><a class="header-anchor" href="#open-graph-meta-elements-para-tarxetas-sociais" aria-hidden="true">#</a> Open Graph Meta Elements para tarxetas sociais</h2>
<p>Como se mencionou, todos os metaelementos son opcionais, pero moitos teñen beneficios para o SEO e o marketing en redes sociais. A seguinte sección do noso modelo HTML5 inclúe algunhas destas opcións de metaelementos:</p>
<div class="language-markup line-numbers-mode" data-ext="markup"><pre v-pre class="language-markup"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>meta</span> <span class="token attr-name">property</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>og:title<span class="token punctuation">"</span></span> <span class="token attr-name">content</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>A Basic HTML5 Template<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>meta</span> <span class="token attr-name">property</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>og:type<span class="token punctuation">"</span></span> <span class="token attr-name">content</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>website<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>meta</span> <span class="token attr-name">property</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>og:url<span class="token punctuation">"</span></span> <span class="token attr-name">content</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>https://www.sitepoint.com/a-basic-html5-template/<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>meta</span> <span class="token attr-name">property</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>og:description<span class="token punctuation">"</span></span> <span class="token attr-name">content</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>A simple HTML5 Template for new projects.<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>meta</span> <span class="token attr-name">property</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>og:image<span class="token punctuation">"</span></span> <span class="token attr-name">content</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>image.png<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Estes <code v-pre>&lt;meta&gt;</code>elementos aproveitan algo chamado protocolo Open Graph, e hai moitos outros que podes usar. Estes son os que é probable que uses con máis frecuencia. Podes ver unha lista completa das meta opcións dispoñibles de Open Graph no <a href="https://ogp.me/" target="_blank" rel="noopener noreferrer">sitio web de Open Graph<ExternalLinkIcon/></a> .</p>
<p>Os que incluímos aquí mellorarán a aparencia da páxina web cando estea ligada nunha publicación de redes sociais. Por exemplo, os cinco <code v-pre>&lt;meta&gt;</code>elementos incluídos aquí aparecerán nas tarxetas sociais que inclúen os seguintes datos:</p>
<ul>
<li>un título para o contido</li>
<li>o tipo de contido que se entrega</li>
<li>o URL canónico para o contido</li>
<li>unha descrición do contido</li>
<li>unha imaxe para asociar co contido</li>
</ul>
<p>Cando ves unha publicación compartida nas redes sociais, moitas veces verás estes datos engadidos automaticamente á publicación das redes sociais. Por exemplo, a continuación móstrase o que aparecería nun tweet se incluíses unha ligazón á páxina de inicio de GitHub:</p>
<figure><img src="https://uploads.sitepoint.com/wp-content/uploads/2021/06/1624432100github-card.png" alt="Tarxeta GitHub" tabindex="0" loading="lazy"><figcaption>Tarxeta GitHub</figcaption></figure>
<iframe frameborder="0" src="https://8a3a1affd7b9f05dbfd70710ff677661.safeframe.googlesyndication.com/safeframe/1-0-38/html/container.html" id="google_ads_iframe_/5376056,7448792/sitepoint_dynamic/dynamic_2_0" title="3rd party ad content" name="" scrolling="no" marginwidth="0" marginheight="0" width="728" height="90" data-is-safeframe="true" sandbox="allow-forms allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts allow-top-navigation-by-user-activation" data-google-container-id="e" data-load-complete="true" style="box-sizing: border-box !important; border: 0px; vertical-align: bottom;"></iframe>
<p><a href="https://user-images.githubusercontent.com/558709/121095418-5218c200-c7be-11eb-97d3-75bbaf52e244.png" target="_blank" rel="noopener noreferrer">Fonte da imaxe: GitHub<ExternalLinkIcon/></a></p>
<h2 id="favicons-e-iconas-tactiles" tabindex="-1"><a class="header-anchor" href="#favicons-e-iconas-tactiles" aria-hidden="true">#</a> Favicons e iconas táctiles</h2>
<p>A seguinte sección do modelo HTML5 inclúe <code v-pre>&lt;link&gt;</code>elementos que indican recursos para incluír como favicon e icona táctil de mazá:</p>
<div class="language-markup line-numbers-mode" data-ext="markup"><pre v-pre class="language-markup"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>link</span> <span class="token attr-name">rel</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>icon<span class="token punctuation">"</span></span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>/favicon.ico<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>link</span> <span class="token attr-name">rel</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>icon<span class="token punctuation">"</span></span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>/favicon.svg<span class="token punctuation">"</span></span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>image/svg+xml<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>link</span> <span class="token attr-name">rel</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>apple-touch-icon<span class="token punctuation">"</span></span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>/apple-touch-icon.png<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>O <code v-pre>favicon.ico</code>arquivo é para navegadores legados e non ten que estar incluído no código. Sempre que o <code v-pre>favicon.ico</code>arquivo estea incluído na raíz do proxecto, o navegador atoparao automaticamente. O <code v-pre>favicon.svg</code>arquivo é para navegadores modernos que admiten iconas SVG. O último elemento fai referencia á icona que se usa nos dispositivos Apple cando a páxina se engade á pantalla de inicio do usuario.</p>
<p>Hai outras opcións que pode incluír aquí, incluíndo un arquivo de manifesto de aplicación web que fai referencia a outras iconas. Para unha discusión completa, recomendamos a <a href="https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs" target="_blank" rel="noopener noreferrer">publicación de Andrey Sitnik<ExternalLinkIcon/></a> sobre o tema. Pero os incluídos aquí serán suficientes para un simple modelo de inicio.</p>
<h2 id="incluindo-unha-folla-de-estilo-e-scripts" tabindex="-1"><a class="header-anchor" href="#incluindo-unha-folla-de-estilo-e-scripts" aria-hidden="true">#</a> Incluíndo unha folla de estilo e scripts</h2>
<p>As dúas últimas partes significativas do noso modelo HTML son a referencia a unha folla de estilo e un guión. Ambos son opcionais, por suposto:</p>
<div class="language-markup line-numbers-mode" data-ext="markup"><pre v-pre class="language-markup"><code>  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>link</span> <span class="token attr-name">rel</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>stylesheet<span class="token punctuation">"</span></span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>css/styles.css?v=1.0<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>A folla de estilo inclúese usando o <code v-pre>&lt;link&gt;</code>elemento cun <code v-pre>rel</code>atributo apropiado . Pódese incluír unha folla de estilo en calquera lugar dun documento, pero normalmente verá dentro do <code v-pre>&lt;head&gt;</code>. E a diferenza das versións antigas de HTML, non é necesario incluír un <code v-pre>type</code>atributo (que nunca foi necesario en primeiro lugar).</p>
<p>Do mesmo xeito que cos elementos de guión, verás case en calquera parte dun documento, pero normalmente están na parte inferior (xusto antes da <code v-pre>&lt;/body&gt;</code>etiqueta de peche ) como mellor práctica.</p>
<div class="language-markup line-numbers-mode" data-ext="markup"><pre v-pre class="language-markup"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>script</span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>js/scripts.js<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token script"></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>script</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Colocar o <code v-pre>&lt;script&gt;</code>elemento na parte inferior da páxina é para os efectos da velocidade de carga da páxina. Cando un navegador atopa un script, fará unha pausa na descarga e renderización do resto da páxina mentres analiza o script. Isto fai que a páxina se cargue moito máis lentamente cando se inclúen scripts grandes na parte superior da páxina antes de calquera contido. Así, a maioría dos scripts deberían colocarse na parte inferior da páxina, de xeito que só se analizarán despois de que se cargue o resto da páxina. Pero teña en conta que, nalgúns casos, é posible <em>que</em> o script <em>teña</em> que colocarse na cabeceira do documento, porque quere que teña efecto antes de que o navegador comece a renderizar a páxina.</p>
<p>Do mesmo xeito que as referencias ás follas de estilo, o <code v-pre>type</code>atributo nos scripts non é (e nunca foi) necesario. Xa que JavaScript é, para todos os efectos prácticos, a única linguaxe de secuencias de comandos real que se usa na web, e dado que todos os navegadores asumirán que estás a usar JavaScript aínda que non o declares explícitamente, podes deixar fóra con seguridade <code v-pre>type=&quot;text/javascript</code>, que moitas veces aparece no código heredado.</p>
<h2 id="unha-nota-sobre-os-navegadores-mais-antigos-e-os-novos-elementos" tabindex="-1"><a class="header-anchor" href="#unha-nota-sobre-os-navegadores-mais-antigos-e-os-novos-elementos" aria-hidden="true">#</a> Unha nota sobre os navegadores máis antigos e os novos elementos</h2>
<p>Cando se introduciu HTML5, incluíu unha serie de elementos novos, como <code v-pre>&lt;article&gt;</code>e <code v-pre>&lt;section&gt;</code>. Poderías pensar que o soporte para elementos non recoñecidos sería un problema importante para os navegadores máis antigos, pero non o é! A maioría dos navegadores non lles importan as etiquetas que use. Se tiveses un documento HTML cun <code v-pre>&lt;recipe&gt;</code>elemento (ou incluso un <code v-pre>&lt;ziggy&gt;</code>elemento) nel e o teu CSS anexase algúns estilos a ese elemento, case todos os navegadores procederían coma se isto fose totalmente normal, aplicando o teu estilo sen queixas.</p>
<p>Por suposto, un documento tan hipotético non se validaría e pode ter problemas de accesibilidade, pero mostraríase correctamente en case todos os navegadores, a excepción das versións antigas de Internet Explorer (IE). Antes da versión 9, IE impedía que os elementos non recoñecidos recibisen estilo. Estes elementos misteriosos foron vistos polo motor de renderizado como &quot;elementos descoñecidos&quot;, polo que non puideches cambiar o seu aspecto ou o seu comportamento. Isto inclúe non só os nosos elementos imaxinados, senón tamén todos os elementos que aínda non estaban por definir no momento en que se desenvolveron esas versións do navegador, incluídos os novos elementos HTML5.</p>
<p>Afortunadamente, os navegadores máis antigos que non admiten o estilo de elementos novos son practicamente inexistentes hoxe en día, polo que podes usar con seguridade calquera elemento HTML novo e sen preocupación en case calquera proxecto.</p>
<p>Dito isto, se <em>realmente</em> precisas admitir navegadores antigos, aínda podes usar o fiable <a href="https://johnresig.com/blog/html5-shiv/" target="_blank" rel="noopener noreferrer">HTML5 Shiv<ExternalLinkIcon/></a> , unha sinxela peza de JavaScript desenvolvida orixinalmente por John Resig. <a href="https://www.paulirish.com/2011/the-history-of-the-html5-shiv/" target="_blank" rel="noopener noreferrer">Inspirado no traballo de Sjoerd Visscher<ExternalLinkIcon/></a> , fixo que os novos elementos HTML5 fosen estilizados en versións antigas de IE. Realmente, porén, isto non debería ser necesario hoxe. Como indica <a href="https://caniuse.com/#feat=html5semantic" target="_blank" rel="noopener noreferrer">caniuse.com<ExternalLinkIcon/></a> , os elementos HTML5 son compatibles con todos os navegadores en uso.</p>
<h2 id="o-modelo-completo-de-html5" tabindex="-1"><a class="header-anchor" href="#o-modelo-completo-de-html5" aria-hidden="true">#</a> O modelo completo de HTML5</h2>
<p>Aquí tes o noso modelo HTML5 final, un modelo básico que podes usar para calquera proxecto:</p>
<div class="language-markup line-numbers-mode" data-ext="markup"><pre v-pre class="language-markup"><code><span class="token doctype"><span class="token punctuation">&lt;!</span><span class="token doctype-tag">doctype</span> <span class="token name">html</span><span class="token punctuation">></span></span>

<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>html</span> <span class="token attr-name">lang</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>en<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>head</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>meta</span> <span class="token attr-name">charset</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>utf-8<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>meta</span> <span class="token attr-name">name</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>viewport<span class="token punctuation">"</span></span> <span class="token attr-name">content</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>width=device-width, initial-scale=1<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>

  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>title</span><span class="token punctuation">></span></span>A Basic HTML5 Template<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>title</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>meta</span> <span class="token attr-name">name</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>description<span class="token punctuation">"</span></span> <span class="token attr-name">content</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>A simple HTML5 Template for new projects.<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>meta</span> <span class="token attr-name">name</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>author<span class="token punctuation">"</span></span> <span class="token attr-name">content</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>SitePoint<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>

  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>meta</span> <span class="token attr-name">property</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>og:title<span class="token punctuation">"</span></span> <span class="token attr-name">content</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>A Basic HTML5 Template<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>meta</span> <span class="token attr-name">property</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>og:type<span class="token punctuation">"</span></span> <span class="token attr-name">content</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>website<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>meta</span> <span class="token attr-name">property</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>og:url<span class="token punctuation">"</span></span> <span class="token attr-name">content</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>https://www.sitepoint.com/a-basic-html5-template/<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>meta</span> <span class="token attr-name">property</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>og:description<span class="token punctuation">"</span></span> <span class="token attr-name">content</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>A simple HTML5 Template for new projects.<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>meta</span> <span class="token attr-name">property</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>og:image<span class="token punctuation">"</span></span> <span class="token attr-name">content</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>image.png<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>

  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>link</span> <span class="token attr-name">rel</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>icon<span class="token punctuation">"</span></span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>/favicon.ico<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>link</span> <span class="token attr-name">rel</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>icon<span class="token punctuation">"</span></span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>/favicon.svg<span class="token punctuation">"</span></span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>image/svg+xml<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>link</span> <span class="token attr-name">rel</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>apple-touch-icon<span class="token punctuation">"</span></span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>/apple-touch-icon.png<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>

  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>link</span> <span class="token attr-name">rel</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>stylesheet<span class="token punctuation">"</span></span> <span class="token attr-name">href</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>css/styles.css?v=1.0<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>

<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>head</span><span class="token punctuation">></span></span>

<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>body</span><span class="token punctuation">></span></span>
  <span class="token comment">&lt;!-- your content here... --></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>script</span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>js/scripts.js<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token script"></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>script</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>body</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>html</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Hoxe podes soltar este modelo HTML5 sinxelo e listo para usar en calquera proxecto. Partindo diso, podes engadir o contido que queiras entre as etiquetas <code v-pre>&lt;body&gt;</code>e <code v-pre>&lt;/body&gt;</code>.</p>
<h2 id="proximos-pasos" tabindex="-1"><a class="header-anchor" href="#proximos-pasos" aria-hidden="true">#</a> Próximos pasos</h2>
<p>Unha boa forma de levar os teus deseños web ao seguinte nivel é con <em><a href="https://www.sitepoint.com/premium/books/the-principles-of-beautiful-web-design-4th-edition/?utm_source=blog&amp;utm_medium=articles" target="_blank" rel="noopener noreferrer">The Principles of Beautiful Web Design, 4th Edition<ExternalLinkIcon/></a></em> . Este libro ensinarache os principios do deseño <em>e</em> amosarache como implementalos na web. Foi completamente reescrito en setembro de 2020 e inclúe técnicas de vangarda das que non liches en ningún outro lugar.</p>
<p>Para mellorar os teus coñecementos de CSS, o noso currículo de <a href="https://www.sitepoint.com/master-modern-css-projects/" target="_blank" rel="noopener noreferrer">proxectos CSS modernos<ExternalLinkIcon/></a> axudarache a dominar as últimas edicións avanzadas de CSS3.</p>
<p>Máis aló dese punto, pode levar o desenvolvemento do seu sitio web ou aplicación web ao seguinte nivel con interactividade e interfaces de usuario programáticas e reactivas. Consulte os amplos recursos de SitePoint sobre <a href="https://www.sitepoint.com/javascript/" target="_blank" rel="noopener noreferrer">JavaScript<ExternalLinkIcon/></a> e <a href="https://www.sitepoint.com/javascript/react/" target="_blank" rel="noopener noreferrer">React<ExternalLinkIcon/></a> , por exemplo. E descubre como <a href="https://www.sitepoint.com/start-new-projects-faster/" target="_blank" rel="noopener noreferrer">comezar novos proxectos máis rápido<ExternalLinkIcon/></a> coa nosa guía das mellores ferramentas e bibliotecas web de andamios. Alternativamente, se queres crear experiencias web sen aprender a codificar, le o noso manual sobre o <a href="https://www.sitepoint.com/the-rise-of-the-no-code-movement/" target="_blank" rel="noopener noreferrer">movemento sen código<ExternalLinkIcon/></a> . As últimas ferramentas sen código cambiaron o xogo. Por primeira vez, son o suficientemente potentes como para ofrecer unha alternativa seria á codificación en moitas situacións.</p>
<hr>
<p>_ref:
<a href="https://www.sitepoint.com/a-basic-html5-template/" target="_blank" rel="noopener noreferrer">https://www.sitepoint.com/a-basic-html5-template/<ExternalLinkIcon/></a></p>
</div></template>


