export const data = JSON.parse("{\"key\":\"v-0b3c854c\",\"path\":\"/uf1841/Fases%20do%20Deseno%20Web.html\",\"title\":\"Fases do Deseño Web\",\"lang\":\"en-US\",\"frontmatter\":{\"description\":\"Fases do Deseño Web Todo proxecto, independentemente da súa complexidade ou do sector ao que pertenza, desenvólvese a través dunha serie de etapas. Ter ben definidas cada unha das fases do deseño web pode axudarnos a ofrecer ao cliente exactamente o que quere e necesita.\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://ambosass.com/megaboot/uf1841/Fases%20do%20Deseno%20Web.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"DAW\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Fases do Deseño Web\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Fases do Deseño Web Todo proxecto, independentemente da súa complexidade ou do sector ao que pertenza, desenvólvese a través dunha serie de etapas. Ter ben definidas cada unha das fases do deseño web pode axudarnos a ofrecer ao cliente exactamente o que quere e necesita.\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Fases do Deseño Web\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Que é o deseño web?\",\"slug\":\"que-e-o-deseno-web\",\"link\":\"#que-e-o-deseno-web\",\"children\":[]},{\"level\":2,\"title\":\"Fases do deseño web\",\"slug\":\"fases-do-deseno-web-1\",\"link\":\"#fases-do-deseno-web-1\",\"children\":[{\"level\":3,\"title\":\"Fase 1: Briefing\",\"slug\":\"fase-1-briefing\",\"link\":\"#fase-1-briefing\",\"children\":[]},{\"level\":3,\"title\":\"Fase 2: Planificación\",\"slug\":\"fase-2-planificacion\",\"link\":\"#fase-2-planificacion\",\"children\":[]},{\"level\":3,\"title\":\"Fase 3: Deseño\",\"slug\":\"fase-3-deseno\",\"link\":\"#fase-3-deseno\",\"children\":[]},{\"level\":3,\"title\":\"Fase 4: Desenvolvemento\",\"slug\":\"fase-4-desenvolvemento\",\"link\":\"#fase-4-desenvolvemento\",\"children\":[]},{\"level\":3,\"title\":\"Fase 5: Publicación\",\"slug\":\"fase-5-publicacion\",\"link\":\"#fase-5-publicacion\",\"children\":[]},{\"level\":3,\"title\":\"Fase 6: Mantemento\",\"slug\":\"fase-6-mantemento\",\"link\":\"#fase-6-mantemento\",\"children\":[]}]}],\"readingTime\":{\"minutes\":4.55,\"words\":1364},\"filePathRelative\":\"uf1841/Fases do Deseno Web.md\",\"excerpt\":\"<h1> Fases do Deseño Web</h1>\\n<p>Todo proxecto, independentemente da súa complexidade ou do sector ao que pertenza, desenvólvese a través dunha serie de etapas. Ter <strong>ben definidas cada unha das fases do deseño web pode axudarnos a ofrecer ao cliente exactamente o que quere</strong> e necesita.</p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
