export const data = JSON.parse("{\"key\":\"v-3eaacb82\",\"path\":\"/uf1841/Ferramentas-do-Desenvolvedor.html\",\"title\":\"Desenvolvemento Web: Como usar as Ferramentas de Desenvolvedor do Navegador\",\"lang\":\"en-US\",\"frontmatter\":{\"description\":\"Desenvolvemento Web: Como usar as Ferramentas de Desenvolvedor do Navegador As ferramentas para desenvolvedores do navegador, ou só \\\"ferramentas de desenvolvemento\\\", son de inmensa axuda para calquera desenvolvedor front-end, sexa principiante ou experto.\"},\"headers\":[{\"level\":3,\"title\":\"1. Fai clic co botón dereito para inspeccionar a páxina.\",\"slug\":\"_1-fai-clic-co-boton-dereito-para-inspeccionar-a-paxina\",\"link\":\"#_1-fai-clic-co-boton-dereito-para-inspeccionar-a-paxina\",\"children\":[]},{\"level\":3,\"title\":\"2. Abrirase a xanela de Chrome DevTools.\",\"slug\":\"_2-abrirase-a-xanela-de-chrome-devtools\",\"link\":\"#_2-abrirase-a-xanela-de-chrome-devtools\",\"children\":[]},{\"level\":3,\"title\":\"3. Fai clic en cada pestana para acceder ás ferramentas.\",\"slug\":\"_3-fai-clic-en-cada-pestana-para-acceder-as-ferramentas\",\"link\":\"#_3-fai-clic-en-cada-pestana-para-acceder-as-ferramentas\",\"children\":[]},{\"level\":3,\"title\":\"\",\"slug\":\"\",\"link\":\"#\",\"children\":[]},{\"level\":3,\"title\":\"Proba o teu deseño con Mobile Chrome Developer Tools.\",\"slug\":\"proba-o-teu-deseno-con-mobile-chrome-developer-tools\",\"link\":\"#proba-o-teu-deseno-con-mobile-chrome-developer-tools\",\"children\":[]},{\"level\":3,\"title\":\"Mide e optimiza a velocidade do teu sitio.\",\"slug\":\"mide-e-optimiza-a-velocidade-do-teu-sitio\",\"link\":\"#mide-e-optimiza-a-velocidade-do-teu-sitio\",\"children\":[]},{\"level\":3,\"title\":\"Previsualiza os cambios de deseño.\",\"slug\":\"previsualiza-os-cambios-de-deseno\",\"link\":\"#previsualiza-os-cambios-de-deseno\",\"children\":[]},{\"level\":3,\"title\":\"Realizar unha auditoría de SEO.\",\"slug\":\"realizar-unha-auditoria-de-seo\",\"link\":\"#realizar-unha-auditoria-de-seo\",\"children\":[]},{\"level\":3,\"title\":\"Monitoriza as túas solicitudes de Google Analytics.\",\"slug\":\"monitoriza-as-tuas-solicitudes-de-google-analytics\",\"link\":\"#monitoriza-as-tuas-solicitudes-de-google-analytics\",\"children\":[]},{\"level\":3,\"title\":\"Fluxo de traballo\",\"slug\":\"fluxo-de-traballo\",\"link\":\"#fluxo-de-traballo\",\"children\":[]},{\"level\":3,\"title\":\"Conclusión\",\"slug\":\"conclusion\",\"link\":\"#conclusion\",\"children\":[]}],\"readingTime\":{\"minutes\":10.67,\"words\":3201},\"filePathRelative\":\"uf1841/Ferramentas-do-Desenvolvedor.md\",\"excerpt\":\"<!-- ---\\nmarp: true\\n--- -->\\n<h1> Desenvolvemento Web: Como usar as Ferramentas de Desenvolvedor do Navegador</h1>\\n<hr>\\n<p>As ferramentas para desenvolvedores do navegador, ou só \\\"ferramentas de desenvolvemento\\\", son de inmensa axuda para calquera desenvolvedor front-end, sexa principiante ou experto.</p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
