export const data = JSON.parse("{\"key\":\"v-481994c1\",\"path\":\"/uf1841/\",\"title\":\"Elaboración de documentos web mediante linguaxes de marcas.\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"Elaboración de documentos web mediante linguaxes de marcas.\",\"index\":true,\"icon\":\"discover\",\"category\":[\"Guide\"],\"tag\":[\"entorna cliente\",\"html\",\"css\",\"javascript\"],\"description\":\"Elaboración de documentos web mediante linguaxes de marcas. Introdución Linguaxes de programación Ferramentas do lado cliente Navegadores Ferramentas do Desenvolvedor Editores de código HTML con VSCode Emmet Fases do deseño web Creación de paxinas web accesibles HTML Elementos Wireframes Deseño/Estrutura/Optimización Imaxes e elementos multimedia\"},\"headers\":[{\"level\":2,\"title\":\"Elaboración de documentos web mediante linguaxes de marcas.\",\"slug\":\"elaboracion-de-documentos-web-mediante-linguaxes-de-marcas\",\"link\":\"#elaboracion-de-documentos-web-mediante-linguaxes-de-marcas\",\"children\":[]}],\"readingTime\":{\"minutes\":0.4,\"words\":121},\"filePathRelative\":\"uf1841/README.md\",\"excerpt\":\"<!-- ## UF1841 -->\\n<h2> Elaboración de documentos web mediante linguaxes de marcas.</h2>\\n<ul>\\n<li><a href=\\\"/uf1841/00-introducion.html\\\" target=\\\"blank\\\">Introdución</a></li>\\n<li><a href=\\\"/uf1841/01-linguaxes-de-programacion.html\\\" target=\\\"blank\\\">Linguaxes de programación</a></li>\\n<li><a href=\\\"/uf1841/ferramentas-do-lado-do-cliente.html\\\" target=\\\"blank\\\">Ferramentas do lado cliente</a>\\n<ul>\\n<li><a href=\\\"/uf1841/axii-Navegadores.html\\\" target=\\\"blank\\\">Navegadores</a>\\n<ul>\\n<li><a href=\\\"/uf1841/Ferramentas-do-Desenvolvedor.html\\\" target=\\\"blank\\\">Ferramentas do Desenvolvedor</a></li>\\n</ul>\\n</li>\\n<li><a href=\\\"/uf1841/axi-Editores-de-codigo.html\\\" target=\\\"blank\\\">Editores de código</a></li>\\n<li><a href=\\\"/uf1841/axvii-HTML-con-VSCode.html\\\" target=\\\"blank\\\">HTML con VSCode</a></li>\\n<li><a href=\\\"/uf1841/axv-Emmet-exemplos.html\\\" target=\\\"blank\\\">Emmet</a></li>\\n</ul>\\n</li>\\n<li><a href=\\\"/uf1841/Fases-do-Deseno-Web.html\\\" target=\\\"blank\\\">Fases do deseño web</a></li>\\n<li><a href=\\\"/uf1841/03-creacion-de-paxinas-web-accesibles.html\\\" target=\\\"blank\\\">Creación de paxinas web accesibles</a></li>\\n<li><a href=\\\"/uf1841/04-HTML5.html\\\" target=\\\"blank\\\">HTML</a>\\n<ul>\\n<li><a href=\\\"/uf1841/axi-Elementos-HTML5.html\\\" target=\\\"blank\\\">Elementos</a></li>\\n</ul>\\n</li>\\n<li><a href=\\\"/uf1841/axvi-wireframes.html\\\" target=\\\"blank\\\">Wireframes</a></li>\\n<li><a href=\\\"/uf1841/Deseno-estrutura-optimizacion-contidos.html\\\" target=\\\"blank\\\">Deseño/Estrutura/Optimización</a></li>\\n<li><a href=\\\"/uf1841/Imaxes-e-elementos-multimedia.html\\\" target=\\\"blank\\\">Imaxes e elementos multimedia</a></li>\\n</ul>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
