export const data = JSON.parse("{\"key\":\"v-1892d1a1\",\"path\":\"/uf1841/Navegadores.html\",\"title\":\"Navegadores\",\"lang\":\"en-US\",\"frontmatter\":{\"marp\":true,\"description\":\"Navegadores Internet é unha rede xigante que conecta miles de ordenadores en todo o mundo. E, permítenos acceder e compartir información con persoas de todo o mundo en segundos. Probablemente utilizaches Internet para visitar sitios web, ver vídeos, enviar correos electrónicos, escoitar música ou xogar.\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://ambosass.com/megaboot/uf1841/Navegadores.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"DAW\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Navegadores\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Navegadores Internet é unha rede xigante que conecta miles de ordenadores en todo o mundo. E, permítenos acceder e compartir información con persoas de todo o mundo en segundos. Probablemente utilizaches Internet para visitar sitios web, ver vídeos, enviar correos electrónicos, escoitar música ou xogar.\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://ambosass.com/megaboot/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Navegadores\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Navegadores\\\",\\\"image\\\":[\\\"https://ambosass.com/megaboot/\\\"],\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":2,\"title\":\"World Wide Web\",\"slug\":\"world-wide-web\",\"link\":\"#world-wide-web\",\"children\":[{\"level\":3,\"title\":\"Navegadores web\",\"slug\":\"navegadores-web\",\"link\":\"#navegadores-web\",\"children\":[]},{\"level\":3,\"title\":\"Servidores web\",\"slug\":\"servidores-web\",\"link\":\"#servidores-web\",\"children\":[]},{\"level\":3,\"title\":\"Enderezos web\",\"slug\":\"enderezos-web\",\"link\":\"#enderezos-web\",\"children\":[]},{\"level\":3,\"title\":\"Páxinas web\",\"slug\":\"paxinas-web\",\"link\":\"#paxinas-web\",\"children\":[]}]}],\"readingTime\":{\"minutes\":3.6,\"words\":1079},\"filePathRelative\":\"uf1841/Navegadores.md\",\"excerpt\":\"<h1> Navegadores</h1>\\n<hr>\\n<p>Internet é unha rede xigante que conecta miles de ordenadores en todo o mundo. E, permítenos acceder e compartir información con persoas de todo o mundo en segundos.</p>\\n<hr>\\n<p>Probablemente utilizaches Internet para visitar sitios web, ver vídeos, enviar correos electrónicos, escoitar música ou xogar.</p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
