export const data = JSON.parse("{\"key\":\"v-4b8eaf76\",\"path\":\"/uf1841/Que-e-unha-paxina-web-Tipos.html\",\"title\":\"\",\"lang\":\"en-US\",\"frontmatter\":{\"description\":\"Que é unha páxina web? Unha páxina web é un documento creado - ou compilado- en formato HTML (HyperText Markup Language ou linguaxe de marcado de hipertexto). Unha linguaxe adaptada á World Wide Web (WWW) e ao que se accede ao navegar nunha web. A agrupación de varias páxinas web enlazadas baixo un mesmo dominio se denomina sitio web.\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://ambosass.com/megaboot/uf1841/Que-e-unha-paxina-web-Tipos.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"DAW\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Que é unha páxina web? Unha páxina web é un documento creado - ou compilado- en formato HTML (HyperText Markup Language ou linguaxe de marcado de hipertexto). Unha linguaxe adaptada á World Wide Web (WWW) e ao que se accede ao navegar nunha web. A agrupación de varias páxinas web enlazadas baixo un mesmo dominio se denomina sitio web.\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Que é unha páxina web?\",\"slug\":\"que-e-unha-paxina-web\",\"link\":\"#que-e-unha-paxina-web\",\"children\":[]},{\"level\":2,\"title\":\"Tipos de páxinas web segundo a súa funcionalidade e constitución\",\"slug\":\"tipos-de-paxinas-web-segundo-a-sua-funcionalidade-e-constitucion\",\"link\":\"#tipos-de-paxinas-web-segundo-a-sua-funcionalidade-e-constitucion\",\"children\":[{\"level\":3,\"title\":\"Páxinas web estáticas\",\"slug\":\"paxinas-web-estaticas\",\"link\":\"#paxinas-web-estaticas\",\"children\":[]},{\"level\":3,\"title\":\"Páxinas web dinámicas\",\"slug\":\"paxinas-web-dinamicas\",\"link\":\"#paxinas-web-dinamicas\",\"children\":[]}]}],\"readingTime\":{\"minutes\":4.28,\"words\":1284},\"filePathRelative\":\"uf1841/Que-e-unha-paxina-web-Tipos.md\",\"excerpt\":\"<h2> Que é unha páxina web?</h2>\\n<p>Unha páxina web é un documento creado - ou compilado- en formato HTML (<em>HyperText Markup Language</em> ou linguaxe de marcado de hipertexto). Unha linguaxe adaptada á World Wide Web (WWW) e ao que se accede ao navegar nunha web.</p>\\n<p>A agrupación de varias páxinas web enlazadas baixo un mesmo dominio se denomina sitio web.</p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
