export const data = JSON.parse("{\"key\":\"v-6b6c9cba\",\"path\":\"/uf1841/UF1841.html\",\"title\":\"UF1841\",\"lang\":\"en-US\",\"frontmatter\":{\"description\":\"UF1841 Elaboración de documentos web mediante linguaxes de marca 60h UD1. DESEÑO WEB Principios de deseño web. O proceso de deseño web.\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://ambosass.com/megaboot/uf1841/UF1841.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"DAW\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"UF1841\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"UF1841 Elaboración de documentos web mediante linguaxes de marca 60h UD1. DESEÑO WEB Principios de deseño web. O proceso de deseño web.\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"UF1841\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":3,\"title\":\"Elaboración de documentos web mediante linguaxes de marca 60h\",\"slug\":\"elaboracion-de-documentos-web-mediante-linguaxes-de-marca-60h\",\"link\":\"#elaboracion-de-documentos-web-mediante-linguaxes-de-marca-60h\",\"children\":[]},{\"level\":3,\"title\":\"UD1. DESEÑO WEB\",\"slug\":\"ud1-deseno-web\",\"link\":\"#ud1-deseno-web\",\"children\":[]},{\"level\":3,\"title\":\"UD2. LINGUAXES DE MARCADO\",\"slug\":\"ud2-linguaxes-de-marcado\",\"link\":\"#ud2-linguaxes-de-marcado\",\"children\":[]},{\"level\":3,\"title\":\"UD 3. LINGUAXES DE MARCADO PARA CREACIÓN DE PÁXINAS WEB\",\"slug\":\"ud-3-linguaxes-de-marcado-para-creacion-de-paxinas-web\",\"link\":\"#ud-3-linguaxes-de-marcado-para-creacion-de-paxinas-web\",\"children\":[]},{\"level\":3,\"title\":\"UD 4. FOLLAS DE ESTILO\",\"slug\":\"ud-4-follas-de-estilo\",\"link\":\"#ud-4-follas-de-estilo\",\"children\":[]},{\"level\":3,\"title\":\"GLOSARIO WEB\",\"slug\":\"glosario-web\",\"link\":\"#glosario-web\",\"children\":[]}],\"readingTime\":{\"minutes\":1.66,\"words\":498},\"filePathRelative\":\"uf1841/UF1841.md\",\"excerpt\":\"<h1> UF1841</h1>\\n<h3> Elaboración de documentos web mediante linguaxes de marca 60h</h3>\\n<!-- ### 02/01/23-18/01/23 -->\\n<h3> UD1. DESEÑO WEB</h3>\\n<ol>\\n<li><a href=\\\"https://cxl.com/blog/universal-web-design-principles/\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">Principios de deseño web</a>.</li>\\n<li><a href=\\\"https://www.newdesigngroup.ca/website-design/web-design-process-infographic/\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">O proceso de deseño web</a>.</li>\\n</ol>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
