<template><div><h1 id="unha-guia-completa-para-principiantes-de-git" tabindex="-1"><a class="header-anchor" href="#unha-guia-completa-para-principiantes-de-git" aria-hidden="true">#</a> Unha guía completa para principiantes de Git</h1>
<p><a href="https://dev.to/t/beginners" target="_blank" rel="noopener noreferrer"># principiantes<ExternalLinkIcon/></a> <a href="https://dev.to/t/tutorial" target="_blank" rel="noopener noreferrer"># titorial<ExternalLinkIcon/></a> <a href="https://dev.to/t/productivity" target="_blank" rel="noopener noreferrer"># produtividade<ExternalLinkIcon/></a> <a href="https://dev.to/t/git" target="_blank" rel="noopener noreferrer"># git<ExternalLinkIcon/></a></p>
<p>Imos revisar unha interesante ferramenta:</p>
<ul>
<li>
<p>que é compatible con todos os sistemas operativos que se  empregan nestes días,</p>
</li>
<li>
<p>que permite a usuarios de todo o mundo realizar operacións nun proxecto de xeito remoto,</p>
</li>
<li>
<p>é lixeira, segura e fiable (a lista continúa )</p>
<p>pero, semella que resulta algo difícil de comprender. Falamos de **Git</p>
</li>
</ul>
<figure><a href="https://res.cloudinary.com/practicaldev/image/fetch/s--n6W9zrpD--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/ibup0b2uyveisalcmczs.png" target="_blank" rel="noopener noreferrer"><img src="https://res.cloudinary.com/practicaldev/image/fetch/s--n6W9zrpD--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/ibup0b2uyveisalcmczs.png" alt="imaxe" tabindex="0" loading="lazy"><ExternalLinkIcon/></a><figcaption>imaxe</figcaption></figure>
<h2 id="p-que-e-iso-de-git" tabindex="-1"><a class="header-anchor" href="#p-que-e-iso-de-git" aria-hidden="true">#</a> P) Que é iso de Git?</h2>
<p>Git é un sistema de control de versións distribuído (VCS) de código aberto e gratuíto.</p>
<p>E, un sistema de control de versións é un sistema que se ocupa de rastrexar os cambios ao longo do tempo nos nosos arquivos de proxecto. Permítenos ir gravando os cambios do proxecto e volver a calquera versión específica dos arquivos rastrexados, en calquera momento. Asemade permite o traballo colaborativo deixando que moitas persoas poidan traballar de forma eficiente xuntos e colaborar en proxectos en equipo, onde cada desenvolvedor pode ter a súa propia versión do proxecto, distribuída no seu ordenador. Máis tarde, estas versións individuais do proxecto pódense combinar e adaptar á versión principal do proxecto.</p>
<p>Basicamente, é unha ferramenta moi popular para coordinar o traballo paralelo e xestionar proxectos entre individuos e equipos. Nin que dicir ten que saber usar Git é unha das habilidades máis importantes para calquera desenvolvedor hoxe en día e definitivamente é un bo complemento para o teu currículo.</p>
<h2 id="q-como-configuro-git" tabindex="-1"><a class="header-anchor" href="#q-como-configuro-git" aria-hidden="true">#</a> Q) Como configuro Git?</h2>
<p>Acceda á ligazón de descarga anterior para o seu sistema operativo específico e logo siga o asistente de instalación para configurar as cousas no seu ordenador.</p>
<p>Voila! , tes Git instalado.
Agora é hora de tartar o teu terminal. Escribe o seguinte comando para verificar que Git estea listo para usarse no teu ordenador:</p>
<figure><a href="https://res.cloudinary.com/practicaldev/image/fetch/s--DVin4GXa--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/dqinyayi5y3e16xko8w4.png" target="_blank" rel="noopener noreferrer"><img src="https://res.cloudinary.com/practicaldev/image/fetch/s--DVin4GXa--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/dqinyayi5y3e16xko8w4.png" alt="carbono" tabindex="0" loading="lazy"><ExternalLinkIcon/></a><figcaption>carbono</figcaption></figure>
<p>Se todo saíu ben durante o proceso, debería devolver a versión de Git instalada no seu computador.</p>
<p>Nota:
Se es usuario de Mac ou Linux, podes utilizar o terminal Bash predeterminado que vén preinstalado na túa máquina.</p>
<p>Se usa Windows, pode usar o seu terminal Powershell integrado ou o terminal Git Bash incluído coa instalación de Git</p>
<h2 id="seguinte-paso-configura-git-co-teu-nome-e-correo-electronico" tabindex="-1"><a class="header-anchor" href="#seguinte-paso-configura-git-co-teu-nome-e-correo-electronico" aria-hidden="true">#</a> Seguinte paso: configura Git co teu nome e correo electrónico</h2>
<p>No seu terminal, execute os seguintes comandos para identificarse con Git, substitúa os valores dentro das comiñas co nome de usuario e enderezo de correo electrónico desexados.</p>
<figure><a href="https://res.cloudinary.com/practicaldev/image/fetch/s--Spec4yMg--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/zf0szl0t3xlkwa1krte9.png" target="_blank" rel="noopener noreferrer"><img src="https://res.cloudinary.com/practicaldev/image/fetch/s--Spec4yMg--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/zf0szl0t3xlkwa1krte9.png" alt="carbono (1)" tabindex="0" loading="lazy"><ExternalLinkIcon/></a><figcaption>carbono (1)</figcaption></figure>
<h2 id="repositorios" tabindex="-1"><a class="header-anchor" href="#repositorios" aria-hidden="true">#</a> Repositorios</h2>
<p>Ao traballar con Git, é importante estar familiarizado co termo repositorio. Un repositorio Git é un contedor para un proxecto que é seguido por Git.</p>
<p>Podemos distinguir dous tipos principais de repositorios Git:</p>
<p><strong>Repositorio local</strong> : un repositorio illado almacenado no seu propio computador, onde pode traballar na versión local do seu proxecto.
Repositorio remoto: normalmente almacénase fóra do seu sistema local illado, normalmente nun servidor remoto. É especialmente útil cando se traballa en equipo: este é o lugar onde pode compartir o código do seu proxecto, ver o código doutras persoas e integralo na súa versión local do proxecto e tamén empuxar os seus cambios ao repositorio remoto.
Neste artigo, só cubriremos os repositorios locais.</p>
<h2 id="inicializacion-dun-repositorio" tabindex="-1"><a class="header-anchor" href="#inicializacion-dun-repositorio" aria-hidden="true">#</a> Inicialización dun repositorio</h2>
<p>Agora que sabemos dos repositorios, creamos un. Para crear un novo repositorio e comezar a rastrexar o seu proxecto con Git, use o software do seu terminal e navegue ata o cartafol principal do seu proxecto e logo escriba o seguinte comando:</p>
<figure><a href="https://res.cloudinary.com/practicaldev/image/fetch/s--lIThTqPI--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/xaff84fjto45y4v0ynn0.png" target="_blank" rel="noopener noreferrer"><img src="https://res.cloudinary.com/practicaldev/image/fetch/s--lIThTqPI--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/xaff84fjto45y4v0ynn0.png" alt="1" tabindex="0" loading="lazy"><ExternalLinkIcon/></a><figcaption>1</figcaption></figure>
<p>Este comando xerará un directorio .git oculto para o seu proxecto creado por Git, onde se gardan todos os datos de seguimento internos do repositorio actual.</p>
<h2 id="comprobacion-do-estado" tabindex="-1"><a class="header-anchor" href="#comprobacion-do-estado" aria-hidden="true">#</a> Comprobación do estado</h2>
<p>Agora que inicializamos o noso repositorio, falemos do estado git. Mentres estamos dentro da carpeta do proxecto no noso terminal, podemos escribir o seguinte comando para comprobar o estado do noso repositorio:</p>
<figure><a href="https://res.cloudinary.com/practicaldev/image/fetch/s--uZk9rcgK--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/rp740sawordwifboabyh.png" target="_blank" rel="noopener noreferrer"><img src="https://res.cloudinary.com/practicaldev/image/fetch/s--uZk9rcgK--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/rp740sawordwifboabyh.png" alt="g2" tabindex="0" loading="lazy"><ExternalLinkIcon/></a><figcaption>g2</figcaption></figure>
<p>Así comproba o estado actual do seu repositorio. Este é un comando que se usa a miúdo cando se traballa con Git. Móstranos que arquivos se cambiaron, que arquivos se seguen, etc.</p>
<h2 id="etapa-e-confirmacion-de-codigo" tabindex="-1"><a class="header-anchor" href="#etapa-e-confirmacion-de-codigo" aria-hidden="true">#</a> Etapa e confirmación de código</h2>
<p>O compromiso é o proceso no que os cambios se engaden &quot;oficialmente&quot; ao repositorio Git.</p>
<p>En Git, podemos considerar que as confirmacións son puntos de control ou instantáneas do seu proxecto no seu estado actual. Noutras palabras, gardamos basicamente a versión actual do noso código nun commit. Podemos crear tantas confirmacións como necesitemos no historial de confirmacións e podemos ir adiante e atrás entre as confirmacións para ver as diferentes revisións do código do noso proxecto. Iso permítenos xestionar de xeito eficiente o noso progreso e rastrexar o proxecto a medida que se vai desenvolvendo.</p>
<p>As confirmacións normalmente créanse en puntos lóxicos a medida que desenvolvemos o noso proxecto, normalmente despois de engadir contidos específicos, funcións ou modificacións (como novas funcionalidades ou corrección de erros).</p>
<h2 id="arquivos-de-proba" tabindex="-1"><a class="header-anchor" href="#arquivos-de-proba" aria-hidden="true">#</a> Arquivos de proba</h2>
<p>Dende o cartafol do proxecto, podemos usar o comando git add para engadir os nosos arquivos á área intermedia, o que permite que se faga un seguimento deles.</p>
<p>Podemos engadir un arquivo específico á área de proba co seguinte comando:</p>
<figure><a href="https://res.cloudinary.com/practicaldev/image/fetch/s--eO7KSYTW--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/zvk6jlmrzttn7ryoqbng.png" target="_blank" rel="noopener noreferrer"><img src="https://res.cloudinary.com/practicaldev/image/fetch/s--eO7KSYTW--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/zvk6jlmrzttn7ryoqbng.png" alt="carbono (3)" tabindex="0" loading="lazy"><ExternalLinkIcon/></a><figcaption>carbono (3)</figcaption></figure>
<p>Para engadir varios arquivos:</p>
<figure><a href="https://res.cloudinary.com/practicaldev/image/fetch/s--7ffL6BQJ--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/2euga1m6yvys8vavutai.png" target="_blank" rel="noopener noreferrer"><img src="https://res.cloudinary.com/practicaldev/image/fetch/s--7ffL6BQJ--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/2euga1m6yvys8vavutai.png" alt="carbono (4)" tabindex="0" loading="lazy"><ExternalLinkIcon/></a><figcaption>carbono (4)</figcaption></figure>
<p>En lugar de ter que engadir os arquivos individualmente, podemos engadir todos os arquivos necesarios dentro do cartafol do proxecto á área intermedia usando o comando:</p>
<figure><a href="https://res.cloudinary.com/practicaldev/image/fetch/s--DlcTvbQE--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/r8g5xolj89p042quodmr.png" target="_blank" rel="noopener noreferrer"><img src="https://res.cloudinary.com/practicaldev/image/fetch/s--DlcTvbQE--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/r8g5xolj89p042quodmr.png" alt="carbono (5)" tabindex="0" loading="lazy"><ExternalLinkIcon/></a><figcaption>carbono (5)</figcaption></figure>
<p>De xeito predeterminado, isto engade todos os arquivos e cartafoles dentro do cartafol do proxecto á área intermedia, desde onde están listos para ser comprometidos e rastrexados.</p>
<h2 id="facendo-commit" tabindex="-1"><a class="header-anchor" href="#facendo-commit" aria-hidden="true">#</a> Facendo <em>commit</em></h2>
<p>Un commit é unha instantánea do noso código nun momento concreto, que gardamos no historial de commit do noso repositorio. Despois de engadir todos os arquivos que queremos rastrexar á área de proba co comando git add, estamos preparados para facer un commit.</p>
<p>Para confirmar os arquivos desde a área intermedia, empregamos o seguinte comando:</p>
<figure><a href="https://res.cloudinary.com/practicaldev/image/fetch/s--lcHAejyx--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/6bcr44x2meqlmm6y1fcm.png" target="_blank" rel="noopener noreferrer"><img src="https://res.cloudinary.com/practicaldev/image/fetch/s--lcHAejyx--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/6bcr44x2meqlmm6y1fcm.png" alt="carbono" tabindex="0" loading="lazy"><ExternalLinkIcon/></a><figcaption>carbono</figcaption></figure>
<p>Podemos escribir unha mensaxe de confirmación dentro das comiñas que se usa para identificala no historial de confirmacións.</p>
<p>A mensaxe de confirmación debe ser un resumo descritivo dos cambios que está a facer no repositorio.</p>
<p>Despois de executar ese comando, obterás os detalles técnicos sobre o <em>commit</em> impreso no terminal.
E iso é basicamente!, fixeches un <em>commit</em> no teu proxecto. 🎉 agora se escribimos git status deberiamos ver isto:</p>
<figure><a href="https://res.cloudinary.com/practicaldev/image/fetch/s--iBhDuNgJ--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/4rnyqd19w7f4scn1p0dr.jpg" target="_blank" rel="noopener noreferrer"><img src="https://res.cloudinary.com/practicaldev/image/fetch/s--iBhDuNgJ--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/4rnyqd19w7f4scn1p0dr.jpg" alt="9HHIf327i" tabindex="0" loading="lazy"><ExternalLinkIcon/></a><figcaption>9HHIf327i</figcaption></figure>
<p>Antes de poder cometer cambios no noso código, necesitamos decidir que arquivos ou que cambios colocaremos (engadir) dentro da área intermedia. e desde a área de posta en escena que comprometemos.</p>
<h2 id="historial-de-compromisos" tabindex="-1"><a class="header-anchor" href="#historial-de-compromisos" aria-hidden="true">#</a> Historial de compromisos</h2>
<p>Para ver todos os compromisos que se fixeron para o noso proxecto, usamos o seguinte comando:</p>
<figure><a href="https://res.cloudinary.com/practicaldev/image/fetch/s--ALZbrQBR--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/ebrmsccfr74wkq7qq3bk.png" target="_blank" rel="noopener noreferrer"><img src="https://res.cloudinary.com/practicaldev/image/fetch/s--ALZbrQBR--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/ebrmsccfr74wkq7qq3bk.png" alt="carbono (1)" tabindex="0" loading="lazy"><ExternalLinkIcon/></a><figcaption>carbono (1)</figcaption></figure>
<p>O comando git log amosará detalles de cada commit, como, nome do autor, hash xerado para commit, data e hora do commit e mensaxe de commit que fornecemos anteriormente.</p>
<p>Agora, digamos que fixemos algúns cambios no noso código (por exemplo, engadimos novas funcionalidades ou corrección de erros) e por algunha razón o noso código rompe e deixa de funcionar como se supón.</p>
<p>Git é aquí moi útil e por que aos grandes desenvolvedores de todo o mundo encántalles tanto.</p>
<p>Con Git podemos volver facilmente a unha versión segura do seu proxecto onde antes funcionaba o noso código:</p>
<figure><a href="https://res.cloudinary.com/practicaldev/image/fetch/s--A-xdqa9x--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/lfsw8c7rykglmtkbpwij.png" target="_blank" rel="noopener noreferrer"><img src="https://res.cloudinary.com/practicaldev/image/fetch/s--A-xdqa9x--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/lfsw8c7rykglmtkbpwij.png" alt="carbono (2)" tabindex="0" loading="lazy"><ExternalLinkIcon/></a><figcaption>carbono (2)</figcaption></figure>
<p>Agora Substitúe co hash real do commit específico que desexa visitar, que aparece co comando git log.</p>
<p>Para volver á última confirmación (a última versión do código do noso proxecto), pode escribir este comando:</p>
<p>git checkout master</p>
<h2 id="ignorando-arquivos" tabindex="-1"><a class="header-anchor" href="#ignorando-arquivos" aria-hidden="true">#</a> Ignorando arquivos</h2>
<p>Para ignorar os arquivos que non desexa que se rastrexe nin se engada á área <strong>intermedia</strong> , pode crear un arquivo chamado <strong>.gitignore</strong> no seu cartafol principal do proxecto.</p>
<p>Dentro do arquivo, pode listar o nome de todos os arquivos e cartafoles dos que non quere seguir (cada arquivo e cartafol ignorado debería ir a unha nova liña dentro do arquivo <strong>.gitignore</strong> ).</p>
<p>Para profundizar na ignoración de arquivos, podes consultar este artigo de GitHub: <a href="https://docs.github.com/en/github/using-git/ignoring-files" target="_blank" rel="noopener noreferrer">https://docs.github.com/en/github/using-git/ignoring-files<ExternalLinkIcon/></a></p>
<h2 id="polas" tabindex="-1"><a class="header-anchor" href="#polas" aria-hidden="true">#</a> Pólas</h2>
<p>Unha rama podería interpretarse como unha liña de tempo individual dos compromisos do noso proxecto.</p>
<p>Pénsao como no flash cando a baga vai a diferentes liñas de tempo alternativas da súa vida (pasado, presente e futuro!), Todas elas por separado, pero ao mesmo tempo</p>
<p>Con Git, podemos crear moitos destes ambientes alternativos (é dicir, podemos crear diferentes ramas) para que poidan existir outras versións do código do noso proxecto e seguirse en paralelo.</p>
<p>Esta función permítenos engadir novas funcións (experimentais, inacabadas e potencialmente erradas) en ramas separadas, sen tocar a versión estable &quot;oficial&quot; principal do noso código de proxecto (que normalmente se mantén na rama principal).</p>
<p>Cando inicializamos un repositorio e comezamos a facer confirmacións, gárdanse na rama principal por defecto.</p>
<h2 id="creando-unha-nova-rama" tabindex="-1"><a class="header-anchor" href="#creando-unha-nova-rama" aria-hidden="true">#</a> Creando unha nova rama</h2>
<p>Podes crear unha nova rama usando o seguinte comando:</p>
<figure><a href="https://res.cloudinary.com/practicaldev/image/fetch/s--t_ZELTbf--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/a49mbvrly5dqmyid916g.png" target="_blank" rel="noopener noreferrer"><img src="https://res.cloudinary.com/practicaldev/image/fetch/s--t_ZELTbf--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/a49mbvrly5dqmyid916g.png" alt="carbono (3)" tabindex="0" loading="lazy"><ExternalLinkIcon/></a><figcaption>carbono (3)</figcaption></figure>
<p>A nova rama que se crea será a referencia ao estado actual do seu repositorio.</p>
<p>É unha boa práctica crear unha rama de desenvolvemento onde podes traballar na mellora do teu código, engadindo novas funcións experimentais e todo similar. Despois de desenvolver e probar estas novas funcións para asegurarse de que non teñen erros e que se poden usar, pode combinalos coa rama principal.</p>
<h2 id="cambio-de-ramas" tabindex="-1"><a class="header-anchor" href="#cambio-de-ramas" aria-hidden="true">#</a> Cambio de ramas</h2>
<p>Para cambiar a unha rama diferente, usa o comando git switch:</p>
<figure><a href="https://res.cloudinary.com/practicaldev/image/fetch/s--UHuhwRIx--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/si1kd22jp36dkzqce4zl.png" target="_blank" rel="noopener noreferrer"><img src="https://res.cloudinary.com/practicaldev/image/fetch/s--UHuhwRIx--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/si1kd22jp36dkzqce4zl.png" alt="carbono (4)" tabindex="0" loading="lazy"><ExternalLinkIcon/></a><figcaption>carbono (4)</figcaption></figure>
<p>Con isto, pode cambiar a unha liña do tempo illada diferente do seu proxecto cambiando ramas.</p>
<p>Por exemplo, podería estar traballando en diferentes funcións do seu código e ter unha rama separada para cada función. Cando cambias a unha sucursal, podes facer cambios de código que só afecten a esa sucursal en particular. Despois, podes cambiar a outra rama para traballar noutra función, que non se verá afectada polos cambios e compromisos feitos desde a rama anterior.</p>
<p>Se a rama á que queremos cambiar non existe, entón o interruptor git comando creará unha nova rama e cambiará a ela ao mesmo tempo</p>
<h2 id="fusion-de-ramas" tabindex="-1"><a class="header-anchor" href="#fusion-de-ramas" aria-hidden="true">#</a> Fusión de ramas</h2>
<p>Aquí está a última parte do crebacabezas.</p>
<p>Digamos que creou unha nova rama separada da rama mestra do seu proxecto na que quere traballar. despois de ter completamente implementado e probado unha nova característica no seu código, desexa combinar eses cambios coa rama estable do seu proxecto (que normalmente é a rama mestra predeterminada).</p>
<p>Entón, como facelo, é doado. Para combinar os cambios dunha rama diferente coa súa rama actual, pode usar este comando:</p>
<figure><a href="https://res.cloudinary.com/practicaldev/image/fetch/s--oVujVjNZ--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/x145z9eiw7t4v5iw2v0g.png" target="_blank" rel="noopener noreferrer"><img src="https://res.cloudinary.com/practicaldev/image/fetch/s--oVujVjNZ--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/x145z9eiw7t4v5iw2v0g.png" alt="carbono (5)" tabindex="0" loading="lazy"><ExternalLinkIcon/></a><figcaption>carbono (5)</figcaption></figure>
<p>Só tes que substituír co nome da sucursal que desexa integrar na súa sucursal actual.</p>
<h2 id="eliminacion-dunha-sucursal" tabindex="-1"><a class="header-anchor" href="#eliminacion-dunha-sucursal" aria-hidden="true">#</a> Eliminación dunha sucursal</h2>
<p>Para eliminar unha rama, pode executar o comando git branch coa bandeira -d:</p>
<figure><a href="https://res.cloudinary.com/practicaldev/image/fetch/s--z9E2w45m--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/wf1zuw102c78pwr4t50x.png" target="_blank" rel="noopener noreferrer"><img src="https://res.cloudinary.com/practicaldev/image/fetch/s--z9E2w45m--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/wf1zuw102c78pwr4t50x.png" alt="carbono (6)" tabindex="0" loading="lazy"><ExternalLinkIcon/></a><figcaption>carbono (6)</figcaption></figure>
<h3 id="esta-ben-este-artigo-remata-aqui" tabindex="-1"><a class="header-anchor" href="#esta-ben-este-artigo-remata-aqui" aria-hidden="true">#</a> Está ben, este artigo remata aquí.</h3>
<p>Así é todo para este artigo, hai moito máis de Git do que non falamos (definitivamente farémolo ás veces máis tarde).</p>
<p>Deixándovos algúns recursos👇:</p>
<p>Documentación oficial de Git: <a href="https://git-scm.com/doc" target="_blank" rel="noopener noreferrer">https://git-scm.com/doc<ExternalLinkIcon/></a>
O libro gratuíto de Pro Git: <a href="https://git-scm.com/book/en/v2" target="_blank" rel="noopener noreferrer">https://git-scm.com/book/en/v2<ExternalLinkIcon/></a>
Máis información sobre GitHub: <a href="https://guides.github.com/" target="_blank" rel="noopener noreferrer">https://guides.github.com/<ExternalLinkIcon/></a>
Libro electrónico sobre como comezar con Git e GitHub (suxerido polo usuario Bobby Iliev): <a href="https://github.com/bobbyiliev/introduction-to-git-and-github-ebook" target="_blank" rel="noopener noreferrer">https://github.com/bobbyiliev/introduction-to-git-and-github-ebook<ExternalLinkIcon/></a></p>
<p>Paz</p>
<hr>
<p>ref.: <a href="https://dev.to/exwhyzed/how-to-git-a-complete-beginners-guide-1h85" target="_blank" rel="noopener noreferrer">https://dev.to/exwhyzed/how-to-git-a-complete-beginners-guide-1h85<ExternalLinkIcon/></a></p>
</div></template>


