export const data = JSON.parse("{\"key\":\"v-8daa1a0e\",\"path\":\"/\",\"title\":\"Home\",\"lang\":\"en-US\",\"frontmatter\":{\"home\":true,\"layout\":\"BlogHome\",\"icon\":\"home\",\"title\":\"Home\",\"heroImage\":\"/logo.svg\",\"heroText\":\"MEGA Bootcamp\",\"tagline\":\"Desenvolvemento de Aplicacións con Tecnoloxías Web\",\"heroFullScreen\":true,\"projects\":[{\"icon\":\"project\",\"name\":\"Deseño web na entorna cliente\",\"desc\":\"uf1841\",\"link\":\"/mod1/uf1841/\"},{\"icon\":\"link\",\"name\":\"Deseño web na entorna cliente\",\"desc\":\"uf1842\",\"link\":\"/mod1/uf1842/\"},{\"icon\":\"book\",\"name\":\"Deseño web na entorna cliente\",\"desc\":\"uf1843\",\"link\":\"/mod1/uf1843/\"},{\"icon\":\"article\",\"name\":\"Lecturas\",\"desc\":\"Lecturas complementarias\",\"link\":\"/posts/\"},{\"icon\":\"friend\",\"name\":\"Deseño web na entorna servidor\",\"desc\":\"uf1844\",\"link\":\"/mod2/uf1844/\"},{\"icon\":\"/logo.svg\",\"name\":\"Deseño web na entorna servidor\",\"desc\":\"uf1845\",\"link\":\"/mod2/uf1845/\"},{\"icon\":\"/logo.svg\",\"name\":\"Deseño web na entorna servidor\",\"desc\":\"uf1846\",\"link\":\"/mod2/uf1846/\"},{\"icon\":\"link\",\"name\":\"Enlaces de interese\",\"desc\":\"uf1846\",\"link\":\"intro\"}],\"footer\":\"mega bootcamp &copy; 2023 \\\\n i.bernárdez\",\"description\":\"This is a blog home page demo. To use this layout, you should set both layout: BlogHome and home: true in the page front matter. For related configuration docs, please see blog homepage.\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://ambosass.com/megaboot/\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"MEGA Bootcamp 2023\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Home\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"This is a blog home page demo. To use this layout, you should set both layout: BlogHome and home: true in the page front matter. For related configuration docs, please see blog homepage.\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"website\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"WebPage\\\",\\\"name\\\":\\\"Home\\\",\\\"description\\\":\\\"This is a blog home page demo. To use this layout, you should set both layout: BlogHome and home: true in the page front matter. For related configuration docs, please see blog homepage.\\\"}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":0.56,\"words\":167},\"filePathRelative\":\"README.md\",\"excerpt\":\"<p>This is a blog home page demo.</p>\\n<p>To use this layout, you should set both <code>layout: BlogHome</code> and <code>home: true</code> in the page front matter.</p>\\n<p>For related configuration docs, please see <a href=\\\"https://theme-hope.vuejs.vuepress/guide/blog/home/\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">blog homepage</a>.</p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
