<template><div><h1 id="que-ferramentas-necesito-para-comezar-no-desenvolvemento-web-🤔" tabindex="-1"><a class="header-anchor" href="#que-ferramentas-necesito-para-comezar-no-desenvolvemento-web-🤔" aria-hidden="true">#</a> Que ferramentas necesito para comezar no desenvolvemento web? 🤔</h1>
<h2 id="editor-es-de-codigo" tabindex="-1"><a class="header-anchor" href="#editor-es-de-codigo" aria-hidden="true">#</a> Editor(es) de código</h2>
<p>🤔 Os editores de código son a ferramenta indispensable que todo desenvolvedor debe aprender a utilizar. Son programas coas ferramentas necesarias para darlle forma as nosas aplicacións e páxinas web ✨. Hai unha chea deles tanto de escritorio como on-line. Cada un conta coas súas avantaxes e os seus invenientes. En cousas parecidos en outras con características propias, as veces un pode ser mellor ca outro segundo a tecnoloxía coa que esteamos a tratar.
Algúns dos máis populares para o desenvolvemento web son: Visual Studio Code ou Sublime Text.</p>
<h2 id="navegadores" tabindex="-1"><a class="header-anchor" href="#navegadores" aria-hidden="true">#</a> Navegadores</h2>
<p>Os navegadores axudarannos a probar cada un dos nosos avances no desenvolvemento das nosas paxinas web. Os navegadores son tamén onde as persoas, como usuarios finais, poderán ver e interactuar cos nosos produtos dixitais. Algúns dos máis populares son Google Chrome, Safari ou Firefox. Existen versións dalgún deles enfocadas aos desenvolvedores como a versión de Firefox Developer Edition.</p>
<h2 id="git" tabindex="-1"><a class="header-anchor" href="#git" aria-hidden="true">#</a> Git</h2>
<p>Algunha vez che ten pasado que.. accidentalmente eliminas un arquivo dun proxecto ou un dos teus colaboradores edita unha tarefa que xa estaba lista e non sabes qué facer para corrixila?
Git, sirve para solucionar ese tipo de problemas, ao ir tomando un rexistro dos cambios que se realizan dentro dun arquivo/proxecto e permite poder movernos entre as diferentes versións dos arquivos, como se nos movéramos dentro dunha liña do tempo e puder resvisitar cambios anteriores. A este tipo de programas se os coñoce como <strong>control de versiones</strong>. Git, un dos máis populares, tamén é un dos máis empregados no campo laboral. Normalmente o utilizaremos para verificar que os nosos cambios se garden e administrar os avances
do poxecto.</p>
<h2 id="github" tabindex="-1"><a class="header-anchor" href="#github" aria-hidden="true">#</a> Github</h2>
<p>GitHub é unha ferramenta en liña que complementa a Git, permitindo levar un control dos cambios cun respaldo web, tendo así tódolos avances locais cunha copia de respaldo segura en Internet. Ademais GitHub conta con moitas outras ferramentas que optimizan as tarefas de traballo en equipo e a contribución dentro de proxectos de código aberto, ao tempo de ser un bo recurso para ter os nosos proxectos e mostralos a outros desenvolvedores, colaboradores ou selectores laborais.</p>
</div></template>


